/**
 * Regenerates `src/puzzles.ts` (the shipped, solver-verified puzzle list). Run from the
 * repository root (Vite's module runner executes the TypeScript directly):
 *
 *   node -e "import('vite').then(({ runnerImport }) => runnerImport('./packages/games/sliding-blocks/scripts/generate-puzzles.ts'))"
 *
 * Deterministic: the same code always produces the same file. Why a shipped list instead of
 * generating on the device: see `src/generator.ts`.
 */
import { writeFileSync } from 'node:fs';
import { generatePuzzle, type GeneratedPuzzle } from '../src/generator';
import { BANDS, DIFFICULTIES, mirrorLayout, parseLayout, solve, type Difficulty } from '../src/rules';

/** Puzzles per difficulty (each is also offered upside down, doubling the boards). */
const COUNT = 30;

const target = new URL('../src/puzzles.ts', import.meta.url);
const seen = new Set<string>();
const lists = {} as Record<Difficulty, GeneratedPuzzle[]>;

for (const difficulty of DIFFICULTIES) {
  const list: GeneratedPuzzle[] = [];
  const started = Date.now();
  for (let seed = 1; list.length < COUNT; seed++) {
    const puzzle = generatePuzzle(seed, difficulty);
    if (!puzzle || seen.has(puzzle.layout) || seen.has(mirrorLayout(puzzle.layout))) continue;
    const check = solve(parseLayout(puzzle.layout));
    if (check !== puzzle.optimum) throw new Error(`solver disagrees for ${puzzle.layout}: ${check} vs ${puzzle.optimum}`);
    seen.add(puzzle.layout);
    list.push(puzzle);
    console.log(`${difficulty} ${list.length}/${COUNT} seed ${seed}: ${puzzle.layout} (${puzzle.optimum}) after ${Math.round((Date.now() - started) / 1000)} s`);
  }
  list.sort((a, b) => a.optimum - b.optimum || (a.layout < b.layout ? -1 : 1));
  lists[difficulty] = list;
}

const body = DIFFICULTIES.map((difficulty) => {
  const [lo, hi] = BANDS[difficulty];
  const rows = lists[difficulty].map((p) => `    { layout: '${p.layout}', optimum: ${p.optimum} }`).join(',\n');
  return `  /** Optimum ${lo}${difficulty === 'hard' ? '+' : `–${hi}`} moves. */\n  ${difficulty}: [\n${rows}\n  ]`;
}).join(',\n');

writeFileSync(
  target,
  `/**
 * The shipped puzzle list — original, generated by \`scripts/generate-puzzles.ts\` (seeded random
 * placement + exhaustive breadth-first search; nothing is taken from a commercial puzzle set).
 * Do not edit by hand: regenerate instead.
 *
 * \`layout\`: 36 cells, row by row, top to bottom: \`.\` free, \`x\` star block, \`a\`… other blocks.
 * \`optimum\`: fewest moves (one block slid any distance) to free the star block. The test suite
 * re-derives every optimum with an independent solver (test/oracle.ts).
 */
export interface PuzzleSource {
  readonly layout: string;
  readonly optimum: number;
}

export const PUZZLES: Readonly<Record<'easy' | 'medium' | 'hard', readonly PuzzleSource[]>> = {
${body}
};
`
);
console.log(`wrote ${target.pathname}`);
