/** Game catalogue generated by apps/web/catalogue-plugin.ts: metadata per game id with catalogue messages only. */
declare module 'virtual:wp-catalogue' {
  import type { GameMetadata } from '@wp/game-core';
  const catalogue: Readonly<Record<string, GameMetadata>>;
  export default catalogue;
}
