/** Game catalogue generated by apps/web/catalogue-plugin.ts: metadata per game id, without messages. */
declare module 'virtual:wp-catalogue' {
  import type { GameMetadata } from '@wp/game-core';
  const catalogue: Readonly<Record<string, Omit<GameMetadata, 'messages'>>>;
  export default catalogue;
}

/** Catalogue messages (title, tagline, rules, difficulty labels) of one locale, per game id. */
declare module 'virtual:wp-catalogue/*' {
  const messages: Readonly<Record<string, Readonly<Record<string, string>>>>;
  export default messages;
}
