/**
 * Lights Out rules: pure, DOM-free logic, the GF(2) solver and the serializable state.
 *
 * The board is a square grid stored row-major as an array of 0 (off) / 1 (on).
 * Pressing a cell toggles it and its orthogonal neighbours. Because every press is an
 * XOR, pressing a cell twice cancels out and presses commute: a position is fully
 * described by the *set* of cells pressed an odd number of times.
 *
 * Puzzles are generated by pressing a random set of cells on the all-off board, so
 * they are solvable by construction. The solver below is deliberately independent of
 * that construction: it solves `A·x = b` over GF(2) by Gaussian elimination, where `A`
 * is the toggle matrix and `b` the board, and takes the minimum-weight solution over
 * the null space (5×5 has a 2-dimensional null space, 3×3 and 7×7 have none).
 */
import { createRng, isArrayOf, isInt, isOneOf, isRecord, isUint32, normalizeSeed } from '@wp/game-core';

export const DIFFICULTIES = ['easy', 'medium', 'hard'] as const;
export type Difficulty = (typeof DIFFICULTIES)[number];
export const DEFAULT_DIFFICULTY: Difficulty = 'easy';

/** Grid edge length per difficulty. */
export const SIZES: Readonly<Record<Difficulty, number>> = { easy: 3, medium: 5, hard: 7 };

/** Inclusive range for the number of presses in a generated puzzle's shortest solution. */
export const PRESS_RANGE: Readonly<Record<Difficulty, readonly [number, number]>> = {
  easy: [3, 6],
  medium: [6, 12],
  hard: [10, 18]
};

/** Candidates tried before accepting one whose shortest solution is below the range (only relevant for 5×5). */
export const GENERATION_ATTEMPTS = 32;

/** Upper bounds that keep untrusted saves small; far beyond any real play session. */
export const MAX_PRESSES = 10_000;
export const MAX_HINTS = 10_000;

/** 0 = off, 1 = on. */
export type Light = 0 | 1;
export type Board = readonly Light[];

export interface LightsOutState {
  seed: number;
  difficulty: Difficulty;
  /** The generated starting board. */
  start: Light[];
  /** Cells pressed so far, in order (the undo history). */
  presses: number[];
  /** How many hints the user asked for (shown as a stat, never penalised). */
  hints: number;
  /** Cell currently highlighted by a hint, or `null`. Cleared by the next press or undo. */
  hint: number | null;
}

export interface Solution {
  /** Cells of one shortest solution, ascending. */
  presses: number[];
  /** Dimension of the toggle matrix's null space for this grid size. */
  nullity: number;
}

export interface Puzzle {
  board: Light[];
  /** The distinct cells pressed on the all-off board to create it, ascending. */
  presses: number[];
}

export const toDifficulty = (value: unknown): Difficulty => (isOneOf(value, DIFFICULTIES) ? value : DEFAULT_DIFFICULTY);

export const sizeOf = (difficulty: Difficulty): number => SIZES[difficulty];

export const emptyBoard = (size: number): Light[] => Array.from({ length: size * size }, () => 0 as Light);

/** The cell itself and its orthogonal neighbours that lie on the board, ascending. */
export function pressMask(size: number, index: number): number[] {
  const row = Math.floor(index / size);
  const col = index % size;
  const cells: number[] = [];
  if (row > 0) cells.push(index - size);
  if (col > 0) cells.push(index - 1);
  cells.push(index);
  if (col < size - 1) cells.push(index + 1);
  if (row < size - 1) cells.push(index + size);
  return cells;
}

export const isCell = (size: number, index: unknown): index is number => isInt(index, 0, size * size - 1);

/** Returns a new board with `index` pressed. Throws for a cell outside the board. */
export function press(board: Board, size: number, index: number): Light[] {
  if (!isCell(size, index)) throw new RangeError(`No cell ${index} on a ${size}×${size} board`);
  const next = [...board];
  for (const cell of pressMask(size, index)) next[cell] = (1 - (next[cell] as Light)) as Light;
  return next;
}

export function applyPresses(board: Board, size: number, presses: readonly number[]): Light[] {
  let next = [...board];
  for (const index of presses) next = press(next, size, index);
  return next;
}

export const countOn = (board: Board): number => board.reduce<number>((sum, light) => sum + light, 0);

export const isSolved = (board: Board): boolean => board.every((light) => light === 0);

/**
 * Shortest solution of `board` via Gaussian elimination over GF(2), or `null` if the
 * board cannot be cleared. Ties between equally short solutions resolve deterministically.
 */
export function solve(board: Board, size: number): Solution | null {
  const n = size * size;
  if (!Number.isInteger(size) || size < 1 || board.length !== n) throw new RangeError('Board does not match size');

  // Augmented matrix [A | b]; A is symmetric, so row i lists the presses that toggle cell i.
  const rows: number[][] = [];
  for (let i = 0; i < n; i++) {
    const row = new Array<number>(n + 1).fill(0);
    for (const j of pressMask(size, i)) row[j] = 1;
    row[n] = board[i] as number;
    rows.push(row);
  }

  // Reduced row echelon form.
  const pivots: number[] = [];
  for (let col = 0; col < n; col++) {
    const r = pivots.length;
    let p = r;
    while (p < n && rows[p]![col] === 0) p++;
    if (p === n) continue;
    [rows[r], rows[p]] = [rows[p]!, rows[r]!];
    const pivotRow = rows[r]!;
    for (let i = 0; i < n; i++) {
      const row = rows[i]!;
      if (i === r || row[col] === 0) continue;
      for (let k = col; k <= n; k++) row[k] = (row[k]! ^ pivotRow[k]!) as number;
    }
    pivots.push(col);
  }

  // A zero row with right-hand side 1 means 0 = 1: the board is unsolvable.
  for (let i = pivots.length; i < n; i++) if (rows[i]![n] === 1) return null;

  const particular = new Array<number>(n).fill(0);
  pivots.forEach((col, i) => (particular[col] = rows[i]![n]!));

  const isPivot = new Array<boolean>(n).fill(false);
  for (const col of pivots) isPivot[col] = true;
  const basis: number[][] = [];
  for (let free = 0; free < n; free++) {
    if (isPivot[free]) continue;
    const vector = new Array<number>(n).fill(0);
    vector[free] = 1;
    pivots.forEach((col, i) => (vector[col] = rows[i]![free]!));
    basis.push(vector);
  }

  let best = particular;
  let bestWeight = weight(particular);
  for (let combo = 1; combo < 2 ** basis.length; combo++) {
    const candidate = [...particular];
    basis.forEach((vector, b) => {
      if ((combo >> b) & 1) for (let k = 0; k < n; k++) candidate[k] = candidate[k]! ^ vector[k]!;
    });
    const w = weight(candidate);
    if (w < bestWeight) {
      best = candidate;
      bestWeight = w;
    }
  }

  const presses: number[] = [];
  best.forEach((bit, index) => {
    if (bit === 1) presses.push(index);
  });
  return { presses, nullity: basis.length };
}

const weight = (vector: readonly number[]): number => vector.reduce((sum, bit) => sum + bit, 0);

/** Number of presses in a shortest solution, or `null` if unsolvable. */
export function minPresses(board: Board, size: number): number | null {
  return solve(board, size)?.presses.length ?? null;
}

/**
 * Builds a solvable puzzle from a seed: a random number of distinct cells (within the
 * difficulty's press range) is pressed on the all-off board. On 5×5 a candidate's shortest
 * solution can fall below the range (about 1 in 300); such candidates are retried, and after
 * `attempts` candidates the last one is used.
 */
export function generatePuzzle(seed: number, difficulty: Difficulty, attempts = GENERATION_ATTEMPTS): Puzzle {
  if (!Number.isInteger(attempts) || attempts < 1) throw new RangeError('attempts must be a positive integer');
  const size = sizeOf(difficulty);
  const [lo, hi] = PRESS_RANGE[difficulty];
  const rng = createRng(seed);
  const all = Array.from({ length: size * size }, (_, i) => i);
  for (let attempt = 1; ; attempt++) {
    const presses = rng
      .shuffle(all)
      .slice(0, rng.int(lo, hi))
      .sort((a, b) => a - b);
    const board = applyPresses(emptyBoard(size), size, presses);
    if (attempt >= attempts || (minPresses(board, size) ?? 0) >= lo) return { board, presses };
  }
}

/* ---------- Game state ---------- */

export function createInitialState(seed: number, difficulty: Difficulty = DEFAULT_DIFFICULTY): LightsOutState {
  const normalized = normalizeSeed(seed);
  return { seed: normalized, difficulty, start: generatePuzzle(normalized, difficulty).board, presses: [], hints: 0, hint: null };
}

/** The same puzzle from its first move: no presses, no hints. */
export const restartState = (state: LightsOutState): LightsOutState => ({ ...state, start: [...state.start], presses: [], hints: 0, hint: null });

export const stateSize = (state: LightsOutState): number => sizeOf(state.difficulty);

export const currentBoard = (state: LightsOutState): Light[] => applyPresses(state.start, stateSize(state), state.presses);

export const isFinished = (state: LightsOutState): boolean => isSolved(currentBoard(state));

/** Presses `index`. Returns the same object (no change) when finished or the cell is invalid. */
export function pressCell(state: LightsOutState, index: number): LightsOutState {
  if (!isCell(stateSize(state), index) || isFinished(state)) return state;
  return { ...state, start: [...state.start], presses: [...state.presses, index], hint: null };
}

export const canUndo = (state: LightsOutState): boolean => state.presses.length > 0 && !isFinished(state);

/** Takes back the last press. Returns the same object when there is nothing to undo or the puzzle is solved. */
export function undo(state: LightsOutState): LightsOutState {
  if (!canUndo(state)) return state;
  return { ...state, start: [...state.start], presses: state.presses.slice(0, -1), hint: null };
}

/** First cell (in reading order) of a shortest solution from the current board, or `null` when solved. */
export function hintFor(board: Board, size: number): number | null {
  return solve(board, size)?.presses[0] ?? null;
}

/**
 * Highlights one cell of a shortest solution and counts the hint. Returns the same object
 * when solved or when a hint is already showing (asking again is not counted twice).
 */
export function requestHint(state: LightsOutState): LightsOutState {
  if (state.hint !== null) return state;
  const cell = hintFor(currentBoard(state), stateSize(state));
  if (cell === null) return state;
  return { ...state, start: [...state.start], presses: [...state.presses], hints: state.hints + 1, hint: cell };
}

/* ---------- Validation ---------- */

const isLight = (value: unknown): value is Light => value === 0 || value === 1;

/** Structural and cross-field validation of untrusted saved data. Never throws. */
export function isLightsOutState(value: unknown): value is LightsOutState {
  if (!isRecord(value)) return false;
  const { seed, difficulty, start, presses, hints, hint } = value;
  if (!isUint32(seed) || !isOneOf(difficulty, DIFFICULTIES)) return false;
  const size = sizeOf(difficulty);
  if (!isArrayOf(start, isLight, size * size)) return false;
  if (!Array.isArray(presses) || presses.length > MAX_PRESSES || !presses.every((p) => isCell(size, p))) return false;
  if (!isInt(hints, 0, MAX_HINTS)) return false;
  if (hint !== null && !isCell(size, hint)) return false;
  // The start must be a real puzzle: lit and solvable.
  if (isSolved(start) || solve(start, size) === null) return false;
  // Play stops once all lights are off, so only the very last press may reach that.
  let board: Light[] = [...start];
  for (const index of presses) {
    if (isSolved(board)) return false;
    board = press(board, size, index);
  }
  return !(isSolved(board) && hint !== null);
}
