import type { ContentText } from './types';

export const content: ContentText = {
  migration: {
    title: 'Datenbankmigration',
    situation: 'Dein Team zieht die Kundendatenbank auf ein neues System um. Die Tests haben ein Problem gefunden, die Umstellung verzögert sich. Erkläre es.',
    facts: {
      newDate: 'Die Umstellung verschiebt sich um zwei Tage: Donnerstag statt Dienstag.',
      cause: 'Die Tests haben einen bisher unbekannten Fehler bei Sonderzeichen wie ü oder é gefunden.',
      noLoss: 'Es sind keine Daten verloren gegangen.',
      encoding: 'Das Importskript liest Text in der falschen Zeichenkodierung.',
      apology: 'Wir entschuldigen uns für die Unannehmlichkeiten.',
      regression: 'Ein neuer automatischer Test prüft jetzt Sonderzeichen.',
      buffer: 'Die zwei Tage passen in den Zeitpuffer des Projekts, ohne Mehrkosten.',
      library: 'Die fehlerhafte Umwandlung stammt aus einer Bibliothek, die vor Jahren gewählt wurde.'
    },
    reasons: {
      'developer.cause': 'Entwickler müssen wissen, was die Tests tatsächlich gefunden haben.',
      'developer.encoding': 'Das ist die eigentliche Ursache, an der sie arbeiten werden.',
      'developer.apology': 'Eine Entschuldigung an Kunden hilft einer Kollegin nicht, den Fehler zu beheben.',
      'developer.regression': 'Sie müssen wissen, dass der Fehler jetzt durch einen Test abgedeckt ist.',
      'developer.buffer': 'Zeitpuffer und Budget sind Sache der Projektleitung.',
      'projectManager.newDate': 'Die Projektleitung plant mit dem neuen Termin.',
      'projectManager.noLoss': 'Datenverlust würde das Risiko völlig verändern, deshalb muss sie hören, dass es keinen gibt.',
      'projectManager.encoding': 'Das Detail zur Kodierung ändert keine Planungsentscheidung.',
      'projectManager.apology': 'Eine Entschuldigung ist für Kunden; die Projektleitung braucht Fakten.',
      'projectManager.buffer': 'Ob Zeitplan und Budget noch halten, ist genau ihre Frage.',
      'projectManager.library': 'Wer vor Jahren eine Bibliothek gewählt hat, hilft der Planung jetzt nicht.',
      'customer.newDate': 'Der Kunde braucht den neuen Termin, nicht die Fehlerklasse.',
      'customer.noLoss': 'Seine erste Sorge gilt seinen Daten – und die sind sicher.',
      'customer.cause': 'Fehlerdetails beunruhigen Kunden, ohne ihnen zu helfen.',
      'customer.encoding': 'Technische Interna sagen dem Kunden nichts.',
      'customer.regression': 'Interne Tests sind nicht Sache des Kunden.',
      'customer.buffer': 'Interne Puffer und Kosten gehen den Kunden nichts an.',
      'customer.library': 'Die Schuld auf eine alte Bibliothek zu schieben, klingt nach Ausrede.'
    },
    messages: {
      'developer.fit': 'Kurze Info: Das Importskript liest Text in der falschen Kodierung, deshalb gehen Sonderzeichen wie ü und é kaputt. Ein Regressionstest deckt das jetzt ab; die Umstellung verschiebt sich auf Donnerstag.',
      'developer.missing': 'Kleine Verzögerung bei der Migration, nichts Wildes. Details später.',
      'developer.condescending': 'Sonderzeichen sind Buchstaben wie ü, die nicht im Grundalphabet vorkommen. Computer speichern Buchstaben als Zahlen, und manchmal geraten die Zahlen durcheinander.',
      'projectManager.fit': 'Die Migration verschiebt sich von Dienstag auf Donnerstag. Es gingen keine Daten verloren, und die zwei Tage passen ohne Mehrkosten in unseren Puffer. Ursache: ein Fehler bei Sonderzeichen, jetzt durch einen Test abgedeckt.',
      'projectManager.tooMuch': 'Das Importskript dekodiert die Eingabe als Latin-1 statt UTF-8, dadurch werden Mehrbyte-Zeichen zerstört; wir patchen den Reader und ergänzen einen Regressionstest.',
      'projectManager.missing': 'Wir haben einen Fehler gefunden und arbeiten daran. Wir melden uns.',
      'customer.fit': 'Ihre Daten sind sicher. Damit jeder Name und jede Adresse korrekt übernommen wird, verschieben wir die Umstellung von Dienstag auf Donnerstag. Bis dahin funktioniert alles wie gewohnt.',
      'customer.tooMuch': 'Unser Importskript hat die falsche Zeichenkodierung verwendet, wodurch Sonderzeichen in Testläufen beschädigt wurden; die Migration braucht daher zwei zusätzliche Tage aus unserem Puffer.',
      'customer.condescending': 'Machen Sie sich keine Gedanken über die Technik, das ist kompliziert. Es dauert einfach etwas länger.'
    }
  },
  skyBlue: {
    title: 'Warum der Himmel blau ist',
    situation: 'Jemand fragt dich, warum der Himmel blau ist. Du kennst die Physik dahinter. Erkläre es.',
    facts: {
      sunlight: 'Sonnenlicht enthält alle Farben.',
      scatter: 'Luft streut blaues Licht viel stärker als rotes.',
      rayleigh: 'Diese Rayleigh-Streuung wächst mit der vierten Potenz der Frequenz (1/λ⁴).',
      sunset: 'Bei Sonnenuntergang legt das Licht mehr Weg durch die Luft zurück, deshalb wird der Himmel rot und orange.',
      everywhere: 'Gestreutes blaues Licht erreicht deine Augen aus allen Richtungen, deshalb wirkt der ganze Himmel blau.',
      violet: 'Violett wird noch stärker gestreut, aber Sonnenlicht enthält weniger Violett und unsere Augen sind dafür weniger empfindlich.',
      molecules: 'Die Streuung entsteht an Stickstoff- und Sauerstoffmolekülen, die viel kleiner sind als die Wellenlänge des Lichts.',
      ocean: 'Der Himmel ist blau, weil er das Meer spiegelt.'
    },
    reasons: {
      'child.sunlight': 'Kinder brauchen zuerst die Überraschung: Im weißen Sonnenlicht stecken alle Farben.',
      'child.scatter': 'Das ist die Kernidee, in einfachen Worten.',
      'child.rayleigh': 'Mit einer Formel verliert man ein Kind sofort.',
      'child.everywhere': 'Es erklärt, was sie sehen: Blau, wohin sie auch schauen.',
      'child.violet': 'Das Detail mit Violett verwirrt in diesem Alter mehr, als es hilft.',
      'child.molecules': 'Moleküle und Wellenlängen sind für ein Kind zu abstrakt.',
      'layperson.sunlight': 'Ohne das ergibt „blaues Licht wird gestreut“ keinen Sinn.',
      'layperson.scatter': 'Das ist die eigentliche Antwort, in Alltagssprache.',
      'layperson.rayleigh': 'Die Formel bringt Laien nichts, was sie nutzen können.',
      'expert.rayleigh': 'Eine Fachperson erwartet den genauen Mechanismus und seine Abhängigkeit von der Wellenlänge.',
      'expert.everywhere': 'Das ist für Fachleute selbstverständlich und kostet nur Zeit.',
      'expert.violet': 'Fachleute kennen den naheliegenden Einwand „Warum nicht violett?“ – beantworte ihn.',
      'expert.molecules': 'Die Streuer und das Größenverhältnis zu nennen, macht die Erklärung präzise.',
      ocean: 'Das ist ein verbreiteter Irrtum; die Farbe kommt nicht vom Meer.'
    },
    messages: {
      'child.fit': 'Sonnenlicht sieht weiß aus, aber eigentlich sind alle Farben darin gemischt. Wenn es durch die Luft fliegt, wird der blaue Teil am meisten herumgeschubst – deshalb kommt Blau von überall am Himmel zu deinen Augen.',
      'child.tooMuch': 'Blaues Licht hat eine kürzere Wellenlänge, und die Rayleigh-Streuung wächst mit eins durch die Wellenlänge hoch vier.',
      'child.missing': 'Der Himmel ist halt so. Er war schon immer blau.',
      'layperson.fit': 'Sonnenlicht enthält alle Farben. Die Luft streut blaues Licht viel stärker als rotes, deshalb erreicht uns blaues Licht aus jedem Teil des Himmels.',
      'layperson.tooMuch': 'Das ist Rayleigh-Streuung: Die Intensität skaliert mit 1/λ⁴, daher dominieren kurze Wellenlängen die diffuse Himmelsstrahlung.',
      'layperson.condescending': 'Das ist für Nicht-Wissenschaftler etwas kompliziert. Sagen wir einfach: Die Luft macht ihn blau.',
      'expert.fit': 'Rayleigh-Streuung an N₂- und O₂-Molekülen, proportional zu 1/λ⁴. Violett wird noch stärker gestreut, aber das Sonnenspektrum enthält weniger Violett und unsere Zapfen sind dafür weniger empfindlich.',
      'expert.condescending': 'Stell dir das Sonnenlicht als Schachtel Buntstifte vor! Die Luft spielt am liebsten mit dem blauen Stift.',
      'expert.missing': 'Die Luft streut blaues Licht stärker, deshalb.'
    }
  },
  clubRoof: {
    title: 'Dach des Vereinsheims',
    situation: 'Das Dach des Vereinsheims eures Sportvereins muss dringend repariert werden, und es kostet mehr als geplant. Erkläre es.',
    facts: {
      cost: 'Die Reparatur kostet 8.000 Euro, 3.000 mehr als geplant.',
      decision: 'Der Vorstand muss bis Freitag entscheiden, ob 3.000 Euro aus dem Budget für das Sommerfest umgeschichtet werden.',
      storage: 'Der Geräteraum bleibt bis zur Reparatur geschlossen; der Rest des Vereinsheims ist offen.',
      fees: 'Die Mitgliedsbeiträge ändern sich nicht.',
      schedule: 'Der Dachdecker beginnt am 12. Mai und braucht vier Tage; der Parkplatz wird für das Gerüst gebraucht.',
      tiles: 'Die neuen Ziegel sind anthrazitfarbene Betondachsteine.',
      reserve: 'Würde man stattdessen die Rücklage nutzen, fiele sie unter das vorgeschriebene Minimum.',
      volunteer: 'Ein Mitglied hat angeboten, das Dach kostenlos selbst zu reparieren, ist aber kein Dachdecker.'
    },
    reasons: {
      'executive.cost': 'Der Vorstand braucht den Betrag und die Überschreitung, um es zu beurteilen.',
      'executive.decision': 'Das ist die Entscheidung, die er treffen muss – samt Frist.',
      'executive.storage': 'Die tägliche Raumnutzung ist keine Frage für den Vorstand.',
      'executive.schedule': 'Die genauen Arbeitstage sind Aufgabe der Koordination.',
      'executive.tiles': 'Art und Farbe der Ziegel beeinflussen die Entscheidung nicht.',
      'executive.reserve': 'Es erklärt, warum die naheliegende Alternative nicht infrage kommt.',
      'projectManager.fees': 'Beiträge haben mit der Organisation der Reparatur nichts zu tun.',
      'projectManager.schedule': 'Genau diese Termine und den Parkplatz organisiert die Koordination.',
      'projectManager.reserve': 'Die Finanzierung entscheidet der Vorstand, nicht die Koordination.',
      'layperson.storage': 'Mitglieder wollen wissen, was sie nutzen können und was nicht.',
      'layperson.fees': 'Ihr eigenes Geld ist ihre erste Frage.',
      'layperson.tiles': 'Materialdetails sind für Mitglieder unwichtig.',
      'layperson.reserve': 'Regeln zur Rücklage sind interne Finanzdetails.',
      volunteer: 'Ein Angebot ohne passende Qualifikation löst nur eine sinnlose Debatte aus; es ist keine echte Option.'
    },
    messages: {
      'executive.fit': 'Entscheidung bis Freitag nötig: Die Dachreparatur kostet 8.000 Euro, 3.000 mehr als geplant. Wir schlagen vor, 3.000 aus dem Sommerfest-Budget umzuschichten, weil die Rücklage sonst unter ihr Minimum fiele.',
      'executive.tooMuch': 'Der Dachdecker beginnt am 12. Mai mit anthrazitfarbenen Betondachsteinen; das Gerüst steht vier Tage auf dem Parkplatz, und der Geräteraum bleibt bis dahin zu.',
      'executive.missing': 'Das Dach wird teurer. Wir halten euch auf dem Laufenden.',
      'projectManager.fit': 'Der Dachdecker beginnt am 12. Mai und braucht vier Tage. Bitte haltet den Parkplatz ab dem 11. Mai für das Gerüst frei.',
      'projectManager.tooMuch': 'Die Reparatur kostet 8.000 Euro, 3.000 über Plan; der Vorstand schichtet eventuell Geld vom Sommerfest um, weil die Rücklage nicht unter ihr Minimum fallen darf, und die Beiträge bleiben gleich.',
      'projectManager.missing': 'Im Mai stehen irgendwann Arbeiten am Dach an.',
      'layperson.fit': 'Das Dach des Vereinsheims wird im Mai repariert. Bis dahin bleibt der Geräteraum geschlossen; alles andere ist wie gewohnt offen. Die Mitgliedsbeiträge ändern sich nicht.',
      'layperson.tooMuch': 'Die Reparatur kostet 8.000 Euro, 3.000 über Plan; der Vorstand prüft eine Umschichtung aus dem Sommerfest-Budget, weil die Rücklage nicht unter ihr Minimum fallen darf.',
      'layperson.condescending': 'Macht euch keine Gedanken ums Dach, um den Erwachsenenkram kümmert sich der Vorstand.'
    }
  },
  shopOutage: {
    title: 'Ausfall des Onlineshops',
    situation: 'Der Onlineshop deiner Firma war gestern drei Stunden lang nicht erreichbar. Erkläre, was passiert ist.',
    facts: {
      duration: 'Der Shop war gestern Abend drei Stunden lang ausgefallen.',
      revenue: 'Bestellungen im Wert von etwa 40.000 Euro gingen verloren.',
      cause: 'Ein abgelaufenes Sicherheitszertifikat hat die Zahlungen gestoppt.',
      fixed: 'Das Zertifikat ist erneuert; der Shop funktioniert wieder normal.',
      renewal: 'Die Erneuerung wird automatisiert, mit einer Warnung zwei Wochen vorher; das kostet das Team einen Tag.',
      voucher: 'Kunden, deren Bestellung fehlschlug, erhalten per E-Mail einen Gutschein über 10 %.',
      approval: 'Die Geschäftsführung wird gebeten, 5.000 Euro für besseres Monitoring freizugeben.',
      competitor: 'Der Shop eines Mitbewerbers hatte letzten Monat einen ähnlichen Ausfall.'
    },
    reasons: {
      'projectManager.cause': 'Die Projektleitung braucht die Ursache, um die Lösung zu beurteilen.',
      'projectManager.renewal': 'Das ist die Arbeit, die sie einplanen muss: einen Tag des Teams.',
      'projectManager.voucher': 'Gutscheine erledigt der Kundenservice, nicht das Projekt.',
      'executive.duration': 'Die Geschäftsführung braucht das Ausmaß des Vorfalls.',
      'executive.revenue': 'Für die Geschäftsführung kommt die geschäftliche Auswirkung zuerst.',
      'executive.cause': 'Das technische Detail ändert ihre Entscheidung nicht; „eine versäumte Erneuerung“ genügt.',
      'executive.renewal': 'Sie muss hören, dass es nicht wieder passiert.',
      'executive.approval': 'Das ist die Entscheidung, die sie treffen muss.',
      'customer.revenue': 'Dein entgangener Umsatz ist nicht das Problem der Kunden.',
      'customer.cause': 'Technische Ursachen helfen Kunden nicht.',
      'customer.fixed': 'Kunden wollen zuerst wissen, dass sie wieder einkaufen können.',
      'customer.renewal': 'Interne Prozessänderungen gehen Kunden nichts an.',
      'customer.voucher': 'Das bekommen sie – und sie sollten nach der E-Mail schauen.',
      'customer.approval': 'Interne Budgetentscheidungen sind nichts für Kunden.',
      competitor: 'Auf andere zu zeigen, klingt nach Ausrede und ändert nichts.'
    },
    messages: {
      'projectManager.fit': 'Der dreistündige Ausfall gestern kam von einem abgelaufenen Sicherheitszertifikat, das die Zahlungen gestoppt hat. Damit es nicht wieder passiert, automatisieren wir die Erneuerung mit Vorwarnung; das kostet das Team in diesem Sprint einen Tag.',
      'projectManager.tooMuch': 'Wir haben Bestellungen für etwa 40.000 Euro verloren, Kunden bekommen einen 10-%-Gutschein per E-Mail, und ein Mitbewerber hatte letzten Monat dasselbe Problem.',
      'projectManager.missing': 'Der Shop hatte gestern einen kurzen Schluckauf, jetzt ist alles gut.',
      'executive.fit': 'Gestern war der Shop drei Stunden lang ausgefallen; uns sind Bestellungen für etwa 40.000 Euro entgangen. Ursache war eine versäumte Routine-Erneuerung, die jetzt automatisiert ist. Um solche Probleme früh zu erkennen, bitten wir um Freigabe von 5.000 Euro für Monitoring.',
      'executive.tooMuch': 'Das TLS-Zertifikat des Payment-Gateways lief um 18:02 Uhr ab; wir erneuern es jetzt automatisch über das ACME-Protokoll, mit Alarm 14 Tage vorher.',
      'executive.missing': 'Gestern gab es ein kleines technisches Problem. Es ist behoben.',
      'customer.fit': 'Entschuldigung: Gestern Abend war unser Shop einige Stunden nicht erreichbar. Jetzt funktioniert alles wieder. Falls Ihre Bestellung fehlgeschlagen ist, erhalten Sie per E-Mail einen Gutschein über 10 %.',
      'customer.tooMuch': 'Ein abgelaufenes Sicherheitszertifikat hat unser Zahlungssystem gestoppt; wir haben etwa 40.000 Euro verloren und erneuern Zertifikate jetzt automatisch.',
      'customer.condescending': 'Irgendein technisches Ding war kaputt, das würden Sie eh nicht verstehen. Versuchen Sie es einfach noch mal.'
    }
  },
  signalFault: {
    title: 'Signalstörung bei der Bahn',
    situation: 'Eine Signalstörung legt eine Bahnstrecke lahm. Du arbeitest bei der Bahn. Erkläre die Lage.',
    facts: {
      delay: 'Die Züge auf dieser Strecke sind etwa 40 Minuten verspätet.',
      bus: 'Ersatzbusse fahren alle 20 Minuten vom Bahnhofsvorplatz ab.',
      tickets: 'Fahrkarten gelten auch in den Bussen und in späteren Zügen.',
      signal: 'Signal 14 an der Abzweigung zeigt nach einem Kabelschaden dauerhaft Rot.',
      singleTrack: 'Die Züge passieren den Abschnitt eingleisig in Schrittgeschwindigkeit, mit schriftlichem Befehl.',
      repair: 'Die Technik rechnet damit, dass die Reparatur noch etwa vier Stunden dauert.',
      construction: 'Vermutlich hat eine Baustelle einer anderen Firma das Kabel beschädigt.',
      staff: 'Zwei Techniker sind diese Woche krank.'
    },
    reasons: {
      'layperson.delay': 'Fahrgäste wollen zuerst wissen, wie spät sie kommen.',
      'layperson.bus': 'Es sagt ihnen, was sie jetzt sofort tun können.',
      'layperson.tickets': 'Es beantwortet die Sorge, ob sie eine neue Fahrkarte brauchen.',
      'layperson.signal': 'Signalnummern sagen Fahrgästen nichts.',
      'layperson.singleTrack': 'Betriebsregeln helfen Fahrgästen nicht.',
      'layperson.construction': 'Spekulationen über Schuld helfen Fahrgästen nicht und können falsch sein.',
      'layperson.staff': 'Interne Personalfragen gehen Fahrgäste nichts an.',
      'expert.tickets': 'Fahrkartenregeln beeinflussen den Zugbetrieb nicht.',
      'expert.signal': 'Die Kollegin braucht genauen Ort und genaue Störung.',
      'expert.singleTrack': 'Das ist die Betriebsregel, die sie anwenden muss.',
      'expert.repair': 'Sie plant den Fahrplan um das erwartete Ende herum.',
      'expert.staff': 'Die Personallage ändert nicht, wie der Abschnitt betrieben wird.',
      'executive.delay': 'Die Leitung braucht das Ausmaß der Störung.',
      'executive.tickets': 'Die Anerkennung von Fahrkarten ist eine Standardregel, kein Leitungsthema.',
      'executive.repair': 'Sie muss wissen, wie lange die Auswirkungen dauern.',
      'executive.construction': 'Ein möglicher Schaden durch Dritte ist für Haftung und Kosten wichtig.'
    },
    messages: {
      'layperson.fit': 'Die Züge auf dieser Strecke sind etwa 40 Minuten verspätet. Ersatzbusse fahren alle 20 Minuten vom Bahnhofsvorplatz, und Ihre Fahrkarte gilt darin.',
      'layperson.tooMuch': 'Signal 14 an der Abzweigung zeigt nach einem Kabelschaden dauerhaft Rot; die Züge fahren eingleisig in Schrittgeschwindigkeit mit schriftlichem Befehl.',
      'layperson.missing': 'Bitte haben Sie Geduld, es liegt eine technische Störung vor.',
      'expert.fit': 'Signal 14 an der Abzweigung steht nach Kabelschaden auf Rot. Eingleisiger Betrieb in Schrittgeschwindigkeit mit schriftlichem Befehl; Reparatur dauert voraussichtlich noch etwa vier Stunden.',
      'expert.condescending': 'Ein Signal ist so etwas wie eine Ampel für Züge. Eins davon ist kaputt, deshalb müssen die Züge langsam fahren.',
      'expert.missing': 'Auf der Strecke gibt es ein Problem, die Züge sind verspätet. Busse fahren.',
      'executive.fit': 'Ein Kabelschaden stört die Strecke noch etwa vier Stunden; die Züge fahren rund 40 Minuten verspätet. Vermutlich hat eine Baustelle einer anderen Firma das Kabel beschädigt, wir prüfen die Haftung.',
      'executive.tooMuch': 'Signal 14 zeigt dauerhaft Rot; eingleisiger Betrieb in Schrittgeschwindigkeit mit schriftlichem Befehl; Busse alle 20 Minuten vom Vorplatz; Fahrkarten gelten in den Bussen.',
      'executive.missing': 'Kleines Signalproblem, das Team kümmert sich.'
    }
  },
  kettleLid: {
    title: 'Wasserkocher-Deckel',
    situation: 'Deine Firma hat festgestellt, dass sich der Deckel eines Wasserkocher-Modells lösen kann. Erkläre es.',
    facts: {
      batches: 'Betroffen sind nur Wasserkocher mit den Chargennummern 2301 bis 2315 (aufgedruckt unter dem Sockel).',
      risk: 'Der Deckel kann beim Ausgießen aufgehen, sodass heißes Wasser spritzen kann.',
      stop: 'Benutzen Sie einen betroffenen Wasserkocher nicht mehr, bis er ersetzt ist.',
      hinge: 'Ein Scharnierstift aus Kunststoff wurde 0,2 mm zu dünn gefertigt.',
      free: 'Der Ersatz ist kostenlos, einschließlich Versand.',
      cost: 'Der Austausch kostet die Firma etwa 120.000 Euro.',
      supplier: 'Die Stifte kamen von einem neuen Zulieferer, dessen Muster die Prüfung bestanden hatten.',
      injuries: 'Bisher sind keine Verletzungen bekannt.'
    },
    reasons: {
      'customer.batches': 'Kunden müssen prüfen können, ob ihr Wasserkocher betroffen ist.',
      'customer.risk': 'Sie müssen verstehen, warum es wichtig ist.',
      'customer.stop': 'Das ist die Handlung, die sie schützt.',
      'customer.hinge': 'Millimeterangaben helfen Kunden nicht.',
      'customer.free': 'Zu wissen, dass es nichts kostet, nimmt einen Grund zum Zögern.',
      'customer.cost': 'Die Kosten der Firma sind nicht das Problem der Kunden.',
      'customer.supplier': 'Details zum Zulieferer klingen danach, die Schuld abzuschieben.',
      'executive.risk': 'Die Geschäftsführung muss zuerst das Sicherheitsrisiko verstehen.',
      'executive.hinge': 'Das genaue Maß ist etwas für die Technik.',
      'executive.cost': 'Die finanzielle Auswirkung gehört zu ihrer Entscheidung.',
      'executive.injuries': 'Ob jemand verletzt wurde, ändert Dringlichkeit und Reaktion.',
      'expert.stop': 'Anweisungen für Kunden helfen nicht, den Fehler zu analysieren.',
      'expert.hinge': 'Die Ingenieurin braucht den genauen Fehler.',
      'expert.free': 'Versandbedingungen spielen für die technische Analyse keine Rolle.',
      'expert.cost': 'Die Kosten des Rückrufs braucht man nicht, um das Teil zu verbessern.',
      'expert.supplier': 'Es zeigt, wo sich die Qualitätsprüfung ändern muss.'
    },
    messages: {
      'customer.fit': 'Bitte prüfen Sie die Chargennummer unter Ihrem Wasserkocher. Liegt sie zwischen 2301 und 2315, benutzen Sie ihn nicht mehr: Der Deckel kann beim Ausgießen aufgehen. Wir ersetzen ihn kostenlos, inklusive Versand.',
      'customer.tooMuch': 'Ein Scharnierstift eines neuen Zulieferers war 0,2 mm zu dünn; der Austausch kostet uns etwa 120.000 Euro.',
      'customer.condescending': 'Manche Wasserkocher haben vielleicht ein winziges Problem. Die Details müssen Sie nicht verstehen; schicken Sie ihn zurück, wenn Sie möchten.',
      'executive.fit': 'Sicherheitsproblem: Bei den Chargen 2301 bis 2315 kann der Deckel beim Ausgießen von heißem Wasser aufgehen. Bisher keine Verletzungen bekannt. Der Austausch kostet etwa 120.000 Euro.',
      'executive.tooMuch': 'Der Durchmesser des Scharnierstifts liegt 0,2 mm unter der Toleranz; die Muster des neuen Zulieferers waren in Spezifikation, wir vermuten Werkzeugverschleiß.',
      'executive.missing': 'Wir tauschen vorsorglich einige Wasserkocher aus.',
      'expert.fit': 'Die Scharnierstifte des neuen Zulieferers sind 0,2 mm zu dünn, deshalb kann der Deckel beim Ausgießen aufgehen. Betroffene Chargen: 2301 bis 2315. Die Muster hatten bestanden, also muss sich unsere Wareneingangsprüfung ändern.',
      'expert.missing': 'Manche Deckel sind locker; Kunden bekommen kostenlosen Ersatz.',
      'expert.condescending': 'Ein Scharnier ist das Teil, mit dem sich der Deckel dreht. Wenn es zu dünn ist, hält es nicht gut.'
    }
  },
  renovation: {
    title: 'Verzögerte Renovierung',
    situation: 'Du leitest die Baufirma, die Küche und Bad in einer Doppelhaushälfte renoviert. Die Arbeiten verzögern sich. Erkläre es.',
    facts: {
      delay: 'Die Renovierung wird eine Woche später fertig: am 21. Juni statt am 14. Juni.',
      tiles: 'Der Lieferant hat Badfliesen in 30 × 60 cm statt 60 × 60 cm geliefert, sie müssen neu bestellt werden.',
      order: 'Bis die neuen Fliesen da sind, arbeitet die Kolonne zuerst an der Küche.',
      water: 'Die gemeinsame Wasserleitung wird am Dienstag von 8 bis 12 Uhr abgestellt.',
      noise: 'Lautes Bohren dauert nächste Woche noch drei Tage, zwischen 8 und 17 Uhr.',
      cost: 'Die Verzögerung kostet die Eigentümer nichts; der Lieferant zahlt die neuen Fliesen.',
      supplierHistory: 'Dieser Fliesenlieferant hatte dieses Jahr schon mehrmals Lieferprobleme.',
      skip: 'Am Montag steht der Container auf der Straße vor der Einfahrt der Nachbarn.'
    },
    reasons: {
      'customer.delay': 'Die Eigentümer planen mit dem neuen Fertigstellungstermin.',
      'customer.tiles': 'Das genaue Fliesenformat ist Sache der Kolonne; die Eigentümer brauchen Termin und Kosten.',
      'customer.water': 'Sie müssen wissen, wann sie kein Wasser haben.',
      'customer.cost': 'Ihre erste Sorge ist, ob die Verzögerung sie Geld kostet.',
      'projectManager.delay': 'Der Vorarbeiter plant die restlichen Arbeiten auf den neuen Termin hin.',
      'projectManager.tiles': 'Die Kolonne muss genau wissen, was an der Lieferung falsch ist.',
      'projectManager.order': 'Das macht die Kolonne morgen früh.',
      'projectManager.water': 'Die Kolonne stellt das Wasser ab und muss alle vorwarnen.',
      'projectManager.cost': 'Wer zahlt, klären Büro und Lieferant; an der Arbeit ändert das nichts.',
      'projectManager.skip': 'Der Vorarbeiter muss klären, wo der Container hinkommt.',
      'neighbour.tiles': 'Fliesendetails gehen die Nachbarn nichts an.',
      'neighbour.order': 'Die Arbeitsreihenfolge der Kolonne betrifft die Nachbarn nicht.',
      'neighbour.water': 'Die Nachbarn teilen die Leitung und brauchen die genauen Zeiten.',
      'neighbour.noise': 'Lärmzeiten betreffen die Nachbarn am meisten.',
      'neighbour.cost': 'Die Kosten der Eigentümer sind privat.',
      'neighbour.skip': 'Der Container blockiert ihre Einfahrt, also müssen sie es vorher wissen.',
      supplierHistory: 'Über den Lieferanten zu klagen, klingt nach Ausrede und hilft niemandem.'
    },
    messages: {
      'customer.fit': 'Ihre Renovierung wird am 21. Juni statt am 14. Juni fertig, weil die Badfliesen in der falschen Größe geliefert wurden. Das kostet Sie nichts. Bitte beachten Sie: Am Dienstag ist das Wasser von 8 bis 12 Uhr abgestellt.',
      'customer.tooMuch': 'Der Lieferant hat 30 × 60 statt 60 × 60 geschickt, deshalb passt der Verlegeplan nicht mehr; die Kolonne macht jetzt zuerst die Küche, und der Container kommt am Montag auf die Straße.',
      'customer.condescending': 'Es gibt einen kleinen Haken mit den Fliesen, darüber müssen Sie sich keine Gedanken machen. Überlassen Sie das den Profis.',
      'projectManager.fit': 'Die Badfliesen kamen in 30 × 60 statt 60 × 60, also erst die Küche, bis die Nachbestellung da ist. Neuer Fertigstellungstermin: 21. Juni. Wasser am Dienstag von 8 bis 12 Uhr aus, und der Container kommt am Montag auf die Straße.',
      'projectManager.missing': 'Beim Bad gibt es Verzögerung. Macht irgendwie weiter.',
      'projectManager.condescending': 'Fliesen haben eine Größe, und wenn die Größe falsch ist, passen sie nicht. Also bitte nicht verlegen.',
      'neighbour.fit': 'Zur Renovierung nebenan: Am Dienstag ist die gemeinsame Wasserleitung von 8 bis 12 Uhr abgestellt, und nächste Woche wird noch drei Tage laut gebohrt, zwischen 8 und 17 Uhr. Am Montag steht der Container vor Ihrer Einfahrt. Entschuldigen Sie die Umstände.',
      'neighbour.tooMuch': 'Die Badfliesen kamen im falschen Format, daher wechselt die Kolonne zur Küche, und die Eigentümer zahlen nichts extra, weil der Lieferant das übernimmt.',
      'neighbour.missing': 'Wir bauen nebenan ein bisschen. Danke für Ihre Geduld.'
    }
  },
  schoolTrip: {
    title: 'Änderung beim Klassenausflug',
    situation: 'Du bist Klassenlehrer/in. Das Busunternehmen hat abgesagt, deshalb muss der Ausflug in den Zoo verschoben werden. Erkläre es.',
    facts: {
      newDate: 'Der Zooausflug wird von Donnerstag auf nächsten Dienstag verschoben.',
      bus: 'Das Busunternehmen hat abgesagt, weil zwei Fahrer krank sind.',
      lunch: 'Die Kinder bringen wie geplant ein Lunchpaket und etwas zu trinken mit.',
      form: 'Die Eltern müssen bis Freitag eine neue Einverständniserklärung unterschreiben.',
      price: 'Der Preis bleibt bei 12 Euro pro Kind.',
      cover: 'Am Dienstag muss jemand meinen Unterricht in der 7b von 10 bis 12 Uhr vertreten.',
      rain: 'Bei starkem Regen besucht die Klasse stattdessen das Aquarienhaus.',
      complaint: 'Einige Eltern haben sich beschwert, dass der Donnerstag ohnehin ungünstig war.'
    },
    reasons: {
      'child.newDate': 'Kinder wollen zuerst wissen, wann der Ausflug stattfindet.',
      'child.bus': 'Kranke Busfahrer sind nichts, worüber Kinder nachdenken müssen.',
      'child.lunch': 'Das müssen sie selbst mitbringen.',
      'child.form': 'Die Erklärung unterschreiben die Eltern, nicht die Kinder.',
      'child.price': 'Ums Geld kümmern sich die Eltern.',
      'child.cover': 'Absprachen zwischen Lehrkräften betreffen die Kinder nicht.',
      'child.rain': 'Es sagt ihnen, was sie erwartet – das wissen Kinder gern.',
      'parent.newDate': 'Eltern brauchen den neuen Termin, um ihre Woche zu planen.',
      'parent.lunch': 'Sie bereiten das Lunchpaket vor.',
      'parent.form': 'Das müssen sie tun, und zwar bis zu einer Frist.',
      'parent.price': 'Sie wollen wissen, ob es teurer wird.',
      'parent.cover': 'Vertretungsstunden sind eine schulinterne Angelegenheit.',
      'parent.rain': 'Es hilft ihnen, ihr Kind auf das Wetter vorzubereiten.',
      'colleague.newDate': 'Die Kollegin muss wissen, welcher Tag betroffen ist.',
      'colleague.lunch': 'Lunchpakete sind für die Klasse, nicht für die Kollegin.',
      'colleague.price': 'Der Preis des Ausflugs betrifft die Kollegin nicht.',
      'colleague.cover': 'Darum bittest du sie eigentlich.',
      'colleague.rain': 'Der Schlechtwetterplan ändert ihren Unterricht nicht.',
      complaint: 'Beschwerden weiterzugeben, sorgt für Unruhe und ändert nichts.'
    },
    messages: {
      'child.fit': 'Unser Zooausflug ist jetzt am nächsten Dienstag! Bringt ein Lunchpaket und etwas zu trinken mit, wie geplant. Wenn es stark regnet, gehen wir ins Aquarienhaus.',
      'child.tooMuch': 'Das Busunternehmen hat abgesagt, weil zwei Fahrer krank sind, eure Eltern müssen bis Freitag ein neues Formular unterschreiben, und der Preis bleibt bei 12 Euro.',
      'child.missing': 'Beim Ausflug ändert sich etwas. Ihr hört später mehr.',
      'parent.fit': 'Der Zooausflug wird von Donnerstag auf nächsten Dienstag verschoben, weil das Busunternehmen abgesagt hat. Bitte unterschreiben Sie bis Freitag die neue Einverständniserklärung. Der Preis bleibt bei 12 Euro; Ihr Kind braucht weiterhin ein Lunchpaket und etwas zu trinken.',
      'parent.tooMuch': 'Beim Busunternehmen sind zwei Fahrer krank, ich brauche am Dienstag von 10 bis 12 Uhr eine Vertretung für die 7b, und einige Eltern meinten, der Donnerstag sei ohnehin ungünstig gewesen.',
      'parent.condescending': 'Machen Sie sich um die Details keine Gedanken, wir Lehrkräfte haben alles im Griff. Unterschreiben Sie einfach, was Ihr Kind mitbringt.',
      'colleague.fit': 'Unser Zooausflug ist jetzt nächsten Dienstag. Könntest du an dem Tag meinen Unterricht in der 7b von 10 bis 12 Uhr vertreten?',
      'colleague.tooMuch': 'Die Kinder bringen ein Lunchpaket mit, der Preis bleibt bei 12 Euro, die Einverständniserklärung ist bis Freitag fällig, und bei Regen gehen wir ins Aquarienhaus.',
      'colleague.missing': 'Der Ausflug wird übrigens verschoben.'
    }
  },
  practiceMonday: {
    title: 'Arztpraxis: Termine am Montag',
    situation: 'Du arbeitest am Empfang einer Hausarztpraxis. Eine Ärztin fällt am Montag kurzfristig aus, deshalb müssen Termine verschoben werden. Erkläre es. (Es geht nur um Termine, nicht um Gesundheit.)',
    facts: {
      moved: 'Alle Montagstermine bei Dr. Lind werden zur selben Uhrzeit auf Mittwoch verschoben.',
      away: 'Dr. Lind fällt kurzfristig aus privaten Gründen aus.',
      urgent: 'Dringende Anliegen am Montag übernimmt die zweite Ärztin der Praxis.',
      calls: '42 Patienten müssen bis Freitag angerufen werden.',
      reply: 'Wer am Mittwoch nicht kann, ruft in der Praxis an und bekommt einen anderen Termin.',
      hours: 'Das Umbuchen braucht diese Woche etwa sechs zusätzliche Personalstunden, die die Praxisleitung genehmigen muss.',
      vip: 'Einer der Montagspatienten ist ein bekannter Lokalpolitiker.',
      texts: 'Das neue Terminsystem kann automatisch SMS-Erinnerungen verschicken.'
    },
    reasons: {
      'patient.moved': 'Der Patient braucht zuerst den neuen Tag und die Uhrzeit.',
      'patient.urgent': 'Er muss wissen, an wen er sich wenden kann, wenn etwas nicht warten kann.',
      'patient.calls': 'Wie viele Menschen betroffen sind, ist interne Arbeitslast.',
      'patient.reply': 'Es sagt ihm, was er tun kann, wenn der Mittwoch nicht passt.',
      'patient.hours': 'Personalstunden sind Sache der Praxis.',
      'patient.texts': 'Interne Werkzeuge muss der Patient nicht kennen.',
      'executive.moved': 'Die Praxisleitung muss wissen, was sich im Terminplan ändert.',
      'executive.calls': 'Das zeigt den Umfang der Arbeit.',
      'executive.reply': 'Hinweise für Patienten sind Routine am Empfang, keine Leitungsfrage.',
      'executive.hours': 'Das ist die Entscheidung, die die Praxisleitung treffen muss.',
      'colleague.moved': 'Die Kollegin muss den Patienten die neue Zeit nennen.',
      'colleague.urgent': 'Patienten werden fragen, also braucht die Kollegin die Antwort.',
      'colleague.calls': 'Das ist die Aufgabe, die du abgibst.',
      'colleague.hours': 'Zusatzstunden genehmigt die Leitung; die Kollegin braucht die Aufgabe.',
      'colleague.texts': 'Das erspart ihr viele Anrufe.',
      vip: 'Wer die Patienten sind, ist vertraulich und gehört in keine dieser Nachrichten.'
    },
    messages: {
      'patient.fit': 'Ihr Termin bei Dr. Lind am Montag wird zur selben Uhrzeit auf Mittwoch verschoben. Wenn Ihnen der Mittwoch nicht passt, rufen Sie uns bitte für einen anderen Termin an. Dringende Anliegen am Montag übernimmt unsere zweite Ärztin.',
      'patient.tooMuch': 'Wir müssen bis Freitag 42 Patienten anrufen, das braucht etwa sechs zusätzliche Personalstunden, und das neue System kann SMS-Erinnerungen verschicken.',
      'patient.condescending': 'Ärzte sind eben viel beschäftigt. Kommen Sie einfach am Mittwoch und machen Sie sich keine Gedanken, warum.',
      'executive.fit': 'Bitte genehmige diese Woche etwa sechs zusätzliche Personalstunden: Dr. Lind fällt am Montag aus, deshalb werden 42 Termine auf Mittwoch verschoben, und diese Patienten müssen bis Freitag angerufen werden.',
      'executive.tooMuch': 'Wer am Mittwoch nicht kann, soll uns anrufen, Dringendes übernimmt die zweite Ärztin, und SMS-Erinnerungen lassen sich im Einstellungsmenü einschalten.',
      'executive.missing': 'Der Montag ist etwas chaotisch, wir kriegen das hin.',
      'colleague.fit': 'Kannst du mir helfen, bis Freitag die 42 Patienten anzurufen, die am Montag bei Dr. Lind gebucht sind? Ihre Termine werden zur selben Uhrzeit auf Mittwoch verschoben; Dringendes am Montag übernimmt die zweite Ärztin. Das neue System kann auch SMS-Erinnerungen schicken.',
      'colleague.missing': 'Die Montagstermine ändern sich, nur damit du es weißt.',
      'colleague.condescending': 'Patienten anrufen ist einfach: Hörer abnehmen, Nummer wählen, reden. Mach das bitte für die Montagsliste.'
    }
  },
  libraryHours: {
    title: 'Öffnungszeiten der Bibliothek',
    situation: 'Du leitest die Stadtbibliothek. Wegen Kürzungen im Haushalt ändern sich die Öffnungszeiten. Erkläre es.',
    facts: {
      hours: 'Ab 1. September ist die Bibliothek dienstags bis samstags von 10 bis 18 Uhr geöffnet und montags geschlossen.',
      cards: 'Bibliotheksausweise und Online-Ausleihe sind nicht betroffen.',
      budget: 'Die Stadt hat das Budget der Bibliothek um 15 % gekürzt.',
      returns: 'Bücher können weiterhin jederzeit über den Rückgabekasten zurückgegeben werden.',
      shifts: 'Die Dienstpläne ändern sich: keine Montagsschichten mehr, längere Samstagsschichten.',
      savings: 'Die neuen Zeiten sparen etwa 40.000 Euro im Jahr, und niemand verliert seinen Arbeitsplatz.',
      petition: 'Eine Leserin hat eine Petition gegen die Schließung am Montag gestartet.',
      heating: 'Die Schließung am Montag spart auch Heizkosten, weil das alte Gebäude schlecht gedämmt ist.'
    },
    reasons: {
      'customer.hours': 'Leser müssen zuerst wissen, wann sie kommen können.',
      'customer.cards': 'Es beantwortet die Sorge, ob Ausweis und Online-Ausleihe noch funktionieren.',
      'customer.returns': 'Es sagt ihnen, was sie an einem Schließtag trotzdem tun können.',
      'customer.shifts': 'Dienstpläne sind intern.',
      'customer.savings': 'Haushaltszahlen helfen Lesern nicht, ihren Besuch zu planen.',
      'customer.petition': 'Die Petition zu erwähnen, ergreift Partei und hilft beim Planen nicht.',
      'customer.heating': 'Die Dämmung des Gebäudes ist ein internes Detail.',
      'colleague.hours': 'Kolleginnen beantworten die Fragen der Leser zu den neuen Zeiten.',
      'colleague.cards': 'Kollegen kennen ihre eigenen Systeme; dieser Satz ist für Leser.',
      'colleague.shifts': 'Das ändert ihre eigene Arbeitswoche.',
      'colleague.savings': 'Zu hören, dass niemand seinen Arbeitsplatz verliert, ist ihnen sehr wichtig.',
      'colleague.heating': 'Heizkosten ändern nichts an ihrer Arbeit.',
      'executive.hours': 'Der Stadtrat muss genau wissen, was die Öffentlichkeit sehen wird.',
      'executive.budget': 'Der Stadtrat hat die Kürzung selbst beschlossen; sie zu wiederholen, kostet nur Zeit.',
      'executive.returns': 'Details zum Rückgabekasten sind Tagesgeschäft.',
      'executive.savings': 'Einsparungen und Arbeitsplätze sind genau das, wonach der Stadtrat gefragt hat.',
      'executive.petition': 'Die Reaktion der Öffentlichkeit kann den Stadtrat erreichen, also sollte er zuerst von dir davon hören.'
    },
    messages: {
      'customer.fit': 'Ab 1. September ist die Bibliothek dienstags bis samstags von 10 bis 18 Uhr geöffnet und montags geschlossen. Bücher können Sie weiterhin jederzeit über den Rückgabekasten zurückgeben, und Ihr Ausweis und die Online-Ausleihe funktionieren wie bisher.',
      'customer.tooMuch': 'Die Stadt hat unser Budget um 15 % gekürzt, also sparen wir etwa 40.000 Euro im Jahr, indem wir die Dienstpläne ändern und das alte Gebäude montags weniger heizen.',
      'customer.condescending': 'Wir wissen, dass Veränderungen manchen Lesern schwerfallen. Merken Sie sich einfach: montags keine Bibliothek. Ist doch ganz einfach.',
      'colleague.fit': 'Ab 1. September ändern sich unsere Dienstpläne: keine Montagsschichten mehr, längere Samstagsschichten. Wir öffnen dienstags bis samstags von 10 bis 18 Uhr, und niemand verliert seinen Arbeitsplatz.',
      'colleague.missing': 'Im Herbst ändert sich einiges. Mehr später.',
      'colleague.tooMuch': 'Leser können weiter den Rückgabekasten nutzen, Ausweise und Online-Ausleihe sind nicht betroffen, und die Montagsschließung spart in unserem schlecht gedämmten Gebäude auch Heizkosten.',
      'executive.fit': 'Die neuen Öffnungszeiten sparen etwa 40.000 Euro im Jahr ohne Stellenabbau: Ab 1. September schließen wir montags und öffnen dienstags bis samstags von 10 bis 18 Uhr. Bitte beachten Sie, dass eine Leserin eine Petition gegen die Montagsschließung gestartet hat.',
      'executive.tooMuch': 'Rückgaben bleiben über den Rückgabekasten möglich, Ausweise und Online-Ausleihe sind nicht betroffen, und die Samstagsschichten werden länger, während die Montagsschichten wegfallen.',
      'executive.missing': 'Wir haben die Öffnungszeiten etwas angepasst.'
    }
  }
};
