import type { ContentText } from './types';

export const content: ContentText = {
  migration: {
    title: 'Database migration',
    situation: 'Your team is moving the customer database to a new system. Tests have found a problem, and the switch-over is delayed. Explain it.',
    facts: {
      newDate: 'The switch-over moves two days later: Thursday instead of Tuesday.',
      cause: 'Tests found a previously unknown bug with special characters such as ü or é.',
      noLoss: 'No data was lost.',
      encoding: 'The import script reads text in the wrong character encoding.',
      apology: 'We are sorry for the inconvenience.',
      regression: 'A new automated test now checks special characters.',
      buffer: 'The two days fit into the project’s time buffer, at no extra cost.',
      library: 'The faulty conversion comes from a library chosen years ago.'
    },
    reasons: {
      'developer.cause': 'Developers need to know what the tests actually found.',
      'developer.encoding': 'This is the root cause they will work on.',
      'developer.apology': 'An apology to customers does not help a colleague fix the bug.',
      'developer.regression': 'They need to know the bug is now covered by a test.',
      'developer.buffer': 'Time buffer and budget are the project lead’s concern.',
      'projectManager.newDate': 'The project lead plans with the new date.',
      'projectManager.noLoss': 'Data loss would change the risk completely, so they need to hear there is none.',
      'projectManager.encoding': 'The encoding detail does not change any planning decision.',
      'projectManager.apology': 'An apology is for customers; the project lead needs facts.',
      'projectManager.buffer': 'Whether schedule and budget still hold is exactly their question.',
      'projectManager.library': 'Who chose a library years ago does not help planning now.',
      'customer.newDate': 'The customer needs the new date, not the bug class.',
      'customer.noLoss': 'Their first worry is their data, and it is safe.',
      'customer.cause': 'Bug details worry customers without helping them.',
      'customer.encoding': 'Technical internals mean nothing to the customer.',
      'customer.regression': 'Internal testing is not the customer’s concern.',
      'customer.buffer': 'Internal buffers and costs are not the customer’s business.',
      'customer.library': 'Blaming an old library sounds like an excuse.'
    },
    messages: {
      'developer.fit': 'Heads-up: the import script reads text in the wrong encoding, so special characters like ü and é break. A regression test now covers it; the switch-over moves to Thursday.',
      'developer.missing': 'Small delay on the migration, nothing serious. Details later.',
      'developer.condescending': 'Special characters are letters like ü that are not in the basic alphabet. Computers store letters as numbers, and sometimes the numbers get mixed up.',
      'projectManager.fit': 'The migration moves from Tuesday to Thursday. No data was lost, and the two days fit into our buffer at no extra cost. Cause: a bug with special characters, now covered by a test.',
      'projectManager.tooMuch': 'The import script decodes the input as Latin-1 instead of UTF-8, so multi-byte characters get mangled; we are patching the reader and adding a regression test.',
      'projectManager.missing': 'We found a bug and are working on it. We will let you know.',
      'customer.fit': 'Your data is safe. To make sure every name and address comes across correctly, we are moving the switch-over from Tuesday to Thursday. Until then, everything works as usual.',
      'customer.tooMuch': 'Our import script used the wrong character encoding, which corrupted special characters in test runs, so the migration needs two extra days of our buffer.',
      'customer.condescending': 'Don’t worry about the technical side, it is complicated. Just know that it will be a bit later.'
    }
  },
  skyBlue: {
    title: 'Why the sky is blue',
    situation: 'Someone asks you why the sky is blue. You know the physics behind it. Explain it.',
    facts: {
      sunlight: 'Sunlight contains all colours.',
      scatter: 'Air scatters blue light much more than red light.',
      rayleigh: 'This Rayleigh scattering grows with the fourth power of the frequency (1/λ⁴).',
      sunset: 'At sunset, light travels through more air, so the sky turns red and orange.',
      everywhere: 'Scattered blue light reaches your eyes from every direction, so the whole sky looks blue.',
      violet: 'Violet is scattered even more, but sunlight contains less violet and our eyes are less sensitive to it.',
      molecules: 'The scattering comes from nitrogen and oxygen molecules, much smaller than the wavelength of light.',
      ocean: 'The sky is blue because it reflects the sea.'
    },
    reasons: {
      'child.sunlight': 'Children first need the surprise: white sunlight hides all the colours.',
      'child.scatter': 'This is the core idea, said in simple words.',
      'child.rayleigh': 'A formula loses a child immediately.',
      'child.everywhere': 'It explains what they see: blue wherever they look.',
      'child.violet': 'The violet detail confuses more than it helps at this age.',
      'child.molecules': 'Molecules and wavelengths are too abstract for a child.',
      'layperson.sunlight': 'Without it, “scattering blue light” makes no sense.',
      'layperson.scatter': 'This is the actual answer, in everyday words.',
      'layperson.rayleigh': 'The formula adds nothing a layperson can use.',
      'expert.rayleigh': 'An expert expects the precise mechanism and how it depends on wavelength.',
      'expert.everywhere': 'This is obvious to an expert and wastes their time.',
      'expert.violet': 'Experts know the obvious objection, “why not violet?” — answer it.',
      'expert.molecules': 'Naming the scatterers and the size ratio makes the explanation precise.',
      ocean: 'This is a common myth; the colour does not come from the sea.'
    },
    messages: {
      'child.fit': 'Sunlight looks white, but it is really all colours mixed together. When it flies through the air, the blue part gets bounced around the most, so blue comes to your eyes from all over the sky.',
      'child.tooMuch': 'Blue light has a shorter wavelength, and Rayleigh scattering grows with one over the wavelength to the fourth power.',
      'child.missing': 'That’s just how the sky is. It has always been blue.',
      'layperson.fit': 'Sunlight contains all colours. The air scatters blue light much more strongly than red, so blue light reaches us from every part of the sky.',
      'layperson.tooMuch': 'It is Rayleigh scattering: the intensity scales with 1/λ⁴, so short wavelengths dominate the diffuse radiance of the sky.',
      'layperson.condescending': 'It is a bit complicated for non-scientists. Let’s just say the air makes it blue.',
      'expert.fit': 'Rayleigh scattering by N₂ and O₂ molecules, proportional to 1/λ⁴. Violet scatters even more, but the solar spectrum has less violet and our cones are less sensitive to it.',
      'expert.condescending': 'Imagine sunlight as a box of crayons! The air likes to play with the blue crayon most.',
      'expert.missing': 'The air scatters blue light more, that’s why.'
    }
  },
  clubRoof: {
    title: 'Clubhouse roof',
    situation: 'The roof of your sports club’s clubhouse needs an urgent repair, and it costs more than planned. Explain it.',
    facts: {
      cost: 'The repair costs 8,000 euros, 3,000 more than budgeted.',
      decision: 'The board must decide by Friday whether to move 3,000 euros from the summer festival budget.',
      storage: 'The storage room stays closed until the repair; the rest of the clubhouse is open.',
      fees: 'Membership fees do not change.',
      schedule: 'The roofer starts on 12 May and needs four days; the car park is needed for scaffolding.',
      tiles: 'The new tiles are anthracite concrete tiles.',
      reserve: 'Using the reserve instead would push it below the required minimum.',
      volunteer: 'A member offered to repair the roof himself for free, but he is not a roofer.'
    },
    reasons: {
      'executive.cost': 'The board needs the amount and the overrun to judge it.',
      'executive.decision': 'This is the decision they must make, with its deadline.',
      'executive.storage': 'Day-to-day room use is not a board-level question.',
      'executive.schedule': 'The exact work days are the coordinator’s job.',
      'executive.tiles': 'Tile type and colour do not affect the decision.',
      'executive.reserve': 'It explains why the obvious alternative is not an option.',
      'projectManager.fees': 'Fees have nothing to do with organising the repair.',
      'projectManager.schedule': 'The coordinator organises exactly these dates and the car park.',
      'projectManager.reserve': 'Financing is the board’s decision, not the coordinator’s.',
      'layperson.storage': 'Members want to know what they can and cannot use.',
      'layperson.fees': 'Their own money is their first question.',
      'layperson.tiles': 'Material details do not matter to members.',
      'layperson.reserve': 'Reserve rules are internal finance details.',
      volunteer: 'An offer without the right qualification only starts a pointless debate; it is not a real option.'
    },
    messages: {
      'executive.fit': 'Decision needed by Friday: the roof repair costs 8,000 euros, 3,000 more than budgeted. We propose moving 3,000 from the summer festival budget, because the reserve would fall below its minimum.',
      'executive.tooMuch': 'The roofer starts on 12 May with anthracite concrete tiles; the scaffolding stands in the car park for four days, and the storage room stays closed until then.',
      'executive.missing': 'The roof is getting more expensive. We will keep you posted.',
      'projectManager.fit': 'The roofer starts on 12 May and needs four days. Please keep the car park free for the scaffolding from 11 May.',
      'projectManager.tooMuch': 'The repair costs 8,000 euros, 3,000 over budget; the board may move money from the festival, since the reserve must not fall below its minimum, and fees stay the same.',
      'projectManager.missing': 'There is some roof work coming up in May.',
      'layperson.fit': 'The clubhouse roof will be repaired in May. Until then, the storage room stays closed; everything else is open as usual. Membership fees do not change.',
      'layperson.tooMuch': 'The repair costs 8,000 euros, 3,000 over budget; the board is considering a transfer from the festival budget, because the reserve must not fall below its minimum.',
      'layperson.condescending': 'Don’t worry about the roof, the board will handle the grown-up stuff.'
    }
  },
  shopOutage: {
    title: 'Online shop outage',
    situation: 'Your company’s online shop was down for three hours yesterday. Explain what happened.',
    facts: {
      duration: 'The shop was down for three hours yesterday evening.',
      revenue: 'About 40,000 euros in orders were lost.',
      cause: 'An expired security certificate stopped payments.',
      fixed: 'The certificate has been renewed; the shop works normally again.',
      renewal: 'Renewal will be automated with a warning two weeks ahead; this takes the team one day.',
      voucher: 'Customers whose order failed receive a 10% voucher by email.',
      approval: 'Management is asked to approve 5,000 euros for better monitoring.',
      competitor: 'A competitor’s shop had a similar outage last month.'
    },
    reasons: {
      'projectManager.cause': 'The project lead needs the cause to judge the fix.',
      'projectManager.renewal': 'This is the work they must plan: one day of the team’s time.',
      'projectManager.voucher': 'Vouchers are handled by customer service, not by the project.',
      'executive.duration': 'Executives need the size of the incident.',
      'executive.revenue': 'Business impact comes first for executives.',
      'executive.cause': 'The technical detail does not change their decision; “a missed renewal” is enough.',
      'executive.renewal': 'They need to hear that it will not happen again.',
      'executive.approval': 'This is the decision they must make.',
      'customer.revenue': 'Your lost revenue is not the customer’s concern.',
      'customer.cause': 'Technical causes do not help customers.',
      'customer.fixed': 'Customers first want to know they can shop again.',
      'customer.renewal': 'Internal process changes are not the customer’s business.',
      'customer.voucher': 'This is what they get, and they should look for the email.',
      'customer.approval': 'Internal budget decisions are not for customers.',
      competitor: 'Pointing at others sounds like an excuse and changes nothing.'
    },
    messages: {
      'projectManager.fit': 'Yesterday’s three-hour outage came from an expired security certificate that stopped payments. To prevent a repeat, we automate renewal with an early warning; that takes the team one day this sprint.',
      'projectManager.tooMuch': 'We lost about 40,000 euros in orders, customers get a 10% voucher by email, and a competitor had the same problem last month.',
      'projectManager.missing': 'The shop had a short hiccup yesterday, all good now.',
      'executive.fit': 'Yesterday the shop was down for three hours; we lost about 40,000 euros in orders. A missed routine renewal caused it, and it is now automated. To catch such problems early, please approve 5,000 euros for monitoring.',
      'executive.tooMuch': 'The TLS certificate on the payment gateway expired at 18:02; we now renew it automatically via the ACME protocol, with alerts 14 days ahead.',
      'executive.missing': 'There was a small technical problem yesterday. It is fixed.',
      'customer.fit': 'We are sorry: yesterday evening our shop was unavailable for a few hours. Everything works again. If your order failed, you will receive a 10% voucher by email.',
      'customer.tooMuch': 'An expired security certificate stopped our payment system; we lost about 40,000 euros and now renew certificates automatically.',
      'customer.condescending': 'Some technical thing broke, nothing you would understand. Just try again.'
    }
  },
  signalFault: {
    title: 'Railway signal fault',
    situation: 'A signal fault is disrupting a railway line. You work for the railway. Explain the situation.',
    facts: {
      delay: 'Trains on this line are about 40 minutes late.',
      bus: 'Replacement buses leave from the station forecourt every 20 minutes.',
      tickets: 'Tickets are also valid on the buses and on later trains.',
      signal: 'Signal 14 at the junction shows a permanent red after a cable fault.',
      singleTrack: 'Trains pass the section on one track at walking speed, with written orders.',
      repair: 'Technicians expect the repair to take about four more hours.',
      construction: 'Construction work by another company probably damaged the cable.',
      staff: 'Two technicians are off sick this week.'
    },
    reasons: {
      'layperson.delay': 'Passengers first want to know how late they will be.',
      'layperson.bus': 'It tells them what they can do right now.',
      'layperson.tickets': 'It answers the worry whether they need a new ticket.',
      'layperson.signal': 'Signal numbers mean nothing to passengers.',
      'layperson.singleTrack': 'Operating rules do not help passengers.',
      'layperson.construction': 'Speculating about blame does not help passengers and may be wrong.',
      'layperson.staff': 'Internal staffing is not the passengers’ concern.',
      'expert.tickets': 'Ticket rules do not affect how trains are run.',
      'expert.signal': 'The colleague needs the exact location and fault.',
      'expert.singleTrack': 'This is the operating rule they must apply.',
      'expert.repair': 'They plan the timetable around the expected end.',
      'expert.staff': 'Staffing does not change how the section is operated.',
      'executive.delay': 'Management needs the scale of the disruption.',
      'executive.tickets': 'Ticket acceptance is a standard rule, not a management topic.',
      'executive.repair': 'They need to know how long the impact lasts.',
      'executive.construction': 'Possible damage by a third party matters for liability and costs.'
    },
    messages: {
      'layperson.fit': 'Trains on this line are about 40 minutes late. Replacement buses leave from the station forecourt every 20 minutes, and your ticket is valid on them.',
      'layperson.tooMuch': 'Signal 14 at the junction shows a permanent red after a cable fault; trains pass on one track at walking speed with written orders.',
      'layperson.missing': 'Please be patient, there is a technical disruption.',
      'expert.fit': 'Signal 14 at the junction is stuck at red after a cable fault. Single-track working at walking speed with written orders; repair expected to take about four more hours.',
      'expert.condescending': 'A signal is like a traffic light for trains. One of them is broken, so the trains have to go slowly.',
      'expert.missing': 'There is a problem on the line and trains are late. Buses are running.',
      'executive.fit': 'A cable fault will disrupt the line for about four more hours; trains run about 40 minutes late. Construction work by another company probably damaged the cable, so we are checking liability.',
      'executive.tooMuch': 'Signal 14 shows a permanent red; single-track working at walking speed with written orders; buses every 20 minutes from the forecourt; tickets valid on buses.',
      'executive.missing': 'Small signal problem, the team is on it.'
    }
  },
  kettleLid: {
    title: 'Kettle lid',
    situation: 'Your company has found that the lid of one kettle model can come loose. Explain it.',
    facts: {
      batches: 'Only kettles with batch numbers 2301 to 2315 are affected (printed under the base).',
      risk: 'The lid can open while pouring, so hot water may splash.',
      stop: 'Stop using an affected kettle until it is replaced.',
      hinge: 'A plastic hinge pin was made 0.2 mm too thin.',
      free: 'The replacement is free, including shipping.',
      cost: 'The exchange will cost the company about 120,000 euros.',
      supplier: 'The pins came from a new supplier whose samples had passed inspection.',
      injuries: 'There are no known injuries so far.'
    },
    reasons: {
      'customer.batches': 'Customers must be able to check whether their kettle is affected.',
      'customer.risk': 'They need to understand why it matters.',
      'customer.stop': 'This is the action that keeps them safe.',
      'customer.hinge': 'Millimetre details do not help customers.',
      'customer.free': 'Knowing it costs nothing removes a reason to wait.',
      'customer.cost': 'The company’s costs are not the customer’s concern.',
      'customer.supplier': 'Supplier details sound like shifting the blame.',
      'executive.risk': 'Executives must understand the safety risk first.',
      'executive.hinge': 'The exact dimension is for engineers.',
      'executive.cost': 'The financial impact is part of their decision.',
      'executive.injuries': 'Whether anyone was hurt changes the urgency and the response.',
      'expert.stop': 'Customer instructions do not help analyse the defect.',
      'expert.hinge': 'The engineer needs the exact defect.',
      'expert.free': 'Shipping terms do not matter for the technical analysis.',
      'expert.cost': 'Recall costs are not needed to fix the part.',
      'expert.supplier': 'It shows where the quality check must change.'
    },
    messages: {
      'customer.fit': 'Please check the batch number under your kettle. If it is between 2301 and 2315, stop using it: the lid can open while pouring. We will replace it free of charge, including shipping.',
      'customer.tooMuch': 'A hinge pin from a new supplier was 0.2 mm too thin; the exchange will cost us about 120,000 euros.',
      'customer.condescending': 'Some kettles might have a tiny problem. No need to understand the details; send it back if you like.',
      'executive.fit': 'Safety issue: on batches 2301 to 2315, the kettle lid can open while pouring hot water. No known injuries so far. The exchange will cost about 120,000 euros.',
      'executive.tooMuch': 'The hinge pin diameter is 0.2 mm below tolerance; the new supplier’s samples were within spec, so we suspect tool wear.',
      'executive.missing': 'We are replacing some kettles as a precaution.',
      'expert.fit': 'The hinge pins from the new supplier are 0.2 mm too thin, so the lid can open while pouring. Affected batches: 2301 to 2315. Their samples passed, so our incoming inspection must change.',
      'expert.missing': 'Some lids are loose; customers get a free replacement.',
      'expert.condescending': 'A hinge is the part that lets the lid turn. If it is too thin, it does not hold well.'
    }
  },
  renovation: {
    title: 'Delayed renovation',
    situation: 'You run the building firm renovating the kitchen and bathroom of a semi-detached house. The work is delayed. Explain it.',
    facts: {
      delay: 'The renovation will finish one week later: on 21 June instead of 14 June.',
      tiles: 'The supplier delivered 30 × 60 cm bathroom tiles instead of 60 × 60 cm, so they must be reordered.',
      order: 'Until the new tiles arrive, the crew works on the kitchen first.',
      water: 'The shared water pipe will be shut off on Tuesday from 8 to 12.',
      noise: 'Loud drilling continues for three more days next week, between 8 and 17.',
      cost: 'The delay costs the homeowner nothing; the supplier pays for the new tiles.',
      supplierHistory: 'This tile supplier has had delivery problems several times this year.',
      skip: 'On Monday the skip will stand on the street in front of the neighbour’s driveway.'
    },
    reasons: {
      'customer.delay': 'The homeowner plans around the new finishing date.',
      'customer.tiles': 'The exact tile format is the crew’s concern; the homeowner needs the date and the cost.',
      'customer.water': 'They must know when they will have no water.',
      'customer.cost': 'Their first worry is whether the delay costs them money.',
      'projectManager.delay': 'The crew lead plans the remaining work towards the new date.',
      'projectManager.tiles': 'The crew must know exactly what is wrong with the delivery.',
      'projectManager.order': 'This is what the crew does tomorrow morning.',
      'projectManager.water': 'The crew shuts off the water and has to warn everyone.',
      'projectManager.cost': 'Who pays is settled between the office and the supplier; it does not change the work.',
      'projectManager.skip': 'The crew lead must arrange where the skip goes.',
      'neighbour.tiles': 'Tile details are none of the neighbour’s business.',
      'neighbour.order': 'The crew’s work order does not affect the neighbour.',
      'neighbour.water': 'The neighbour shares the pipe and needs the exact times.',
      'neighbour.noise': 'Noise times are what affect the neighbour most.',
      'neighbour.cost': 'The homeowner’s costs are private.',
      'neighbour.skip': 'The skip blocks their driveway, so they must know in advance.',
      supplierHistory: 'Complaining about the supplier sounds like an excuse and helps no one.'
    },
    messages: {
      'customer.fit': 'Your renovation will be finished on 21 June instead of 14 June, because the bathroom tiles were delivered in the wrong size. This costs you nothing. Please note: on Tuesday the water is off from 8 to 12.',
      'customer.tooMuch': 'The supplier sent 30 × 60 tiles instead of 60 × 60, so the layout plan no longer fits; the crew now does the kitchen first, and the skip goes on the street on Monday.',
      'customer.condescending': 'There’s a small hiccup with the tiles, nothing you need to worry about. Leave it to the professionals.',
      'projectManager.fit': 'The bathroom tiles came as 30 × 60 instead of 60 × 60, so do the kitchen first until the reorder arrives. New finish: 21 June. Water off on Tuesday from 8 to 12, and the skip goes on the street on Monday.',
      'projectManager.missing': 'There’s a delay on the bathroom. Carry on as best you can.',
      'projectManager.condescending': 'Tiles have a size, and when the size is wrong they don’t fit. So please don’t lay them.',
      'neighbour.fit': 'About the renovation next door: on Tuesday the shared water pipe is off from 8 to 12, and there will be loud drilling for three more days next week, between 8 and 17. On Monday the skip stands in front of your driveway. Sorry for the trouble.',
      'neighbour.tooMuch': 'The bathroom tiles came in the wrong format, so the crew is switching to the kitchen, and the homeowner pays nothing extra because the supplier covers it.',
      'neighbour.missing': 'We are doing some building work next door. Thank you for your patience.'
    }
  },
  schoolTrip: {
    title: 'School trip change',
    situation: 'You are a class teacher. The bus company cancelled, so the class trip to the zoo has to move. Explain it.',
    facts: {
      newDate: 'The zoo trip moves from Thursday to next Tuesday.',
      bus: 'The bus company cancelled because two of its drivers are ill.',
      lunch: 'Children bring a packed lunch and a drink, as planned.',
      form: 'Parents must sign a new consent form by Friday.',
      price: 'The price stays at 12 euros per child.',
      cover: 'On Tuesday someone must cover my lessons with class 7b from 10 to 12.',
      rain: 'If it rains heavily, the class visits the aquarium house instead.',
      complaint: 'Some parents complained that Thursday was a bad day anyway.'
    },
    reasons: {
      'child.newDate': 'Children first want to know when the trip happens.',
      'child.bus': 'Ill bus drivers are not something the children need to think about.',
      'child.lunch': 'This is what they have to bring themselves.',
      'child.form': 'The form is for parents to sign, not for children.',
      'child.price': 'Money is handled by the parents.',
      'child.cover': 'Arrangements between teachers do not concern the children.',
      'child.rain': 'It tells them what to expect, which children like to know.',
      'parent.newDate': 'Parents need the new date to plan their week.',
      'parent.lunch': 'They prepare the packed lunch.',
      'parent.form': 'This is what they must do, with a deadline.',
      'parent.price': 'They want to know whether it costs more.',
      'parent.cover': 'Cover lessons are an internal school matter.',
      'parent.rain': 'It helps them prepare their child for the weather.',
      'colleague.newDate': 'The colleague must know which day is affected.',
      'colleague.lunch': 'Packed lunches are for the class, not for the colleague.',
      'colleague.price': 'The trip price does not affect the colleague.',
      'colleague.cover': 'This is what you are actually asking them for.',
      'colleague.rain': 'The bad-weather plan does not change the colleague’s lessons.',
      complaint: 'Passing on complaints stirs things up and changes nothing.'
    },
    messages: {
      'child.fit': 'Our zoo trip moves to next Tuesday! Bring a packed lunch and a drink, just like we planned. If it rains a lot, we will visit the aquarium house.',
      'child.tooMuch': 'The bus company cancelled because two drivers are ill, your parents must sign a new form by Friday, and the price stays at 12 euros.',
      'child.missing': 'There is a little change with the trip. You will hear more later.',
      'parent.fit': 'The zoo trip moves from Thursday to next Tuesday because the bus company cancelled. Please sign the new consent form by Friday. The price stays at 12 euros; your child still needs a packed lunch and a drink.',
      'parent.tooMuch': 'The bus company has two drivers off sick, I need cover for class 7b on Tuesday from 10 to 12, and some parents said Thursday was a bad day anyway.',
      'parent.condescending': 'Don’t worry about the details, we teachers have everything under control. Just sign whatever your child brings home.',
      'colleague.fit': 'Our zoo trip moves to next Tuesday. Could you cover my lessons with class 7b from 10 to 12 that day?',
      'colleague.tooMuch': 'The children bring a packed lunch, the price stays at 12 euros, the consent form is due on Friday, and if it rains we go to the aquarium house.',
      'colleague.missing': 'The trip is moving, by the way.'
    }
  },
  practiceMonday: {
    title: 'Doctor’s practice: Monday appointments',
    situation: 'You work at the front desk of a family doctor’s practice. One doctor is away on Monday at short notice, so appointments must move. Explain it. (This is only about appointments, not about health.)',
    facts: {
      moved: 'All of Dr Lind’s Monday appointments move to Wednesday at the same time.',
      away: 'Dr Lind is away at short notice for private reasons.',
      urgent: 'Urgent matters on Monday are seen by the second doctor in the practice.',
      calls: '42 patients must be phoned by Friday.',
      reply: 'Patients who cannot come on Wednesday call the practice to get another time.',
      hours: 'Rebooking needs about six extra staff hours this week, which the practice manager must approve.',
      vip: 'One of the Monday patients is a well-known local politician.',
      texts: 'The new appointment system can send text reminders automatically.'
    },
    reasons: {
      'patient.moved': 'The patient needs the new day and time first.',
      'patient.urgent': 'They need to know where to turn if something cannot wait.',
      'patient.calls': 'How many people are affected is internal workload.',
      'patient.reply': 'It tells them what to do if Wednesday does not work.',
      'patient.hours': 'Staff hours are the practice’s concern.',
      'patient.texts': 'Internal tools are not what the patient needs to hear.',
      'executive.moved': 'The practice manager must know what changes in the schedule.',
      'executive.calls': 'It shows the size of the workload.',
      'executive.reply': 'Patient instructions are front-desk routine, not a management question.',
      'executive.hours': 'This is the decision the practice manager must make.',
      'colleague.moved': 'The colleague must tell patients the new time.',
      'colleague.urgent': 'Patients will ask, so the colleague needs the answer.',
      'colleague.calls': 'This is the task you are handing over.',
      'colleague.hours': 'Approving extra hours is the manager’s decision; the colleague needs the task.',
      'colleague.texts': 'It saves them many phone calls.',
      vip: 'Who the patients are is confidential and does not belong in any of these messages.'
    },
    messages: {
      'patient.fit': 'Your appointment with Dr Lind on Monday moves to Wednesday at the same time. If Wednesday does not suit you, please call us for another time. Urgent matters on Monday are seen by our second doctor.',
      'patient.tooMuch': 'We have to phone 42 patients by Friday, which needs about six extra staff hours, and the new system can send text reminders.',
      'patient.condescending': 'Doctors are busy people, you know. Just come on Wednesday instead and don’t worry about why.',
      'executive.fit': 'Please approve about six extra staff hours this week: Dr Lind is away on Monday, so 42 appointments move to Wednesday and those patients must be phoned by Friday.',
      'executive.tooMuch': 'Patients who cannot make Wednesday should call us, urgent matters go to the second doctor, and text reminders can be switched on in the settings menu.',
      'executive.missing': 'Monday is a bit messy; we will sort it out.',
      'colleague.fit': 'Could you help phone the 42 patients booked with Dr Lind on Monday by Friday? Their appointments move to Wednesday at the same time; urgent matters on Monday go to the second doctor. The new system can also send text reminders.',
      'colleague.missing': 'Monday’s appointments are changing, just so you know.',
      'colleague.condescending': 'Phoning patients is easy: you pick up the phone, dial the number and talk. Please do it for Monday’s list.'
    }
  },
  libraryHours: {
    title: 'Library opening hours',
    situation: 'You manage the city library. Because of budget cuts, the opening hours change. Explain it.',
    facts: {
      hours: 'From 1 September the library opens Tuesday to Saturday from 10 to 18 and is closed on Mondays.',
      cards: 'Library cards and online loans are not affected.',
      budget: 'The city cut the library budget by 15%.',
      returns: 'Books can still be returned at any time through the drop box.',
      shifts: 'Staff shifts change: no more Monday shifts, longer Saturday shifts.',
      savings: 'The new hours save about 40,000 euros a year, and nobody loses their job.',
      petition: 'A reader has started a petition against the Monday closure.',
      heating: 'Closing on Mondays also saves heating, as the old building is poorly insulated.'
    },
    reasons: {
      'customer.hours': 'Readers first need to know when they can come.',
      'customer.cards': 'It answers the worry whether their card and online loans still work.',
      'customer.returns': 'It tells them what they can still do on a closed day.',
      'customer.shifts': 'Staff rosters are internal.',
      'customer.savings': 'Budget figures do not help readers plan their visit.',
      'customer.petition': 'Mentioning the petition takes sides and does not help readers plan.',
      'customer.heating': 'The building’s insulation is an internal detail.',
      'colleague.hours': 'Colleagues answer readers’ questions about the new times.',
      'colleague.cards': 'Colleagues know their own systems; this line is for readers.',
      'colleague.shifts': 'This changes their own working week.',
      'colleague.savings': 'Hearing that nobody loses their job matters a lot to them.',
      'colleague.heating': 'Heating costs do not change their work.',
      'executive.hours': 'The council must know exactly what the public will see.',
      'executive.budget': 'The council made the cut itself; repeating it wastes their time.',
      'executive.returns': 'Drop-box details are day-to-day operations.',
      'executive.savings': 'Savings and jobs are what the council asked about.',
      'executive.petition': 'Public reaction may reach the council, so they should hear it from you first.'
    },
    messages: {
      'customer.fit': 'From 1 September the library is open Tuesday to Saturday from 10 to 18 and closed on Mondays. You can still return books at any time through the drop box, and your library card and online loans work as before.',
      'customer.tooMuch': 'The city cut our budget by 15%, so we save about 40,000 euros a year by changing staff shifts and heating the old building less on Mondays.',
      'customer.condescending': 'We know change is hard for some readers. Just remember: no library on Mondays. It’s really quite simple.',
      'colleague.fit': 'From 1 September our shifts change: no more Monday shifts, longer Saturday shifts. We open Tuesday to Saturday from 10 to 18, and nobody loses their job.',
      'colleague.missing': 'Some things will change in the autumn. More later.',
      'colleague.tooMuch': 'Readers can still use the drop box, library cards and online loans are unaffected, and the Monday closure also saves heating in our poorly insulated building.',
      'executive.fit': 'The new opening hours save about 40,000 euros a year without job losses: from 1 September we close on Mondays and open Tuesday to Saturday from 10 to 18. Please note that a reader has started a petition against the Monday closure.',
      'executive.tooMuch': 'Returns stay possible through the drop box, library cards and online loans are unaffected, and Saturday shifts get longer while Monday shifts are dropped.',
      'executive.missing': 'We have adjusted the opening hours a little.'
    }
  }
};
