import type { ContentText } from './types';

export const content: ContentText = {
  migration: {
    title: 'Migración de base de datos',
    situation: 'Tu equipo está trasladando la base de datos de clientes a un sistema nuevo. Las pruebas han encontrado un problema y el cambio se retrasa. Explícalo.',
    facts: {
      newDate: 'El cambio se retrasa dos días: el jueves en lugar del martes.',
      cause: 'Las pruebas encontraron un error desconocido hasta ahora con caracteres especiales como ü o é.',
      noLoss: 'No se ha perdido ningún dato.',
      encoding: 'El script de importación lee el texto con una codificación de caracteres incorrecta.',
      apology: 'Sentimos las molestias.',
      regression: 'Una nueva prueba automática comprueba ahora los caracteres especiales.',
      buffer: 'Los dos días caben en el margen de tiempo del proyecto, sin coste adicional.',
      library: 'La conversión errónea viene de una biblioteca elegida hace años.'
    },
    reasons: {
      'developer.cause': 'Los desarrolladores necesitan saber qué encontraron realmente las pruebas.',
      'developer.encoding': 'Es la causa de fondo en la que van a trabajar.',
      'developer.apology': 'Una disculpa a los clientes no ayuda a una compañera a corregir el error.',
      'developer.regression': 'Necesitan saber que el error ya está cubierto por una prueba.',
      'developer.buffer': 'El margen de tiempo y el presupuesto son asunto de la jefa de proyecto.',
      'projectManager.newDate': 'La jefa de proyecto planifica con la nueva fecha.',
      'projectManager.noLoss': 'Una pérdida de datos cambiaría el riesgo por completo, así que necesita oír que no la hay.',
      'projectManager.encoding': 'El detalle de la codificación no cambia ninguna decisión de planificación.',
      'projectManager.apology': 'La disculpa es para los clientes; la jefa de proyecto necesita hechos.',
      'projectManager.buffer': 'Si el calendario y el presupuesto se mantienen es justo su pregunta.',
      'projectManager.library': 'Quién eligió una biblioteca hace años no ayuda ahora a planificar.',
      'customer.newDate': 'El cliente necesita la nueva fecha, no el tipo de error.',
      'customer.noLoss': 'Su primera preocupación son sus datos, y están a salvo.',
      'customer.cause': 'Los detalles del error preocupan al cliente sin ayudarle.',
      'customer.encoding': 'Los detalles técnicos internos no le dicen nada al cliente.',
      'customer.regression': 'Las pruebas internas no son asunto del cliente.',
      'customer.buffer': 'Los márgenes y costes internos no le incumben al cliente.',
      'customer.library': 'Culpar a una biblioteca antigua suena a excusa.'
    },
    messages: {
      'developer.fit': 'Aviso: el script de importación lee el texto con la codificación equivocada, así que caracteres especiales como ü y é se rompen. Ya hay una prueba de regresión que lo cubre; el cambio pasa al jueves.',
      'developer.missing': 'Pequeño retraso en la migración, nada grave. Detalles más adelante.',
      'developer.condescending': 'Los caracteres especiales son letras como la ü que no están en el alfabeto básico. Los ordenadores guardan las letras como números y a veces los números se mezclan.',
      'projectManager.fit': 'La migración pasa del martes al jueves. No se ha perdido ningún dato y los dos días caben en nuestro margen sin coste adicional. Causa: un error con caracteres especiales, ya cubierto por una prueba.',
      'projectManager.tooMuch': 'El script de importación decodifica la entrada como Latin-1 en vez de UTF-8, de modo que los caracteres multibyte se corrompen; estamos parcheando el lector y añadiendo una prueba de regresión.',
      'projectManager.missing': 'Hemos encontrado un error y estamos trabajando en ello. Ya te avisaremos.',
      'customer.fit': 'Sus datos están a salvo. Para asegurarnos de que cada nombre y cada dirección se transfieran correctamente, trasladamos el cambio del martes al jueves. Hasta entonces, todo funciona como siempre.',
      'customer.tooMuch': 'Nuestro script de importación usó una codificación de caracteres incorrecta que dañó los caracteres especiales en las pruebas, así que la migración necesita dos días más de nuestro margen.',
      'customer.condescending': 'No se preocupe por la parte técnica, es complicada. Solo sepa que tardará un poco más.'
    }
  },
  skyBlue: {
    title: 'Por qué el cielo es azul',
    situation: 'Alguien te pregunta por qué el cielo es azul. Conoces la física que hay detrás. Explícalo.',
    facts: {
      sunlight: 'La luz del sol contiene todos los colores.',
      scatter: 'El aire dispersa la luz azul mucho más que la roja.',
      rayleigh: 'Esta dispersión de Rayleigh crece con la cuarta potencia de la frecuencia (1/λ⁴).',
      sunset: 'Al atardecer, la luz atraviesa más aire, por eso el cielo se vuelve rojo y naranja.',
      everywhere: 'La luz azul dispersada llega a tus ojos desde todas las direcciones, por eso todo el cielo se ve azul.',
      violet: 'El violeta se dispersa aún más, pero la luz del sol tiene menos violeta y nuestros ojos son menos sensibles a él.',
      molecules: 'La dispersión la producen moléculas de nitrógeno y oxígeno, mucho más pequeñas que la longitud de onda de la luz.',
      ocean: 'El cielo es azul porque refleja el mar.'
    },
    reasons: {
      'child.sunlight': 'Los niños necesitan primero la sorpresa: la luz blanca del sol esconde todos los colores.',
      'child.scatter': 'Es la idea central, dicha con palabras sencillas.',
      'child.rayleigh': 'Con una fórmula se pierde a un niño al instante.',
      'child.everywhere': 'Explica lo que ven: azul mires donde mires.',
      'child.violet': 'El detalle del violeta confunde más de lo que ayuda a esa edad.',
      'child.molecules': 'Las moléculas y las longitudes de onda son demasiado abstractas para un niño.',
      'layperson.sunlight': 'Sin esto, «se dispersa la luz azul» no tiene sentido.',
      'layperson.scatter': 'Es la respuesta en sí, con palabras cotidianas.',
      'layperson.rayleigh': 'La fórmula no aporta nada que un profano pueda usar.',
      'expert.rayleigh': 'Un experto espera el mecanismo preciso y cómo depende de la longitud de onda.',
      'expert.everywhere': 'Es obvio para un experto y le hace perder el tiempo.',
      'expert.violet': 'Los expertos conocen la objeción evidente, «¿por qué no violeta?»: respóndela.',
      'expert.molecules': 'Nombrar a los dispersores y la relación de tamaños hace precisa la explicación.',
      ocean: 'Es un mito muy extendido; el color no viene del mar.'
    },
    messages: {
      'child.fit': 'La luz del sol parece blanca, pero en realidad lleva todos los colores mezclados. Cuando viaja por el aire, la parte azul es la que más rebota de un lado a otro, así que el azul te llega a los ojos desde todo el cielo.',
      'child.tooMuch': 'La luz azul tiene una longitud de onda más corta, y la dispersión de Rayleigh crece con uno entre la longitud de onda a la cuarta.',
      'child.missing': 'El cielo es así y ya está. Siempre ha sido azul.',
      'layperson.fit': 'La luz del sol contiene todos los colores. El aire dispersa la luz azul mucho más que la roja, así que nos llega luz azul desde todas partes del cielo.',
      'layperson.tooMuch': 'Es dispersión de Rayleigh: la intensidad escala con 1/λ⁴, de modo que las longitudes de onda cortas dominan la radiancia difusa del cielo.',
      'layperson.condescending': 'Es un poco complicado para quien no es científico. Digamos simplemente que el aire lo vuelve azul.',
      'expert.fit': 'Dispersión de Rayleigh por moléculas de N₂ y O₂, proporcional a 1/λ⁴. El violeta se dispersa aún más, pero el espectro solar tiene menos violeta y nuestros conos son menos sensibles a él.',
      'expert.condescending': '¡Imagina la luz del sol como una caja de lápices de colores! Al aire le gusta jugar sobre todo con el lápiz azul.',
      'expert.missing': 'El aire dispersa más la luz azul, por eso.'
    }
  },
  clubRoof: {
    title: 'El tejado del club',
    situation: 'El tejado de la sede de tu club deportivo necesita una reparación urgente y cuesta más de lo previsto. Explícalo.',
    facts: {
      cost: 'La reparación cuesta 8.000 euros, 3.000 más de lo presupuestado.',
      decision: 'La junta directiva debe decidir antes del viernes si traslada 3.000 euros del presupuesto de la fiesta de verano.',
      storage: 'El almacén de material permanece cerrado hasta la reparación; el resto de la sede está abierto.',
      fees: 'Las cuotas de socio no cambian.',
      schedule: 'El techador empieza el 12 de mayo y necesita cuatro días; el aparcamiento hace falta para el andamio.',
      tiles: 'Las tejas nuevas son de hormigón en color antracita.',
      reserve: 'Usar el fondo de reserva lo dejaría por debajo del mínimo obligatorio.',
      volunteer: 'Un socio se ofreció a reparar el tejado gratis él mismo, pero no es techador.'
    },
    reasons: {
      'executive.cost': 'La junta necesita la cantidad y el sobrecoste para valorarlo.',
      'executive.decision': 'Es la decisión que tiene que tomar, con su plazo.',
      'executive.storage': 'El uso diario de las salas no es un tema de la junta.',
      'executive.schedule': 'Los días exactos de obra son tarea del coordinador.',
      'executive.tiles': 'El tipo y el color de las tejas no influyen en la decisión.',
      'executive.reserve': 'Explica por qué la alternativa obvia no es una opción.',
      'projectManager.fees': 'Las cuotas no tienen nada que ver con organizar la reparación.',
      'projectManager.schedule': 'El coordinador organiza justo estas fechas y el aparcamiento.',
      'projectManager.reserve': 'La financiación la decide la junta, no el coordinador.',
      'layperson.storage': 'Los socios quieren saber qué pueden usar y qué no.',
      'layperson.fees': 'Su propio dinero es su primera pregunta.',
      'layperson.tiles': 'Los detalles del material no importan a los socios.',
      'layperson.reserve': 'Las reglas del fondo de reserva son detalles financieros internos.',
      volunteer: 'Una oferta sin la cualificación adecuada solo abre un debate inútil; no es una opción real.'
    },
    messages: {
      'executive.fit': 'Hace falta una decisión antes del viernes: la reparación del tejado cuesta 8.000 euros, 3.000 más de lo presupuestado. Proponemos trasladar 3.000 del presupuesto de la fiesta de verano, porque el fondo de reserva quedaría por debajo de su mínimo.',
      'executive.tooMuch': 'El techador empieza el 12 de mayo con tejas de hormigón antracita; el andamio estará cuatro días en el aparcamiento y el almacén seguirá cerrado hasta entonces.',
      'executive.missing': 'El tejado sale más caro. Os mantendremos informados.',
      'projectManager.fit': 'El techador empieza el 12 de mayo y necesita cuatro días. Por favor, deja libre el aparcamiento para el andamio a partir del 11 de mayo.',
      'projectManager.tooMuch': 'La reparación cuesta 8.000 euros, 3.000 por encima del presupuesto; quizá la junta traslade dinero de la fiesta, porque la reserva no puede bajar de su mínimo, y las cuotas no cambian.',
      'projectManager.missing': 'En mayo habrá alguna obra en el tejado.',
      'layperson.fit': 'El tejado de la sede se reparará en mayo. Hasta entonces, el almacén de material sigue cerrado; todo lo demás está abierto como siempre. Las cuotas de socio no cambian.',
      'layperson.tooMuch': 'La reparación cuesta 8.000 euros, 3.000 por encima del presupuesto; la junta estudia un traslado desde el presupuesto de la fiesta, porque la reserva no puede bajar de su mínimo.',
      'layperson.condescending': 'No os preocupéis por el tejado, la junta se encarga de las cosas de mayores.'
    }
  },
  shopOutage: {
    title: 'Caída de la tienda online',
    situation: 'La tienda online de tu empresa estuvo caída tres horas ayer. Explica lo que pasó.',
    facts: {
      duration: 'La tienda estuvo caída tres horas ayer por la tarde.',
      revenue: 'Se perdieron pedidos por unos 40.000 euros.',
      cause: 'Un certificado de seguridad caducado bloqueó los pagos.',
      fixed: 'El certificado se ha renovado; la tienda vuelve a funcionar con normalidad.',
      renewal: 'La renovación se automatizará con un aviso dos semanas antes; al equipo le lleva un día.',
      voucher: 'Los clientes cuyo pedido falló reciben por correo un vale del 10 %.',
      approval: 'Se pide a la dirección que apruebe 5.000 euros para una mejor monitorización.',
      competitor: 'La tienda de un competidor tuvo una caída parecida el mes pasado.'
    },
    reasons: {
      'projectManager.cause': 'La jefa de proyecto necesita la causa para valorar la solución.',
      'projectManager.renewal': 'Es el trabajo que tiene que planificar: un día del equipo.',
      'projectManager.voucher': 'Los vales los gestiona atención al cliente, no el proyecto.',
      'executive.duration': 'La dirección necesita la magnitud del incidente.',
      'executive.revenue': 'Para la dirección, el impacto en el negocio va primero.',
      'executive.cause': 'El detalle técnico no cambia su decisión; «una renovación olvidada» basta.',
      'executive.renewal': 'Necesita oír que no volverá a pasar.',
      'executive.approval': 'Es la decisión que tiene que tomar.',
      'customer.revenue': 'Tus ingresos perdidos no son asunto del cliente.',
      'customer.cause': 'Las causas técnicas no ayudan a los clientes.',
      'customer.fixed': 'Los clientes quieren saber primero que pueden volver a comprar.',
      'customer.renewal': 'Los cambios de procesos internos no le incumben al cliente.',
      'customer.voucher': 'Es lo que reciben, y deben estar atentos al correo.',
      'customer.approval': 'Las decisiones internas de presupuesto no son para los clientes.',
      competitor: 'Señalar a otros suena a excusa y no cambia nada.'
    },
    messages: {
      'projectManager.fit': 'La caída de tres horas de ayer se debió a un certificado de seguridad caducado que bloqueó los pagos. Para que no se repita, automatizamos la renovación con aviso previo; al equipo le lleva un día de este sprint.',
      'projectManager.tooMuch': 'Perdimos unos 40.000 euros en pedidos, los clientes reciben un vale del 10 % por correo y un competidor tuvo el mismo problema el mes pasado.',
      'projectManager.missing': 'La tienda tuvo un pequeño tropiezo ayer, ya está todo bien.',
      'executive.fit': 'Ayer la tienda estuvo caída tres horas; perdimos unos 40.000 euros en pedidos. La causa fue una renovación rutinaria olvidada, que ya está automatizada. Para detectar antes este tipo de problemas, les pedimos que aprueben 5.000 euros para monitorización.',
      'executive.tooMuch': 'El certificado TLS de la pasarela de pago caducó a las 18:02; ahora lo renovamos automáticamente con el protocolo ACME, con alertas 14 días antes.',
      'executive.missing': 'Ayer hubo un pequeño problema técnico. Ya está resuelto.',
      'customer.fit': 'Lo sentimos: ayer por la tarde nuestra tienda no estuvo disponible durante unas horas. Todo vuelve a funcionar. Si su pedido falló, recibirá por correo un vale del 10 %.',
      'customer.tooMuch': 'Un certificado de seguridad caducado detuvo nuestro sistema de pagos; perdimos unos 40.000 euros y ahora renovamos los certificados automáticamente.',
      'customer.condescending': 'Se rompió algo técnico, nada que usted fuera a entender. Simplemente vuelva a intentarlo.'
    }
  },
  signalFault: {
    title: 'Avería de señal en el tren',
    situation: 'Una avería de señal interrumpe una línea de tren. Trabajas para la compañía ferroviaria. Explica la situación.',
    facts: {
      delay: 'Los trenes de esta línea llevan unos 40 minutos de retraso.',
      bus: 'Hay autobuses de sustitución cada 20 minutos desde la explanada de la estación.',
      tickets: 'Los billetes también son válidos en los autobuses y en trenes posteriores.',
      signal: 'La señal 14 del cruce marca rojo fijo tras una avería en un cable.',
      singleTrack: 'Los trenes cruzan el tramo por una sola vía a paso de persona, con orden escrita.',
      repair: 'Los técnicos calculan que la reparación durará unas cuatro horas más.',
      construction: 'Probablemente unas obras de otra empresa dañaron el cable.',
      staff: 'Dos técnicos están de baja esta semana.'
    },
    reasons: {
      'layperson.delay': 'Los viajeros quieren saber primero cuánto retraso tendrán.',
      'layperson.bus': 'Les dice qué pueden hacer ahora mismo.',
      'layperson.tickets': 'Responde a la duda de si necesitan un billete nuevo.',
      'layperson.signal': 'Los números de señal no les dicen nada a los viajeros.',
      'layperson.singleTrack': 'Las normas de circulación no ayudan a los viajeros.',
      'layperson.construction': 'Especular sobre culpas no ayuda a los viajeros y puede ser falso.',
      'layperson.staff': 'La plantilla interna no es asunto de los viajeros.',
      'expert.tickets': 'Las normas de billetes no afectan a la circulación de trenes.',
      'expert.signal': 'El compañero necesita el lugar y la avería exactos.',
      'expert.singleTrack': 'Es la norma de circulación que debe aplicar.',
      'expert.repair': 'Planifica el horario en torno al final previsto.',
      'expert.staff': 'La plantilla no cambia cómo se circula por el tramo.',
      'executive.delay': 'La dirección necesita la magnitud de la interrupción.',
      'executive.tickets': 'Aceptar billetes es una norma estándar, no un tema de dirección.',
      'executive.repair': 'Necesita saber cuánto durará el impacto.',
      'executive.construction': 'Un posible daño causado por terceros importa para la responsabilidad y los costes.'
    },
    messages: {
      'layperson.fit': 'Los trenes de esta línea llevan unos 40 minutos de retraso. Hay autobuses de sustitución cada 20 minutos desde la explanada de la estación, y su billete es válido en ellos.',
      'layperson.tooMuch': 'La señal 14 del cruce marca rojo fijo tras una avería en un cable; los trenes pasan por una sola vía a paso de persona con orden escrita.',
      'layperson.missing': 'Les rogamos paciencia, hay una incidencia técnica.',
      'expert.fit': 'La señal 14 del cruce está bloqueada en rojo tras una avería de cable. Circulación por vía única a paso de persona con orden escrita; la reparación durará previsiblemente unas cuatro horas más.',
      'expert.condescending': 'Una señal es como un semáforo para trenes. Una está rota, así que los trenes tienen que ir despacio.',
      'expert.missing': 'Hay un problema en la línea y los trenes van con retraso. Hay autobuses.',
      'executive.fit': 'Una avería de cable afectará a la línea unas cuatro horas más; los trenes llevan unos 40 minutos de retraso. Probablemente unas obras de otra empresa dañaron el cable, así que estamos revisando la responsabilidad.',
      'executive.tooMuch': 'La señal 14 marca rojo fijo; circulación por vía única a paso de persona con orden escrita; autobuses cada 20 minutos desde la explanada; billetes válidos en los autobuses.',
      'executive.missing': 'Pequeño problema de señales, el equipo se está ocupando.'
    }
  },
  kettleLid: {
    title: 'La tapa del hervidor',
    situation: 'Tu empresa ha descubierto que la tapa de un modelo de hervidor puede soltarse. Explícalo.',
    facts: {
      batches: 'Solo están afectados los hervidores con números de lote del 2301 al 2315 (impresos bajo la base).',
      risk: 'La tapa puede abrirse al servir, así que puede salpicar agua caliente.',
      stop: 'Deje de usar un hervidor afectado hasta que se lo sustituyan.',
      hinge: 'Un pasador de plástico de la bisagra se fabricó 0,2 mm más fino de lo debido.',
      free: 'La sustitución es gratuita, envío incluido.',
      cost: 'El cambio costará a la empresa unos 120.000 euros.',
      supplier: 'Los pasadores venían de un proveedor nuevo cuyas muestras habían pasado la inspección.',
      injuries: 'Hasta ahora no se conocen heridos.'
    },
    reasons: {
      'customer.batches': 'Los clientes tienen que poder comprobar si su hervidor está afectado.',
      'customer.risk': 'Necesitan entender por qué importa.',
      'customer.stop': 'Es la acción que los mantiene a salvo.',
      'customer.hinge': 'Los detalles en milímetros no ayudan a los clientes.',
      'customer.free': 'Saber que no cuesta nada elimina un motivo para esperar.',
      'customer.cost': 'Los costes de la empresa no son asunto del cliente.',
      'customer.supplier': 'Los detalles del proveedor suenan a echar la culpa a otro.',
      'executive.risk': 'La dirección debe entender primero el riesgo para la seguridad.',
      'executive.hinge': 'La medida exacta es cosa de ingenieros.',
      'executive.cost': 'El impacto económico forma parte de su decisión.',
      'executive.injuries': 'Que haya o no heridos cambia la urgencia y la respuesta.',
      'expert.stop': 'Las instrucciones para clientes no ayudan a analizar el defecto.',
      'expert.hinge': 'La ingeniera necesita el defecto exacto.',
      'expert.free': 'Las condiciones de envío no importan para el análisis técnico.',
      'expert.cost': 'Los costes de la retirada no hacen falta para mejorar la pieza.',
      'expert.supplier': 'Muestra dónde debe cambiar el control de calidad.'
    },
    messages: {
      'customer.fit': 'Compruebe el número de lote bajo su hervidor. Si está entre 2301 y 2315, deje de usarlo: la tapa puede abrirse al servir. Se lo sustituiremos gratis, envío incluido.',
      'customer.tooMuch': 'Un pasador de bisagra de un proveedor nuevo era 0,2 mm demasiado fino; el cambio nos costará unos 120.000 euros.',
      'customer.condescending': 'Puede que algunos hervidores tengan un problemita. No hace falta que entienda los detalles; devuélvalo si quiere.',
      'executive.fit': 'Problema de seguridad: en los lotes 2301 a 2315, la tapa del hervidor puede abrirse al servir agua caliente. Hasta ahora no se conocen heridos. El cambio costará unos 120.000 euros.',
      'executive.tooMuch': 'El diámetro del pasador de la bisagra está 0,2 mm por debajo de la tolerancia; las muestras del proveedor nuevo cumplían la especificación, así que sospechamos desgaste de la herramienta.',
      'executive.missing': 'Vamos a sustituir algunos hervidores por precaución.',
      'expert.fit': 'Los pasadores de bisagra del proveedor nuevo son 0,2 mm demasiado finos, así que la tapa puede abrirse al servir. Lotes afectados: 2301 a 2315. Sus muestras pasaron, así que nuestra inspección de entrada tiene que cambiar.',
      'expert.missing': 'Algunas tapas están flojas; los clientes reciben una sustitución gratuita.',
      'expert.condescending': 'Una bisagra es la pieza que permite que la tapa gire. Si es demasiado fina, no sujeta bien.'
    }
  },
  renovation: {
    title: 'Reforma con retraso',
    situation: 'Diriges la empresa que reforma la cocina y el baño de una casa pareada. La obra se retrasa. Explícalo.',
    facts: {
      delay: 'La reforma terminará una semana más tarde: el 21 de junio en lugar del 14 de junio.',
      tiles: 'El proveedor entregó azulejos de baño de 30 × 60 cm en vez de 60 × 60 cm; hay que volver a pedirlos.',
      order: 'Hasta que lleguen los azulejos nuevos, la cuadrilla trabaja primero en la cocina.',
      water: 'La tubería de agua compartida se cortará el martes de 8 a 12.',
      noise: 'La próxima semana habrá tres días más de taladro ruidoso, entre las 8 y las 17.',
      cost: 'El retraso no le cuesta nada a la propietaria; el proveedor paga los azulejos nuevos.',
      supplierHistory: 'Este proveedor de azulejos ya ha tenido varios problemas de entrega este año.',
      skip: 'El lunes el contenedor estará en la calle, delante de la entrada de los vecinos.'
    },
    reasons: {
      'customer.delay': 'La propietaria organiza sus planes en torno a la nueva fecha de fin.',
      'customer.tiles': 'El formato exacto de los azulejos es asunto de la cuadrilla; la propietaria necesita la fecha y el coste.',
      'customer.water': 'Tiene que saber cuándo se quedará sin agua.',
      'customer.cost': 'Su primera preocupación es si el retraso le cuesta dinero.',
      'projectManager.delay': 'El jefe de cuadrilla planifica el resto de la obra hacia la nueva fecha.',
      'projectManager.tiles': 'La cuadrilla debe saber exactamente qué falla en la entrega.',
      'projectManager.order': 'Esto es lo que hace la cuadrilla mañana por la mañana.',
      'projectManager.water': 'La cuadrilla corta el agua y tiene que avisar a todos.',
      'projectManager.cost': 'Quién paga lo resuelven la oficina y el proveedor; no cambia el trabajo.',
      'projectManager.skip': 'El jefe de cuadrilla tiene que organizar dónde va el contenedor.',
      'neighbour.tiles': 'Los detalles de los azulejos no son asunto de los vecinos.',
      'neighbour.order': 'El orden de trabajo de la cuadrilla no afecta a los vecinos.',
      'neighbour.water': 'Los vecinos comparten la tubería y necesitan las horas exactas.',
      'neighbour.noise': 'Las horas de ruido son lo que más afecta a los vecinos.',
      'neighbour.cost': 'Los costes de la propietaria son privados.',
      'neighbour.skip': 'El contenedor bloquea su entrada, así que deben saberlo con antelación.',
      supplierHistory: 'Quejarse del proveedor suena a excusa y no ayuda a nadie.'
    },
    messages: {
      'customer.fit': 'Su reforma estará terminada el 21 de junio en lugar del 14, porque los azulejos del baño llegaron con un tamaño equivocado. A usted no le cuesta nada. Tenga en cuenta: el martes no habrá agua de 8 a 12.',
      'customer.tooMuch': 'El proveedor mandó 30 × 60 en vez de 60 × 60, así que el plano de colocación ya no encaja; la cuadrilla hace primero la cocina y el contenedor va a la calle el lunes.',
      'customer.condescending': 'Hay un pequeño contratiempo con los azulejos, nada de lo que tenga que preocuparse. Déjeselo a los profesionales.',
      'projectManager.fit': 'Los azulejos del baño llegaron en 30 × 60 en vez de 60 × 60, así que primero la cocina hasta que llegue el nuevo pedido. Nuevo final: 21 de junio. El martes se corta el agua de 8 a 12 y el lunes el contenedor va a la calle.',
      'projectManager.missing': 'Hay retraso en el baño. Seguid como podáis.',
      'projectManager.condescending': 'Los azulejos tienen un tamaño, y si el tamaño está mal, no encajan. Así que no los pongáis, por favor.',
      'neighbour.fit': 'Sobre la reforma de al lado: el martes se corta la tubería de agua compartida de 8 a 12, y la próxima semana habrá tres días más de taladro, entre las 8 y las 17. El lunes el contenedor estará delante de su entrada. Disculpe las molestias.',
      'neighbour.tooMuch': 'Los azulejos del baño llegaron en un formato equivocado, así que la cuadrilla pasa a la cocina, y la propietaria no paga nada extra porque lo cubre el proveedor.',
      'neighbour.missing': 'Estamos haciendo algunas obras al lado. Gracias por su paciencia.'
    }
  },
  schoolTrip: {
    title: 'Cambio en la excursión',
    situation: 'Eres tutor o tutora de una clase. La empresa de autobuses ha cancelado, así que la excursión al zoo tiene que cambiar de fecha. Explícalo.',
    facts: {
      newDate: 'La excursión al zoo pasa del jueves al martes de la semana que viene.',
      bus: 'La empresa de autobuses canceló porque dos conductores están enfermos.',
      lunch: 'Los niños llevan bocadillo y bebida, como estaba previsto.',
      form: 'Los padres deben firmar una nueva autorización antes del viernes.',
      price: 'El precio sigue siendo de 12 euros por niño.',
      cover: 'El martes alguien tiene que cubrir mis clases con 7.º B de 10 a 12.',
      rain: 'Si llueve mucho, la clase visitará la casa del acuario.',
      complaint: 'Algunos padres se quejaron de que el jueves era de todos modos un mal día.'
    },
    reasons: {
      'child.newDate': 'Los niños quieren saber primero cuándo es la excursión.',
      'child.bus': 'Los conductores enfermos no son algo en lo que los niños tengan que pensar.',
      'child.lunch': 'Esto es lo que tienen que llevar ellos mismos.',
      'child.form': 'La autorización la firman los padres, no los niños.',
      'child.price': 'Del dinero se encargan los padres.',
      'child.cover': 'Los acuerdos entre profesores no afectan a los niños.',
      'child.rain': 'Les dice qué esperar, y a los niños les gusta saberlo.',
      'parent.newDate': 'Los padres necesitan la nueva fecha para organizar su semana.',
      'parent.lunch': 'Ellos preparan el bocadillo.',
      'parent.form': 'Esto es lo que tienen que hacer, con un plazo.',
      'parent.price': 'Quieren saber si cuesta más.',
      'parent.cover': 'Las sustituciones son un asunto interno del colegio.',
      'parent.rain': 'Les ayuda a preparar a su hijo para el tiempo que haga.',
      'colleague.newDate': 'El compañero debe saber qué día se ve afectado.',
      'colleague.lunch': 'Los bocadillos son para la clase, no para el compañero.',
      'colleague.price': 'El precio de la excursión no afecta al compañero.',
      'colleague.cover': 'Esto es lo que realmente le estás pidiendo.',
      'colleague.rain': 'El plan para la lluvia no cambia sus clases.',
      complaint: 'Transmitir quejas crea revuelo y no cambia nada.'
    },
    messages: {
      'child.fit': '¡Nuestra excursión al zoo será el martes que viene! Traed bocadillo y bebida, como habíamos dicho. Si llueve mucho, iremos a la casa del acuario.',
      'child.tooMuch': 'La empresa de autobuses canceló porque dos conductores están enfermos, vuestros padres tienen que firmar una nueva autorización antes del viernes y el precio sigue en 12 euros.',
      'child.missing': 'Hay un pequeño cambio en la excursión. Ya os contaré.',
      'parent.fit': 'La excursión al zoo pasa del jueves al martes de la semana que viene porque la empresa de autobuses canceló. Por favor, firmen la nueva autorización antes del viernes. El precio sigue siendo de 12 euros; su hijo sigue necesitando bocadillo y bebida.',
      'parent.tooMuch': 'La empresa de autobuses tiene dos conductores de baja, necesito que alguien cubra 7.º B el martes de 10 a 12 y algunos padres dijeron que el jueves era mal día de todos modos.',
      'parent.condescending': 'No se preocupen por los detalles, los profesores lo tenemos todo controlado. Firmen lo que su hijo lleve a casa y ya está.',
      'colleague.fit': 'Nuestra excursión al zoo será el martes que viene. ¿Podrías cubrir ese día mis clases con 7.º B de 10 a 12?',
      'colleague.tooMuch': 'Los niños llevan bocadillo, el precio sigue en 12 euros, la autorización hay que entregarla el viernes y, si llueve, vamos a la casa del acuario.',
      'colleague.missing': 'Por cierto, la excursión cambia de fecha.'
    }
  },
  practiceMonday: {
    title: 'Consulta médica: citas del lunes',
    situation: 'Trabajas en la recepción de una consulta de medicina general. Una médica no estará el lunes por un imprevisto, así que hay que mover citas. Explícalo. (Se trata solo de citas, no de salud.)',
    facts: {
      moved: 'Todas las citas del lunes con la Dra. Lind pasan al miércoles a la misma hora.',
      away: 'La Dra. Lind falta por motivos personales imprevistos.',
      urgent: 'Los asuntos urgentes del lunes los atiende el segundo médico de la consulta.',
      calls: 'Hay que llamar a 42 pacientes antes del viernes.',
      reply: 'Quien no pueda venir el miércoles llama a la consulta para pedir otra hora.',
      hours: 'Reprogramar requiere unas seis horas extra de personal esta semana, que debe aprobar la gerente de la consulta.',
      vip: 'Uno de los pacientes del lunes es un político local conocido.',
      texts: 'El nuevo sistema de citas puede enviar recordatorios por SMS automáticamente.'
    },
    reasons: {
      'patient.moved': 'El paciente necesita primero el nuevo día y la hora.',
      'patient.urgent': 'Necesita saber a quién acudir si algo no puede esperar.',
      'patient.calls': 'Cuántas personas están afectadas es carga de trabajo interna.',
      'patient.reply': 'Le dice qué hacer si el miércoles no le va bien.',
      'patient.hours': 'Las horas del personal son cosa de la consulta.',
      'patient.texts': 'Las herramientas internas no son lo que el paciente necesita oír.',
      'executive.moved': 'La gerente debe saber qué cambia en la agenda.',
      'executive.calls': 'Muestra el volumen de trabajo.',
      'executive.reply': 'Las indicaciones a pacientes son rutina de recepción, no un tema de gerencia.',
      'executive.hours': 'Es la decisión que tiene que tomar la gerente.',
      'colleague.moved': 'La compañera tiene que decir a los pacientes la nueva hora.',
      'colleague.urgent': 'Los pacientes lo preguntarán, así que la compañera necesita la respuesta.',
      'colleague.calls': 'Esta es la tarea que le pasas.',
      'colleague.hours': 'Aprobar horas extra es cosa de la gerente; la compañera necesita la tarea.',
      'colleague.texts': 'Le ahorra muchas llamadas.',
      vip: 'Quiénes son los pacientes es confidencial y no tiene cabida en ninguno de estos mensajes.'
    },
    messages: {
      'patient.fit': 'Su cita del lunes con la Dra. Lind pasa al miércoles a la misma hora. Si el miércoles no le va bien, llámenos y le daremos otra hora. Los asuntos urgentes del lunes los atiende nuestro segundo médico.',
      'patient.tooMuch': 'Tenemos que llamar a 42 pacientes antes del viernes, lo que requiere unas seis horas extra de personal, y el nuevo sistema puede enviar recordatorios por SMS.',
      'patient.condescending': 'Los médicos están muy ocupados, ya sabe. Venga el miércoles y no se preocupe por el porqué.',
      'executive.fit': 'Por favor, aprueba unas seis horas extra de personal esta semana: la Dra. Lind falta el lunes, así que 42 citas pasan al miércoles y hay que llamar a esos pacientes antes del viernes.',
      'executive.tooMuch': 'Quien no pueda el miércoles debe llamarnos, lo urgente va al segundo médico y los recordatorios por SMS se activan en el menú de ajustes.',
      'executive.missing': 'El lunes está un poco liado, ya lo arreglaremos.',
      'colleague.fit': '¿Me ayudas a llamar antes del viernes a los 42 pacientes citados el lunes con la Dra. Lind? Sus citas pasan al miércoles a la misma hora; lo urgente del lunes va al segundo médico. El nuevo sistema también puede enviar recordatorios por SMS.',
      'colleague.missing': 'Las citas del lunes cambian, para que lo sepas.',
      'colleague.condescending': 'Llamar a pacientes es fácil: coges el teléfono, marcas el número y hablas. Hazlo con la lista del lunes, por favor.'
    }
  },
  libraryHours: {
    title: 'Horario de la biblioteca',
    situation: 'Diriges la biblioteca municipal. Por recortes de presupuesto cambia el horario de apertura. Explícalo.',
    facts: {
      hours: 'A partir del 1 de septiembre la biblioteca abre de martes a sábado de 10 a 18 y cierra los lunes.',
      cards: 'Los carnés de biblioteca y el préstamo en línea no cambian.',
      budget: 'El ayuntamiento recortó el presupuesto de la biblioteca un 15 %.',
      returns: 'Los libros se pueden seguir devolviendo en cualquier momento por el buzón de devolución.',
      shifts: 'Cambian los turnos del personal: ya no hay turnos los lunes y los de los sábados son más largos.',
      savings: 'El nuevo horario ahorra unos 40.000 euros al año y nadie pierde su empleo.',
      petition: 'Una lectora ha iniciado una recogida de firmas contra el cierre de los lunes.',
      heating: 'Cerrar los lunes también ahorra calefacción, porque el edificio es viejo y está mal aislado.'
    },
    reasons: {
      'customer.hours': 'Los lectores necesitan saber primero cuándo pueden venir.',
      'customer.cards': 'Responde a la duda de si su carné y el préstamo en línea siguen funcionando.',
      'customer.returns': 'Les dice qué pueden seguir haciendo un día de cierre.',
      'customer.shifts': 'Los turnos del personal son internos.',
      'customer.savings': 'Las cifras del presupuesto no ayudan a los lectores a planificar su visita.',
      'customer.petition': 'Mencionar la recogida de firmas toma partido y no ayuda a planificar.',
      'customer.heating': 'El aislamiento del edificio es un detalle interno.',
      'colleague.hours': 'Los compañeros responden a las preguntas de los lectores sobre el nuevo horario.',
      'colleague.cards': 'Los compañeros conocen sus propios sistemas; esta frase es para los lectores.',
      'colleague.shifts': 'Esto cambia su propia semana de trabajo.',
      'colleague.savings': 'Saber que nadie pierde su empleo les importa mucho.',
      'colleague.heating': 'Los gastos de calefacción no cambian su trabajo.',
      'executive.hours': 'El pleno municipal debe saber exactamente qué verá el público.',
      'executive.budget': 'El pleno decidió el recorte; repetirlo solo le hace perder tiempo.',
      'executive.returns': 'Los detalles del buzón son operación diaria.',
      'executive.savings': 'Ahorro y empleos es justo lo que el pleno preguntó.',
      'executive.petition': 'La reacción del público puede llegar al pleno, así que debe enterarse primero por ti.'
    },
    messages: {
      'customer.fit': 'A partir del 1 de septiembre la biblioteca abre de martes a sábado de 10 a 18 y cierra los lunes. Puede seguir devolviendo libros en cualquier momento por el buzón, y su carné y el préstamo en línea funcionan como siempre.',
      'customer.tooMuch': 'El ayuntamiento recortó nuestro presupuesto un 15 %, así que ahorramos unos 40.000 euros al año cambiando los turnos y calentando menos el viejo edificio los lunes.',
      'customer.condescending': 'Sabemos que a algunos lectores les cuestan los cambios. Recuerde solo esto: los lunes no hay biblioteca. Es muy sencillo.',
      'colleague.fit': 'A partir del 1 de septiembre cambian nuestros turnos: ya no hay turnos los lunes y los de los sábados son más largos. Abrimos de martes a sábado de 10 a 18 y nadie pierde su empleo.',
      'colleague.missing': 'En otoño cambiarán algunas cosas. Más adelante os cuento.',
      'colleague.tooMuch': 'Los lectores pueden seguir usando el buzón, los carnés y el préstamo en línea no cambian, y el cierre de los lunes también ahorra calefacción en nuestro edificio mal aislado.',
      'executive.fit': 'El nuevo horario ahorra unos 40.000 euros al año sin despidos: a partir del 1 de septiembre cerramos los lunes y abrimos de martes a sábado de 10 a 18. Tengan en cuenta que una lectora ha iniciado una recogida de firmas contra el cierre de los lunes.',
      'executive.tooMuch': 'Las devoluciones siguen siendo posibles por el buzón, los carnés y el préstamo en línea no cambian, y los turnos de los sábados se alargan mientras desaparecen los de los lunes.',
      'executive.missing': 'Hemos ajustado un poco el horario.'
    }
  }
};
