import type { ContentText } from './types';

export const content: ContentText = {
  migration: {
    title: 'Migration de base de données',
    situation: 'Ton équipe transfère la base de données clients vers un nouveau système. Les tests ont trouvé un problème et la bascule est retardée. Explique-le.',
    facts: {
      newDate: 'La bascule est décalée de deux jours : jeudi au lieu de mardi.',
      cause: 'Les tests ont trouvé un bug jusqu’ici inconnu avec des caractères spéciaux comme ü ou é.',
      noLoss: 'Aucune donnée n’a été perdue.',
      encoding: 'Le script d’import lit le texte avec le mauvais encodage de caractères.',
      apology: 'Nous sommes désolés pour la gêne occasionnée.',
      regression: 'Un nouveau test automatique vérifie désormais les caractères spéciaux.',
      buffer: 'Les deux jours tiennent dans la marge de temps du projet, sans surcoût.',
      library: 'La conversion fautive vient d’une bibliothèque choisie il y a des années.'
    },
    reasons: {
      'developer.cause': 'Les développeurs doivent savoir ce que les tests ont réellement trouvé.',
      'developer.encoding': 'C’est la cause profonde sur laquelle ils vont travailler.',
      'developer.apology': 'Des excuses aux clients n’aident pas une collègue à corriger le bug.',
      'developer.regression': 'Ils doivent savoir que le bug est désormais couvert par un test.',
      'developer.buffer': 'La marge de temps et le budget relèvent de la cheffe de projet.',
      'projectManager.newDate': 'La cheffe de projet planifie avec la nouvelle date.',
      'projectManager.noLoss': 'Une perte de données changerait complètement le risque ; elle doit donc entendre qu’il n’y en a pas.',
      'projectManager.encoding': 'Le détail de l’encodage ne change aucune décision de planification.',
      'projectManager.apology': 'Les excuses s’adressent aux clients ; la cheffe de projet a besoin de faits.',
      'projectManager.buffer': 'Savoir si le calendrier et le budget tiennent, c’est justement sa question.',
      'projectManager.library': 'Qui a choisi une bibliothèque il y a des années n’aide pas à planifier maintenant.',
      'customer.newDate': 'Le client a besoin de la nouvelle date, pas du type de bug.',
      'customer.noLoss': 'Son premier souci, ce sont ses données, et elles sont en sécurité.',
      'customer.cause': 'Les détails du bug inquiètent les clients sans les aider.',
      'customer.encoding': 'Les rouages techniques ne disent rien au client.',
      'customer.regression': 'Les tests internes ne concernent pas le client.',
      'customer.buffer': 'Les marges et coûts internes ne regardent pas le client.',
      'customer.library': 'Accuser une vieille bibliothèque sonne comme une excuse.'
    },
    messages: {
      'developer.fit': 'Pour info : le script d’import lit le texte avec le mauvais encodage, donc les caractères spéciaux comme ü et é sont cassés. Un test de non-régression le couvre maintenant ; la bascule passe à jeudi.',
      'developer.missing': 'Petit retard sur la migration, rien de grave. Détails plus tard.',
      'developer.condescending': 'Les caractères spéciaux sont des lettres comme ü qui ne font pas partie de l’alphabet de base. Les ordinateurs stockent les lettres sous forme de nombres, et parfois les nombres se mélangent.',
      'projectManager.fit': 'La migration passe de mardi à jeudi. Aucune donnée n’a été perdue, et les deux jours tiennent dans notre marge sans surcoût. Cause : un bug avec les caractères spéciaux, désormais couvert par un test.',
      'projectManager.tooMuch': 'Le script d’import décode l’entrée en Latin-1 au lieu d’UTF-8, ce qui abîme les caractères multi-octets ; nous corrigeons le lecteur et ajoutons un test de non-régression.',
      'projectManager.missing': 'Nous avons trouvé un bug et nous y travaillons. On te tient au courant.',
      'customer.fit': 'Vos données sont en sécurité. Pour que chaque nom et chaque adresse soient repris correctement, nous décalons la bascule de mardi à jeudi. D’ici là, tout fonctionne comme d’habitude.',
      'customer.tooMuch': 'Notre script d’import utilisait le mauvais encodage de caractères, ce qui a abîmé les caractères spéciaux lors des tests ; la migration a donc besoin de deux jours de plus pris sur notre marge.',
      'customer.condescending': 'Ne vous souciez pas de la partie technique, c’est compliqué. Sachez seulement que ce sera un peu plus tard.'
    }
  },
  skyBlue: {
    title: 'Pourquoi le ciel est bleu',
    situation: 'Quelqu’un te demande pourquoi le ciel est bleu. Tu connais la physique derrière. Explique-le.',
    facts: {
      sunlight: 'La lumière du soleil contient toutes les couleurs.',
      scatter: 'L’air diffuse beaucoup plus la lumière bleue que la rouge.',
      rayleigh: 'Cette diffusion de Rayleigh croît avec la puissance quatre de la fréquence (1/λ⁴).',
      sunset: 'Au coucher du soleil, la lumière traverse plus d’air, alors le ciel devient rouge et orange.',
      everywhere: 'La lumière bleue diffusée arrive à tes yeux de toutes les directions, donc tout le ciel paraît bleu.',
      violet: 'Le violet est encore plus diffusé, mais la lumière du soleil en contient moins et nos yeux y sont moins sensibles.',
      molecules: 'La diffusion est due aux molécules d’azote et d’oxygène, bien plus petites que la longueur d’onde de la lumière.',
      ocean: 'Le ciel est bleu parce qu’il reflète la mer.'
    },
    reasons: {
      'child.sunlight': 'L’enfant a d’abord besoin de la surprise : la lumière blanche cache toutes les couleurs.',
      'child.scatter': 'C’est l’idée centrale, dite avec des mots simples.',
      'child.rayleigh': 'Avec une formule, on perd un enfant tout de suite.',
      'child.everywhere': 'Cela explique ce qu’il voit : du bleu partout où il regarde.',
      'child.violet': 'Le détail du violet embrouille plus qu’il n’aide à cet âge.',
      'child.molecules': 'Molécules et longueurs d’onde sont trop abstraites pour un enfant.',
      'layperson.sunlight': 'Sans cela, « la lumière bleue est diffusée » n’a pas de sens.',
      'layperson.scatter': 'C’est la vraie réponse, avec des mots de tous les jours.',
      'layperson.rayleigh': 'La formule n’apporte rien d’utile à un non-spécialiste.',
      'expert.rayleigh': 'Un expert attend le mécanisme précis et sa dépendance à la longueur d’onde.',
      'expert.everywhere': 'C’est évident pour un expert et lui fait perdre du temps.',
      'expert.violet': 'Les experts connaissent l’objection évidente, « pourquoi pas violet ? » : réponds-y.',
      'expert.molecules': 'Nommer les diffuseurs et le rapport de tailles rend l’explication précise.',
      ocean: 'C’est une idée reçue répandue ; la couleur ne vient pas de la mer.'
    },
    messages: {
      'child.fit': 'La lumière du soleil a l’air blanche, mais en vrai toutes les couleurs y sont mélangées. Quand elle traverse l’air, c’est la partie bleue qui rebondit le plus dans tous les sens, alors le bleu arrive à tes yeux de partout dans le ciel.',
      'child.tooMuch': 'La lumière bleue a une longueur d’onde plus courte, et la diffusion de Rayleigh croît comme un sur la longueur d’onde à la puissance quatre.',
      'child.missing': 'Le ciel est comme ça, c’est tout. Il a toujours été bleu.',
      'layperson.fit': 'La lumière du soleil contient toutes les couleurs. L’air diffuse beaucoup plus la lumière bleue que la rouge, donc de la lumière bleue nous arrive de toutes les parties du ciel.',
      'layperson.tooMuch': 'C’est la diffusion de Rayleigh : l’intensité varie en 1/λ⁴, donc les courtes longueurs d’onde dominent la luminance diffuse du ciel.',
      'layperson.condescending': 'C’est un peu compliqué pour les non-scientifiques. Disons simplement que l’air le rend bleu.',
      'expert.fit': 'Diffusion de Rayleigh par les molécules de N₂ et d’O₂, proportionnelle à 1/λ⁴. Le violet est encore plus diffusé, mais le spectre solaire en contient moins et nos cônes y sont moins sensibles.',
      'expert.condescending': 'Imagine la lumière du soleil comme une boîte de crayons de couleur ! L’air adore jouer avec le crayon bleu.',
      'expert.missing': 'L’air diffuse davantage la lumière bleue, voilà pourquoi.'
    }
  },
  clubRoof: {
    title: 'Le toit du club',
    situation: 'Le toit du local de ton club sportif doit être réparé d’urgence, et cela coûte plus cher que prévu. Explique-le.',
    facts: {
      cost: 'La réparation coûte 8 000 euros, soit 3 000 de plus que prévu au budget.',
      decision: 'Le comité doit décider d’ici vendredi s’il transfère 3 000 euros du budget de la fête d’été.',
      storage: 'Le local de matériel reste fermé jusqu’à la réparation ; le reste du club est ouvert.',
      fees: 'Les cotisations ne changent pas.',
      schedule: 'Le couvreur commence le 12 mai et a besoin de quatre jours ; le parking sert à l’échafaudage.',
      tiles: 'Les nouvelles tuiles sont des tuiles en béton couleur anthracite.',
      reserve: 'Utiliser plutôt la réserve la ferait passer sous le minimum obligatoire.',
      volunteer: 'Un membre a proposé de réparer le toit lui-même gratuitement, mais il n’est pas couvreur.'
    },
    reasons: {
      'executive.cost': 'Le comité a besoin du montant et du dépassement pour juger.',
      'executive.decision': 'C’est la décision qu’il doit prendre, avec son échéance.',
      'executive.storage': 'L’usage quotidien des salles n’est pas une question pour le comité.',
      'executive.schedule': 'Les jours exacts des travaux sont l’affaire du coordinateur.',
      'executive.tiles': 'Le type et la couleur des tuiles ne changent pas la décision.',
      'executive.reserve': 'Cela explique pourquoi l’alternative évidente n’est pas possible.',
      'projectManager.fees': 'Les cotisations n’ont rien à voir avec l’organisation de la réparation.',
      'projectManager.schedule': 'Le coordinateur organise justement ces dates et le parking.',
      'projectManager.reserve': 'Le financement est la décision du comité, pas du coordinateur.',
      'layperson.storage': 'Les membres veulent savoir ce qu’ils peuvent utiliser ou non.',
      'layperson.fees': 'Leur propre argent est leur première question.',
      'layperson.tiles': 'Les détails de matériaux n’intéressent pas les membres.',
      'layperson.reserve': 'Les règles de la réserve sont des détails financiers internes.',
      volunteer: 'Une offre sans la qualification nécessaire ne fait que lancer un débat inutile ; ce n’est pas une vraie option.'
    },
    messages: {
      'executive.fit': 'Décision nécessaire d’ici vendredi : la réparation du toit coûte 8 000 euros, 3 000 de plus que prévu. Nous proposons de transférer 3 000 euros du budget de la fête d’été, car la réserve passerait sinon sous son minimum.',
      'executive.tooMuch': 'Le couvreur commence le 12 mai avec des tuiles en béton anthracite ; l’échafaudage reste quatre jours sur le parking et le local de matériel reste fermé d’ici là.',
      'executive.missing': 'Le toit coûte plus cher. Nous vous tenons au courant.',
      'projectManager.fit': 'Le couvreur commence le 12 mai et a besoin de quatre jours. Merci de libérer le parking pour l’échafaudage à partir du 11 mai.',
      'projectManager.tooMuch': 'La réparation coûte 8 000 euros, 3 000 au-dessus du budget ; le comité transférera peut-être de l’argent de la fête, car la réserve ne doit pas passer sous son minimum, et les cotisations restent les mêmes.',
      'projectManager.missing': 'Il y aura des travaux sur le toit à un moment en mai.',
      'layperson.fit': 'Le toit du club sera réparé en mai. D’ici là, le local de matériel reste fermé ; tout le reste est ouvert comme d’habitude. Les cotisations ne changent pas.',
      'layperson.tooMuch': 'La réparation coûte 8 000 euros, 3 000 au-dessus du budget ; le comité envisage un transfert depuis le budget de la fête, car la réserve ne doit pas passer sous son minimum.',
      'layperson.condescending': 'Ne vous inquiétez pas pour le toit, le comité s’occupe des affaires de grands.'
    }
  },
  shopOutage: {
    title: 'Panne de la boutique en ligne',
    situation: 'La boutique en ligne de ton entreprise a été en panne pendant trois heures hier. Explique ce qui s’est passé.',
    facts: {
      duration: 'La boutique a été en panne trois heures hier soir.',
      revenue: 'Environ 40 000 euros de commandes ont été perdus.',
      cause: 'Un certificat de sécurité expiré a bloqué les paiements.',
      fixed: 'Le certificat a été renouvelé ; la boutique fonctionne de nouveau normalement.',
      renewal: 'Le renouvellement sera automatisé, avec une alerte deux semaines avant ; cela prend une journée à l’équipe.',
      voucher: 'Les clients dont la commande a échoué reçoivent un bon de réduction de 10 % par e-mail.',
      approval: 'La direction est priée d’approuver 5 000 euros pour une meilleure surveillance.',
      competitor: 'La boutique d’un concurrent a eu une panne similaire le mois dernier.'
    },
    reasons: {
      'projectManager.cause': 'La cheffe de projet a besoin de la cause pour juger la correction.',
      'projectManager.renewal': 'C’est le travail qu’elle doit planifier : une journée de l’équipe.',
      'projectManager.voucher': 'Les bons sont gérés par le service client, pas par le projet.',
      'executive.duration': 'La direction a besoin de l’ampleur de l’incident.',
      'executive.revenue': 'Pour la direction, l’impact sur l’activité passe en premier.',
      'executive.cause': 'Le détail technique ne change pas sa décision ; « un renouvellement oublié » suffit.',
      'executive.renewal': 'Elle doit entendre que cela ne se reproduira pas.',
      'executive.approval': 'C’est la décision qu’elle doit prendre.',
      'customer.revenue': 'Ton chiffre d’affaires perdu ne concerne pas le client.',
      'customer.cause': 'Les causes techniques n’aident pas les clients.',
      'customer.fixed': 'Les clients veulent d’abord savoir qu’ils peuvent de nouveau commander.',
      'customer.renewal': 'Les changements de processus internes ne regardent pas les clients.',
      'customer.voucher': 'C’est ce qu’ils reçoivent, et ils doivent guetter l’e-mail.',
      'customer.approval': 'Les décisions budgétaires internes ne sont pas pour les clients.',
      competitor: 'Montrer les autres du doigt sonne comme une excuse et ne change rien.'
    },
    messages: {
      'projectManager.fit': 'La panne de trois heures d’hier venait d’un certificat de sécurité expiré qui a bloqué les paiements. Pour éviter que cela se reproduise, nous automatisons le renouvellement avec une alerte anticipée ; cela prend une journée à l’équipe dans ce sprint.',
      'projectManager.tooMuch': 'Nous avons perdu environ 40 000 euros de commandes, les clients reçoivent un bon de 10 % par e-mail, et un concurrent a eu le même problème le mois dernier.',
      'projectManager.missing': 'La boutique a eu un petit hoquet hier, tout va bien maintenant.',
      'executive.fit': 'Hier, la boutique a été en panne pendant trois heures ; nous avons perdu environ 40 000 euros de commandes. La cause est un renouvellement de routine oublié, désormais automatisé. Pour détecter ce genre de problème plus tôt, nous vous demandons d’approuver 5 000 euros pour la surveillance.',
      'executive.tooMuch': 'Le certificat TLS de la passerelle de paiement a expiré à 18 h 02 ; nous le renouvelons désormais automatiquement via le protocole ACME, avec des alertes 14 jours avant.',
      'executive.missing': 'Il y a eu un petit problème technique hier. Il est réglé.',
      'customer.fit': 'Toutes nos excuses : hier soir, notre boutique a été indisponible pendant quelques heures. Tout fonctionne de nouveau. Si votre commande a échoué, vous recevrez un bon de réduction de 10 % par e-mail.',
      'customer.tooMuch': 'Un certificat de sécurité expiré a bloqué notre système de paiement ; nous avons perdu environ 40 000 euros et renouvelons désormais les certificats automatiquement.',
      'customer.condescending': 'Un truc technique est tombé en panne, rien que vous puissiez comprendre. Réessayez, c’est tout.'
    }
  },
  signalFault: {
    title: 'Panne de signalisation',
    situation: 'Une panne de signalisation perturbe une ligne de train. Tu travailles pour la compagnie ferroviaire. Explique la situation.',
    facts: {
      delay: 'Les trains de cette ligne ont environ 40 minutes de retard.',
      bus: 'Des bus de remplacement partent du parvis de la gare toutes les 20 minutes.',
      tickets: 'Les billets sont aussi valables dans les bus et dans les trains suivants.',
      signal: 'Le signal 14 à la bifurcation reste au rouge après un défaut de câble.',
      singleTrack: 'Les trains franchissent la section sur une seule voie, au pas, avec un ordre écrit.',
      repair: 'Les techniciens estiment que la réparation durera encore environ quatre heures.',
      construction: 'Des travaux d’une autre entreprise ont probablement endommagé le câble.',
      staff: 'Deux techniciens sont en arrêt maladie cette semaine.'
    },
    reasons: {
      'layperson.delay': 'Les voyageurs veulent d’abord savoir combien de retard ils auront.',
      'layperson.bus': 'Cela leur dit ce qu’ils peuvent faire tout de suite.',
      'layperson.tickets': 'Cela répond à la crainte de devoir racheter un billet.',
      'layperson.signal': 'Les numéros de signaux ne disent rien aux voyageurs.',
      'layperson.singleTrack': 'Les règles d’exploitation n’aident pas les voyageurs.',
      'layperson.construction': 'Spéculer sur les responsabilités n’aide pas les voyageurs et peut être faux.',
      'layperson.staff': 'Les effectifs internes ne concernent pas les voyageurs.',
      'expert.tickets': 'Les règles de billetterie n’influencent pas la circulation des trains.',
      'expert.signal': 'Le collègue a besoin de l’endroit et du défaut exacts.',
      'expert.singleTrack': 'C’est la règle d’exploitation qu’il doit appliquer.',
      'expert.repair': 'Il organise l’horaire autour de la fin prévue.',
      'expert.staff': 'Les effectifs ne changent pas la manière d’exploiter la section.',
      'executive.delay': 'La direction a besoin de l’ampleur de la perturbation.',
      'executive.tickets': 'L’acceptation des billets est une règle standard, pas un sujet de direction.',
      'executive.repair': 'Elle doit savoir combien de temps durera l’impact.',
      'executive.construction': 'Un éventuel dommage causé par un tiers compte pour la responsabilité et les coûts.'
    },
    messages: {
      'layperson.fit': 'Les trains de cette ligne ont environ 40 minutes de retard. Des bus de remplacement partent du parvis de la gare toutes les 20 minutes, et votre billet y est valable.',
      'layperson.tooMuch': 'Le signal 14 à la bifurcation reste au rouge après un défaut de câble ; les trains circulent sur une seule voie, au pas, avec un ordre écrit.',
      'layperson.missing': 'Merci de votre patience, une perturbation technique est en cours.',
      'expert.fit': 'Signal 14 à la bifurcation bloqué au rouge après un défaut de câble. Circulation en voie unique au pas avec ordre écrit ; réparation prévue pour encore environ quatre heures.',
      'expert.condescending': 'Un signal, c’est comme un feu tricolore pour les trains. L’un d’eux est cassé, donc les trains doivent rouler lentement.',
      'expert.missing': 'Il y a un problème sur la ligne et les trains sont en retard. Des bus circulent.',
      'executive.fit': 'Un défaut de câble perturbera la ligne encore environ quatre heures ; les trains ont environ 40 minutes de retard. Des travaux d’une autre entreprise ont probablement endommagé le câble, nous examinons donc la question de la responsabilité.',
      'executive.tooMuch': 'Signal 14 au rouge fixe ; voie unique au pas avec ordre écrit ; bus toutes les 20 minutes depuis le parvis ; billets valables dans les bus.',
      'executive.missing': 'Petit souci de signal, l’équipe s’en occupe.'
    }
  },
  kettleLid: {
    title: 'Couvercle de bouilloire',
    situation: 'Ton entreprise a découvert que le couvercle d’un modèle de bouilloire peut se détacher. Explique-le.',
    facts: {
      batches: 'Seules les bouilloires portant les numéros de lot 2301 à 2315 sont concernées (imprimés sous le socle).',
      risk: 'Le couvercle peut s’ouvrir en versant, et de l’eau chaude peut gicler.',
      stop: 'N’utilisez plus une bouilloire concernée jusqu’à son remplacement.',
      hinge: 'Une goupille de charnière en plastique a été fabriquée 0,2 mm trop fine.',
      free: 'Le remplacement est gratuit, frais d’envoi compris.',
      cost: 'L’échange coûtera environ 120 000 euros à l’entreprise.',
      supplier: 'Les goupilles venaient d’un nouveau fournisseur dont les échantillons avaient passé le contrôle.',
      injuries: 'Aucune blessure n’est connue à ce jour.'
    },
    reasons: {
      'customer.batches': 'Les clients doivent pouvoir vérifier si leur bouilloire est concernée.',
      'customer.risk': 'Ils doivent comprendre pourquoi c’est important.',
      'customer.stop': 'C’est le geste qui les protège.',
      'customer.hinge': 'Les détails au millimètre n’aident pas les clients.',
      'customer.free': 'Savoir que c’est gratuit enlève une raison d’attendre.',
      'customer.cost': 'Les coûts de l’entreprise ne concernent pas le client.',
      'customer.supplier': 'Les détails sur le fournisseur donnent l’impression de rejeter la faute.',
      'executive.risk': 'La direction doit d’abord comprendre le risque pour la sécurité.',
      'executive.hinge': 'La cote exacte, c’est pour les ingénieurs.',
      'executive.cost': 'L’impact financier fait partie de sa décision.',
      'executive.injuries': 'Savoir si quelqu’un a été blessé change l’urgence et la réponse.',
      'expert.stop': 'Les consignes aux clients n’aident pas à analyser le défaut.',
      'expert.hinge': 'L’ingénieure a besoin du défaut exact.',
      'expert.free': 'Les conditions d’envoi ne comptent pas pour l’analyse technique.',
      'expert.cost': 'Les coûts du rappel ne servent pas à corriger la pièce.',
      'expert.supplier': 'Cela montre où le contrôle qualité doit changer.'
    },
    messages: {
      'customer.fit': 'Vérifiez le numéro de lot sous votre bouilloire. S’il est compris entre 2301 et 2315, ne l’utilisez plus : le couvercle peut s’ouvrir en versant. Nous la remplaçons gratuitement, frais d’envoi compris.',
      'customer.tooMuch': 'Une goupille de charnière d’un nouveau fournisseur était 0,2 mm trop fine ; l’échange va nous coûter environ 120 000 euros.',
      'customer.condescending': 'Certaines bouilloires ont peut-être un tout petit souci. Pas besoin de comprendre les détails ; renvoyez-la si vous voulez.',
      'executive.fit': 'Problème de sécurité : sur les lots 2301 à 2315, le couvercle de la bouilloire peut s’ouvrir en versant de l’eau chaude. Aucune blessure connue à ce jour. L’échange coûtera environ 120 000 euros.',
      'executive.tooMuch': 'Le diamètre de la goupille est 0,2 mm sous la tolérance ; les échantillons du nouveau fournisseur étaient conformes, nous soupçonnons donc une usure de l’outil.',
      'executive.missing': 'Nous remplaçons quelques bouilloires par précaution.',
      'expert.fit': 'Les goupilles de charnière du nouveau fournisseur sont 0,2 mm trop fines, donc le couvercle peut s’ouvrir en versant. Lots concernés : 2301 à 2315. Leurs échantillons avaient passé le contrôle, notre contrôle à réception doit donc changer.',
      'expert.missing': 'Certains couvercles ont du jeu ; les clients reçoivent un remplacement gratuit.',
      'expert.condescending': 'Une charnière, c’est la pièce qui permet au couvercle de tourner. Si elle est trop fine, elle tient mal.'
    }
  },
  renovation: {
    title: 'Rénovation en retard',
    situation: 'Tu diriges l’entreprise qui rénove la cuisine et la salle de bains d’une maison jumelée. Les travaux prennent du retard. Explique-le.',
    facts: {
      delay: 'La rénovation se terminera une semaine plus tard : le 21 juin au lieu du 14 juin.',
      tiles: 'Le fournisseur a livré des carreaux de 30 × 60 cm au lieu de 60 × 60 cm pour la salle de bains ; il faut les recommander.',
      order: 'En attendant les nouveaux carreaux, l’équipe travaille d’abord sur la cuisine.',
      water: 'La conduite d’eau commune sera coupée mardi de 8 h à 12 h.',
      noise: 'La semaine prochaine, il y aura encore trois jours de perçage bruyant, entre 8 h et 17 h.',
      cost: 'Le retard ne coûte rien aux propriétaires ; le fournisseur paie les nouveaux carreaux.',
      supplierHistory: 'Ce fournisseur de carreaux a déjà eu plusieurs problèmes de livraison cette année.',
      skip: 'Lundi, la benne sera dans la rue devant l’entrée des voisins.'
    },
    reasons: {
      'customer.delay': 'Les propriétaires s’organisent autour de la nouvelle date de fin.',
      'customer.tiles': 'Le format exact des carreaux regarde l’équipe ; les propriétaires ont besoin de la date et du coût.',
      'customer.water': 'Ils doivent savoir quand ils n’auront pas d’eau.',
      'customer.cost': 'Leur premier souci est de savoir si le retard leur coûte de l’argent.',
      'projectManager.delay': 'Le chef d’équipe planifie la suite des travaux vers la nouvelle date.',
      'projectManager.tiles': 'L’équipe doit savoir exactement ce qui ne va pas dans la livraison.',
      'projectManager.order': 'C’est ce que l’équipe fait demain matin.',
      'projectManager.water': 'L’équipe coupe l’eau et doit prévenir tout le monde.',
      'projectManager.cost': 'Qui paie se règle entre le bureau et le fournisseur ; cela ne change pas le travail.',
      'projectManager.skip': 'Le chef d’équipe doit organiser l’emplacement de la benne.',
      'neighbour.tiles': 'Les détails des carreaux ne regardent pas les voisins.',
      'neighbour.order': 'L’ordre des travaux de l’équipe ne concerne pas les voisins.',
      'neighbour.water': 'Les voisins partagent la conduite et ont besoin des horaires exacts.',
      'neighbour.noise': 'Les horaires de bruit sont ce qui touche le plus les voisins.',
      'neighbour.cost': 'Les coûts des propriétaires sont privés.',
      'neighbour.skip': 'La benne bloque leur entrée, ils doivent donc le savoir à l’avance.',
      supplierHistory: 'Se plaindre du fournisseur sonne comme une excuse et n’aide personne.'
    },
    messages: {
      'customer.fit': 'Votre rénovation sera terminée le 21 juin au lieu du 14 juin, car les carreaux de la salle de bains ont été livrés dans la mauvaise taille. Cela ne vous coûte rien. À noter : mardi, l’eau sera coupée de 8 h à 12 h.',
      'customer.tooMuch': 'Le fournisseur a envoyé du 30 × 60 au lieu du 60 × 60, donc le plan de pose ne convient plus ; l’équipe fait d’abord la cuisine, et la benne sera dans la rue lundi.',
      'customer.condescending': 'Il y a un petit souci avec les carreaux, rien dont vous deviez vous préoccuper. Laissez faire les professionnels.',
      'projectManager.fit': 'Les carreaux de la salle de bains sont arrivés en 30 × 60 au lieu de 60 × 60, donc la cuisine d’abord jusqu’à la nouvelle livraison. Nouvelle fin : 21 juin. Eau coupée mardi de 8 h à 12 h, et la benne va dans la rue lundi.',
      'projectManager.missing': 'Il y a du retard sur la salle de bains. Continuez comme vous pouvez.',
      'projectManager.condescending': 'Les carreaux ont une taille, et quand la taille est fausse, ils ne vont pas. Donc ne les posez pas, s’il vous plaît.',
      'neighbour.fit': 'Au sujet des travaux d’à côté : mardi, la conduite d’eau commune sera coupée de 8 h à 12 h, et la semaine prochaine il y aura encore trois jours de perçage, entre 8 h et 17 h. Lundi, la benne sera devant votre entrée. Désolés pour la gêne.',
      'neighbour.tooMuch': 'Les carreaux de la salle de bains sont arrivés au mauvais format, l’équipe passe donc à la cuisine, et les propriétaires ne paient rien de plus car le fournisseur prend tout en charge.',
      'neighbour.missing': 'Nous faisons quelques travaux à côté. Merci de votre patience.'
    }
  },
  schoolTrip: {
    title: 'Changement de sortie scolaire',
    situation: 'Tu es professeur principal. La compagnie de cars a annulé, la sortie au zoo doit donc être déplacée. Explique-le.',
    facts: {
      newDate: 'La sortie au zoo passe du jeudi au mardi de la semaine prochaine.',
      bus: 'La compagnie de cars a annulé parce que deux chauffeurs sont malades.',
      lunch: 'Les enfants apportent un pique-nique et une boisson, comme prévu.',
      form: 'Les parents doivent signer une nouvelle autorisation d’ici vendredi.',
      price: 'Le prix reste de 12 euros par enfant.',
      cover: 'Mardi, quelqu’un doit me remplacer auprès de la classe de 7b de 10 h à 12 h.',
      rain: 'En cas de forte pluie, la classe visitera plutôt le pavillon de l’aquarium.',
      complaint: 'Certains parents se sont plaints que le jeudi était de toute façon un mauvais jour.'
    },
    reasons: {
      'child.newDate': 'Les enfants veulent d’abord savoir quand a lieu la sortie.',
      'child.bus': 'Des chauffeurs malades, ce n’est pas un souci pour les enfants.',
      'child.lunch': 'C’est ce qu’ils doivent apporter eux-mêmes.',
      'child.form': 'L’autorisation est à signer par les parents, pas par les enfants.',
      'child.price': 'L’argent, ce sont les parents qui s’en occupent.',
      'child.cover': 'Les arrangements entre enseignants ne concernent pas les enfants.',
      'child.rain': 'Cela leur dit à quoi s’attendre, et les enfants aiment le savoir.',
      'parent.newDate': 'Les parents ont besoin de la nouvelle date pour organiser leur semaine.',
      'parent.lunch': 'Ce sont eux qui préparent le pique-nique.',
      'parent.form': 'C’est ce qu’ils doivent faire, avec une échéance.',
      'parent.price': 'Ils veulent savoir si cela coûte plus cher.',
      'parent.cover': 'Les remplacements sont une affaire interne à l’école.',
      'parent.rain': 'Cela les aide à préparer leur enfant à la météo.',
      'colleague.newDate': 'Le collègue doit savoir quel jour est concerné.',
      'colleague.lunch': 'Les pique-niques concernent la classe, pas le collègue.',
      'colleague.price': 'Le prix de la sortie ne concerne pas le collègue.',
      'colleague.cover': 'C’est en fait ce que tu lui demandes.',
      'colleague.rain': 'Le plan en cas de pluie ne change pas ses cours.',
      complaint: 'Relayer des plaintes agite les esprits et ne change rien.'
    },
    messages: {
      'child.fit': 'Notre sortie au zoo, c’est mardi prochain ! Apportez un pique-nique et une boisson, comme prévu. S’il pleut beaucoup, nous irons au pavillon de l’aquarium.',
      'child.tooMuch': 'La compagnie de cars a annulé parce que deux chauffeurs sont malades, vos parents doivent signer une nouvelle autorisation d’ici vendredi, et le prix reste de 12 euros.',
      'child.missing': 'Il y a un petit changement pour la sortie. Vous en saurez plus plus tard.',
      'parent.fit': 'La sortie au zoo passe du jeudi au mardi de la semaine prochaine, car la compagnie de cars a annulé. Merci de signer la nouvelle autorisation d’ici vendredi. Le prix reste de 12 euros ; votre enfant a toujours besoin d’un pique-nique et d’une boisson.',
      'parent.tooMuch': 'La compagnie de cars a deux chauffeurs malades, j’ai besoin d’un remplacement pour la 7b mardi de 10 h à 12 h, et certains parents ont dit que le jeudi était de toute façon un mauvais jour.',
      'parent.condescending': 'Ne vous souciez pas des détails, nous, les enseignants, maîtrisons tout. Signez simplement ce que votre enfant rapporte.',
      'colleague.fit': 'Notre sortie au zoo est maintenant mardi prochain. Pourrais-tu me remplacer ce jour-là auprès de la 7b de 10 h à 12 h ?',
      'colleague.tooMuch': 'Les enfants apportent un pique-nique, le prix reste de 12 euros, l’autorisation est à rendre vendredi, et s’il pleut, nous allons au pavillon de l’aquarium.',
      'colleague.missing': 'Au fait, la sortie est déplacée.'
    }
  },
  practiceMonday: {
    title: 'Cabinet médical : rendez-vous du lundi',
    situation: 'Tu travailles à l’accueil d’un cabinet de médecine générale. Une médecin est absente lundi de façon imprévue, il faut donc déplacer des rendez-vous. Explique-le. (Il s’agit seulement de rendez-vous, pas de santé.)',
    facts: {
      moved: 'Tous les rendez-vous du lundi avec la Dre Lind passent au mercredi, à la même heure.',
      away: 'La Dre Lind est absente de façon imprévue pour des raisons personnelles.',
      urgent: 'Les demandes urgentes du lundi sont prises en charge par le second médecin du cabinet.',
      calls: 'Il faut appeler 42 patients d’ici vendredi.',
      reply: 'Les patients qui ne peuvent pas venir mercredi appellent le cabinet pour un autre horaire.',
      hours: 'Reprogrammer demande environ six heures de personnel en plus cette semaine, que la gérante du cabinet doit approuver.',
      vip: 'L’un des patients du lundi est un élu local connu.',
      texts: 'Le nouveau logiciel de rendez-vous peut envoyer des rappels par SMS automatiquement.'
    },
    reasons: {
      'patient.moved': 'Le patient a d’abord besoin du nouveau jour et de l’heure.',
      'patient.urgent': 'Il doit savoir à qui s’adresser si quelque chose ne peut pas attendre.',
      'patient.calls': 'Le nombre de personnes concernées relève de la charge de travail interne.',
      'patient.reply': 'Cela lui dit quoi faire si le mercredi ne convient pas.',
      'patient.hours': 'Les heures du personnel regardent le cabinet.',
      'patient.texts': 'Les outils internes ne sont pas ce que le patient a besoin d’entendre.',
      'executive.moved': 'La gérante doit savoir ce qui change dans le planning.',
      'executive.calls': 'Cela montre l’ampleur du travail.',
      'executive.reply': 'Les consignes aux patients relèvent de l’accueil, pas de la gestion.',
      'executive.hours': 'C’est la décision que la gérante doit prendre.',
      'colleague.moved': 'La collègue doit donner le nouvel horaire aux patients.',
      'colleague.urgent': 'Les patients vont demander, la collègue a donc besoin de la réponse.',
      'colleague.calls': 'C’est la tâche que tu lui confies.',
      'colleague.hours': 'Approuver des heures en plus revient à la gérante ; la collègue a besoin de la tâche.',
      'colleague.texts': 'Cela lui épargne beaucoup d’appels.',
      vip: 'L’identité des patients est confidentielle et n’a sa place dans aucun de ces messages.'
    },
    messages: {
      'patient.fit': 'Votre rendez-vous de lundi avec la Dre Lind passe au mercredi, à la même heure. Si mercredi ne vous convient pas, appelez-nous pour un autre horaire. Les demandes urgentes du lundi sont prises en charge par notre second médecin.',
      'patient.tooMuch': 'Nous devons appeler 42 patients d’ici vendredi, ce qui demande environ six heures de personnel en plus, et le nouveau logiciel peut envoyer des rappels par SMS.',
      'patient.condescending': 'Les médecins sont très occupés, vous savez. Venez simplement mercredi et ne vous demandez pas pourquoi.',
      'executive.fit': 'Merci d’approuver environ six heures de personnel en plus cette semaine : la Dre Lind est absente lundi, donc 42 rendez-vous passent au mercredi et ces patients doivent être appelés d’ici vendredi.',
      'executive.tooMuch': 'Les patients qui ne peuvent pas venir mercredi doivent nous appeler, les urgences vont au second médecin, et les rappels SMS s’activent dans le menu des réglages.',
      'executive.missing': 'Lundi est un peu compliqué, on va s’arranger.',
      'colleague.fit': 'Peux-tu m’aider à appeler d’ici vendredi les 42 patients prévus lundi avec la Dre Lind ? Leurs rendez-vous passent au mercredi, à la même heure ; les urgences du lundi vont au second médecin. Le nouveau logiciel peut aussi envoyer des rappels par SMS.',
      'colleague.missing': 'Les rendez-vous du lundi changent, pour info.',
      'colleague.condescending': 'Appeler des patients, c’est facile : on décroche, on compose le numéro et on parle. Fais-le pour la liste du lundi, s’il te plaît.'
    }
  },
  libraryHours: {
    title: 'Horaires de la bibliothèque',
    situation: 'Tu diriges la bibliothèque municipale. À cause de coupes budgétaires, les horaires d’ouverture changent. Explique-le.',
    facts: {
      hours: 'À partir du 1er septembre, la bibliothèque ouvre du mardi au samedi de 10 h à 18 h et ferme le lundi.',
      cards: 'Les cartes de bibliothèque et le prêt numérique ne changent pas.',
      budget: 'La ville a réduit le budget de la bibliothèque de 15 %.',
      returns: 'Les livres peuvent toujours être rendus à tout moment dans la boîte de retour.',
      shifts: 'Les plannings changent : plus de service le lundi, des services plus longs le samedi.',
      savings: 'Les nouveaux horaires économisent environ 40 000 euros par an, et personne ne perd son emploi.',
      petition: 'Une lectrice a lancé une pétition contre la fermeture du lundi.',
      heating: 'Fermer le lundi économise aussi du chauffage, car le vieux bâtiment est mal isolé.'
    },
    reasons: {
      'customer.hours': 'Les lecteurs doivent d’abord savoir quand ils peuvent venir.',
      'customer.cards': 'Cela répond à la crainte que leur carte et le prêt numérique ne marchent plus.',
      'customer.returns': 'Cela leur dit ce qu’ils peuvent encore faire un jour de fermeture.',
      'customer.shifts': 'Les plannings du personnel sont internes.',
      'customer.savings': 'Les chiffres budgétaires n’aident pas les lecteurs à planifier leur visite.',
      'customer.petition': 'Mentionner la pétition, c’est prendre parti, et cela n’aide pas à planifier.',
      'customer.heating': 'L’isolation du bâtiment est un détail interne.',
      'colleague.hours': 'Les collègues répondent aux questions des lecteurs sur les nouveaux horaires.',
      'colleague.cards': 'Les collègues connaissent leurs propres systèmes ; cette phrase est pour les lecteurs.',
      'colleague.shifts': 'Cela change leur propre semaine de travail.',
      'colleague.savings': 'Savoir que personne ne perd son emploi compte beaucoup pour eux.',
      'colleague.heating': 'Les frais de chauffage ne changent rien à leur travail.',
      'executive.hours': 'Le conseil municipal doit savoir exactement ce que verra le public.',
      'executive.budget': 'Le conseil a lui-même voté la coupe ; la répéter lui fait perdre du temps.',
      'executive.returns': 'Les détails de la boîte de retour relèvent du fonctionnement quotidien.',
      'executive.savings': 'Les économies et les emplois, c’est exactement ce qu’a demandé le conseil.',
      'executive.petition': 'La réaction du public peut remonter au conseil, il doit donc l’apprendre d’abord par toi.'
    },
    messages: {
      'customer.fit': 'À partir du 1er septembre, la bibliothèque est ouverte du mardi au samedi de 10 h à 18 h et fermée le lundi. Vous pouvez toujours rendre vos livres à tout moment dans la boîte de retour, et votre carte et le prêt numérique fonctionnent comme avant.',
      'customer.tooMuch': 'La ville a réduit notre budget de 15 %, nous économisons donc environ 40 000 euros par an en changeant les plannings et en chauffant moins le vieux bâtiment le lundi.',
      'customer.condescending': 'Nous savons que le changement est difficile pour certains lecteurs. Retenez simplement : pas de bibliothèque le lundi. C’est tout simple.',
      'colleague.fit': 'À partir du 1er septembre, nos plannings changent : plus de service le lundi, des services plus longs le samedi. Nous ouvrons du mardi au samedi de 10 h à 18 h, et personne ne perd son emploi.',
      'colleague.missing': 'Certaines choses vont changer à l’automne. Plus d’infos plus tard.',
      'colleague.tooMuch': 'Les lecteurs peuvent toujours utiliser la boîte de retour, les cartes et le prêt numérique ne changent pas, et la fermeture du lundi économise aussi du chauffage dans notre bâtiment mal isolé.',
      'executive.fit': 'Les nouveaux horaires économisent environ 40 000 euros par an sans suppression de postes : à partir du 1er septembre, nous fermons le lundi et ouvrons du mardi au samedi de 10 h à 18 h. À noter : une lectrice a lancé une pétition contre la fermeture du lundi.',
      'executive.tooMuch': 'Les retours restent possibles par la boîte de retour, les cartes et le prêt numérique ne changent pas, et les services du samedi s’allongent tandis que ceux du lundi disparaissent.',
      'executive.missing': 'Nous avons un peu ajusté les horaires.'
    }
  }
};
