import type { ContentText } from './types';

export const content: ContentText = {
  migration: {
    title: 'Databasemigratie',
    situation: 'Je team verhuist de klantendatabase naar een nieuw systeem. De tests hebben een probleem gevonden en de overstap loopt vertraging op. Leg het uit.',
    facts: {
      newDate: 'De overstap schuift twee dagen op: donderdag in plaats van dinsdag.',
      cause: 'De tests vonden een tot nu toe onbekende fout met speciale tekens zoals ü of é.',
      noLoss: 'Er zijn geen gegevens verloren gegaan.',
      encoding: 'Het importscript leest tekst in de verkeerde tekencodering.',
      apology: 'Onze excuses voor het ongemak.',
      regression: 'Een nieuwe automatische test controleert nu speciale tekens.',
      buffer: 'De twee dagen passen in de tijdsbuffer van het project, zonder extra kosten.',
      library: 'De foute conversie komt uit een bibliotheek die jaren geleden is gekozen.'
    },
    reasons: {
      'developer.cause': 'Ontwikkelaars moeten weten wat de tests precies hebben gevonden.',
      'developer.encoding': 'Dit is de echte oorzaak waaraan ze gaan werken.',
      'developer.apology': 'Excuses aan klanten helpen een collega niet om de fout op te lossen.',
      'developer.regression': 'Ze moeten weten dat de fout nu door een test wordt afgedekt.',
      'developer.buffer': 'Tijdsbuffer en budget zijn een zaak van de projectleider.',
      'projectManager.newDate': 'De projectleider plant met de nieuwe datum.',
      'projectManager.noLoss': 'Gegevensverlies zou het risico volledig veranderen, dus moet hij horen dat het er niet is.',
      'projectManager.encoding': 'Het detail over de codering verandert geen enkele planningsbeslissing.',
      'projectManager.apology': 'Excuses zijn voor klanten; de projectleider heeft feiten nodig.',
      'projectManager.buffer': 'Of planning en budget nog kloppen, is precies zijn vraag.',
      'projectManager.library': 'Wie jaren geleden een bibliotheek koos, helpt de planning nu niet.',
      'customer.newDate': 'De klant heeft de nieuwe datum nodig, niet het soort fout.',
      'customer.noLoss': 'Zijn eerste zorg zijn zijn gegevens, en die zijn veilig.',
      'customer.cause': 'Details over fouten maken klanten ongerust zonder ze te helpen.',
      'customer.encoding': 'Technische details zeggen de klant niets.',
      'customer.regression': 'Interne tests zijn niet de zorg van de klant.',
      'customer.buffer': 'Interne buffers en kosten gaan de klant niet aan.',
      'customer.library': 'De schuld op een oude bibliotheek schuiven klinkt als een excuus.'
    },
    messages: {
      'developer.fit': 'Even ter info: het importscript leest tekst in de verkeerde codering, waardoor speciale tekens zoals ü en é stukgaan. Een regressietest dekt dat nu af; de overstap schuift naar donderdag.',
      'developer.missing': 'Kleine vertraging bij de migratie, niets ernstigs. Details volgen.',
      'developer.condescending': 'Speciale tekens zijn letters zoals ü die niet in het basisalfabet staan. Computers slaan letters op als getallen, en soms raken die getallen door elkaar.',
      'projectManager.fit': 'De migratie schuift van dinsdag naar donderdag. Er zijn geen gegevens verloren en de twee dagen passen zonder extra kosten in onze buffer. Oorzaak: een fout met speciale tekens, nu afgedekt door een test.',
      'projectManager.tooMuch': 'Het importscript decodeert de invoer als Latin-1 in plaats van UTF-8, waardoor multibyte-tekens beschadigd raken; we patchen de reader en voegen een regressietest toe.',
      'projectManager.missing': 'We hebben een fout gevonden en werken eraan. We laten het je weten.',
      'customer.fit': 'Uw gegevens zijn veilig. Om ervoor te zorgen dat elke naam en elk adres correct wordt overgenomen, verschuiven we de overstap van dinsdag naar donderdag. Tot dan werkt alles zoals altijd.',
      'customer.tooMuch': 'Ons importscript gebruikte de verkeerde tekencodering, waardoor speciale tekens in testruns beschadigd raakten; de migratie heeft daarom twee extra dagen uit onze buffer nodig.',
      'customer.condescending': 'Maakt u zich geen zorgen over de techniek, dat is ingewikkeld. Het wordt gewoon iets later.'
    }
  },
  skyBlue: {
    title: 'Waarom de lucht blauw is',
    situation: 'Iemand vraagt je waarom de lucht blauw is. Je kent de natuurkunde erachter. Leg het uit.',
    facts: {
      sunlight: 'Zonlicht bevat alle kleuren.',
      scatter: 'Lucht verstrooit blauw licht veel sterker dan rood licht.',
      rayleigh: 'Deze rayleighverstrooiing groeit met de vierde macht van de frequentie (1/λ⁴).',
      sunset: 'Bij zonsondergang gaat het licht door meer lucht, daardoor kleurt de lucht rood en oranje.',
      everywhere: 'Verstrooid blauw licht bereikt je ogen uit alle richtingen, daarom lijkt de hele lucht blauw.',
      violet: 'Violet wordt nog sterker verstrooid, maar zonlicht bevat minder violet en onze ogen zijn er minder gevoelig voor.',
      molecules: 'De verstrooiing komt van stikstof- en zuurstofmoleculen, die veel kleiner zijn dan de golflengte van licht.',
      ocean: 'De lucht is blauw omdat ze de zee weerspiegelt.'
    },
    reasons: {
      'child.sunlight': 'Kinderen hebben eerst de verrassing nodig: in wit zonlicht zitten alle kleuren.',
      'child.scatter': 'Dit is het kernidee, in eenvoudige woorden.',
      'child.rayleigh': 'Met een formule ben je een kind meteen kwijt.',
      'child.everywhere': 'Het verklaart wat ze zien: blauw, waar ze ook kijken.',
      'child.violet': 'Het detail over violet verwart op deze leeftijd meer dan het helpt.',
      'child.molecules': 'Moleculen en golflengtes zijn te abstract voor een kind.',
      'layperson.sunlight': 'Zonder dit is „blauw licht wordt verstrooid” onbegrijpelijk.',
      'layperson.scatter': 'Dit is het eigenlijke antwoord, in gewone taal.',
      'layperson.rayleigh': 'De formule voegt niets toe waar een leek iets mee kan.',
      'expert.rayleigh': 'Een expert verwacht het precieze mechanisme en de afhankelijkheid van de golflengte.',
      'expert.everywhere': 'Dit is vanzelfsprekend voor een expert en kost alleen tijd.',
      'expert.violet': 'Experts kennen de voor de hand liggende tegenwerping „waarom niet violet?” – beantwoord die.',
      'expert.molecules': 'De verstrooiers en de grootteverhouding noemen maakt de uitleg precies.',
      ocean: 'Dit is een bekende mythe; de kleur komt niet van de zee.'
    },
    messages: {
      'child.fit': 'Zonlicht ziet er wit uit, maar eigenlijk zijn alle kleuren erin gemengd. Als het door de lucht vliegt, wordt het blauwe deel het meest heen en weer gekaatst, dus komt er van overal in de lucht blauw naar je ogen.',
      'child.tooMuch': 'Blauw licht heeft een kortere golflengte, en rayleighverstrooiing groeit met één gedeeld door de golflengte tot de vierde macht.',
      'child.missing': 'Zo is de lucht nu eenmaal. Hij is altijd blauw geweest.',
      'layperson.fit': 'Zonlicht bevat alle kleuren. De lucht verstrooit blauw licht veel sterker dan rood, daardoor bereikt blauw licht ons uit elk deel van de hemel.',
      'layperson.tooMuch': 'Het is rayleighverstrooiing: de intensiteit schaalt met 1/λ⁴, dus korte golflengtes domineren de diffuse hemelstraling.',
      'layperson.condescending': 'Het is een beetje ingewikkeld voor niet-wetenschappers. Laten we zeggen dat de lucht hem blauw maakt.',
      'expert.fit': 'Rayleighverstrooiing aan N₂- en O₂-moleculen, evenredig met 1/λ⁴. Violet wordt nog sterker verstrooid, maar het zonnespectrum bevat minder violet en onze kegeltjes zijn er minder gevoelig voor.',
      'expert.condescending': 'Stel je zonlicht voor als een doos kleurpotloden! De lucht speelt het liefst met het blauwe potlood.',
      'expert.missing': 'De lucht verstrooit blauw licht sterker, daarom.'
    }
  },
  clubRoof: {
    title: 'Dak van het clubhuis',
    situation: 'Het dak van het clubhuis van je sportclub moet dringend worden gerepareerd, en het kost meer dan gepland. Leg het uit.',
    facts: {
      cost: 'De reparatie kost 8.000 euro, 3.000 meer dan begroot.',
      decision: 'Het bestuur moet vóór vrijdag beslissen of er 3.000 euro uit het budget van het zomerfeest wordt overgeheveld.',
      storage: 'De materiaalruimte blijft dicht tot de reparatie; de rest van het clubhuis is open.',
      fees: 'De contributie verandert niet.',
      schedule: 'De dakdekker begint op 12 mei en heeft vier dagen nodig; het parkeerterrein is nodig voor de steiger.',
      tiles: 'De nieuwe pannen zijn antracietkleurige betonpannen.',
      reserve: 'Als je in plaats daarvan de reserve gebruikt, zakt die onder het verplichte minimum.',
      volunteer: 'Een lid bood aan het dak gratis zelf te repareren, maar hij is geen dakdekker.'
    },
    reasons: {
      'executive.cost': 'Het bestuur heeft het bedrag en de overschrijding nodig om te oordelen.',
      'executive.decision': 'Dit is de beslissing die het moet nemen, met de deadline.',
      'executive.storage': 'Het dagelijkse gebruik van ruimtes is geen bestuurszaak.',
      'executive.schedule': 'De precieze werkdagen zijn de taak van de coördinator.',
      'executive.tiles': 'Soort en kleur van de pannen hebben geen invloed op de beslissing.',
      'executive.reserve': 'Het legt uit waarom het voor de hand liggende alternatief geen optie is.',
      'projectManager.fees': 'De contributie heeft niets te maken met het organiseren van de reparatie.',
      'projectManager.schedule': 'Precies deze data en het parkeerterrein regelt de coördinator.',
      'projectManager.reserve': 'De financiering is een beslissing van het bestuur, niet van de coördinator.',
      'layperson.storage': 'Leden willen weten wat ze wel en niet kunnen gebruiken.',
      'layperson.fees': 'Hun eigen geld is hun eerste vraag.',
      'layperson.tiles': 'Materiaaldetails doen er voor leden niet toe.',
      'layperson.reserve': 'Regels over de reserve zijn interne financiële details.',
      volunteer: 'Een aanbod zonder de juiste vakkennis leidt alleen tot een zinloze discussie; het is geen echte optie.'
    },
    messages: {
      'executive.fit': 'Beslissing nodig vóór vrijdag: de dakreparatie kost 8.000 euro, 3.000 meer dan begroot. We stellen voor 3.000 over te hevelen uit het budget van het zomerfeest, omdat de reserve anders onder het minimum zakt.',
      'executive.tooMuch': 'De dakdekker begint op 12 mei met antracietkleurige betonpannen; de steiger staat vier dagen op het parkeerterrein en de materiaalruimte blijft tot dan dicht.',
      'executive.missing': 'Het dak wordt duurder. We houden jullie op de hoogte.',
      'projectManager.fit': 'De dakdekker begint op 12 mei en heeft vier dagen nodig. Houd het parkeerterrein vanaf 11 mei vrij voor de steiger.',
      'projectManager.tooMuch': 'De reparatie kost 8.000 euro, 3.000 boven budget; het bestuur hevelt misschien geld over van het zomerfeest, omdat de reserve niet onder het minimum mag, en de contributie blijft gelijk.',
      'projectManager.missing': 'Ergens in mei komt er werk aan het dak.',
      'layperson.fit': 'Het dak van het clubhuis wordt in mei gerepareerd. Tot dan blijft de materiaalruimte dicht; al het andere is gewoon open. De contributie verandert niet.',
      'layperson.tooMuch': 'De reparatie kost 8.000 euro, 3.000 boven budget; het bestuur overweegt geld over te hevelen van het zomerfeest, omdat de reserve niet onder het minimum mag zakken.',
      'layperson.condescending': 'Maak je geen zorgen over het dak, het bestuur regelt de grotemensenzaken.'
    }
  },
  shopOutage: {
    title: 'Storing in de webwinkel',
    situation: 'De webwinkel van je bedrijf lag gisteren drie uur plat. Leg uit wat er is gebeurd.',
    facts: {
      duration: 'De winkel lag gisteravond drie uur plat.',
      revenue: 'Er is voor ongeveer 40.000 euro aan bestellingen verloren gegaan.',
      cause: 'Een verlopen beveiligingscertificaat blokkeerde de betalingen.',
      fixed: 'Het certificaat is vernieuwd; de winkel werkt weer normaal.',
      renewal: 'Het vernieuwen wordt geautomatiseerd, met een waarschuwing twee weken van tevoren; dat kost het team één dag.',
      voucher: 'Klanten van wie de bestelling mislukte, krijgen per e-mail een tegoedbon van 10%.',
      approval: 'De directie wordt gevraagd 5.000 euro goed te keuren voor betere monitoring.',
      competitor: 'De winkel van een concurrent had vorige maand een vergelijkbare storing.'
    },
    reasons: {
      'projectManager.cause': 'De projectleider heeft de oorzaak nodig om de oplossing te beoordelen.',
      'projectManager.renewal': 'Dit is het werk dat hij moet inplannen: één dag van het team.',
      'projectManager.voucher': 'Tegoedbonnen regelt de klantenservice, niet het project.',
      'executive.duration': 'De directie heeft de omvang van het incident nodig.',
      'executive.revenue': 'Voor de directie komt de zakelijke impact eerst.',
      'executive.cause': 'Het technische detail verandert hun beslissing niet; „een gemiste vernieuwing” is genoeg.',
      'executive.renewal': 'Ze moeten horen dat het niet opnieuw gebeurt.',
      'executive.approval': 'Dit is de beslissing die ze moeten nemen.',
      'customer.revenue': 'Jullie gemiste omzet is niet de zorg van de klant.',
      'customer.cause': 'Technische oorzaken helpen klanten niet.',
      'customer.fixed': 'Klanten willen eerst weten dat ze weer kunnen winkelen.',
      'customer.renewal': 'Interne procesveranderingen gaan klanten niet aan.',
      'customer.voucher': 'Dit krijgen ze, en ze moeten op de e-mail letten.',
      'customer.approval': 'Interne budgetbeslissingen zijn niet voor klanten.',
      competitor: 'Naar anderen wijzen klinkt als een excuus en verandert niets.'
    },
    messages: {
      'projectManager.fit': 'De storing van drie uur gisteren kwam door een verlopen beveiligingscertificaat dat de betalingen blokkeerde. Om herhaling te voorkomen, automatiseren we het vernieuwen met een vroege waarschuwing; dat kost het team deze sprint één dag.',
      'projectManager.tooMuch': 'We zijn ongeveer 40.000 euro aan bestellingen kwijt, klanten krijgen per e-mail een tegoedbon van 10% en een concurrent had vorige maand hetzelfde probleem.',
      'projectManager.missing': 'De winkel had gisteren een kort hikje, alles is weer in orde.',
      'executive.fit': 'Gisteren lag de winkel drie uur plat; we zijn ongeveer 40.000 euro aan bestellingen misgelopen. Een gemiste routinevernieuwing was de oorzaak en die is nu geautomatiseerd. Om zulke problemen vroeg te zien, vragen we u 5.000 euro voor monitoring goed te keuren.',
      'executive.tooMuch': 'Het TLS-certificaat van de betaalgateway verliep om 18:02; we vernieuwen het nu automatisch via het ACME-protocol, met een waarschuwing 14 dagen vooraf.',
      'executive.missing': 'Er was gisteren een klein technisch probleem. Het is opgelost.',
      'customer.fit': 'Excuses: gisteravond was onze winkel een paar uur niet bereikbaar. Alles werkt weer. Als uw bestelling mislukte, ontvangt u per e-mail een tegoedbon van 10%.',
      'customer.tooMuch': 'Een verlopen beveiligingscertificaat legde ons betaalsysteem stil; we zijn ongeveer 40.000 euro kwijt en vernieuwen certificaten nu automatisch.',
      'customer.condescending': 'Er ging iets technisch mis, dat begrijpt u toch niet. Probeer het gewoon nog eens.'
    }
  },
  signalFault: {
    title: 'Seinstoring bij het spoor',
    situation: 'Een seinstoring verstoort een spoorlijn. Je werkt bij het spoor. Leg de situatie uit.',
    facts: {
      delay: 'Treinen op deze lijn hebben ongeveer 40 minuten vertraging.',
      bus: 'Vervangende bussen vertrekken elke 20 minuten van het stationsplein.',
      tickets: 'Vervoerbewijzen zijn ook geldig in de bussen en in latere treinen.',
      signal: 'Sein 14 bij het splitsingspunt staat na een kabelstoring permanent op rood.',
      singleTrack: 'Treinen rijden het baanvak over één spoor met loopsnelheid, op schriftelijke opdracht.',
      repair: 'De technici verwachten dat de reparatie nog ongeveer vier uur duurt.',
      construction: 'Waarschijnlijk heeft bouwwerk van een ander bedrijf de kabel beschadigd.',
      staff: 'Twee technici zijn deze week ziek.'
    },
    reasons: {
      'layperson.delay': 'Reizigers willen eerst weten hoeveel later ze aankomen.',
      'layperson.bus': 'Het vertelt wat ze nu meteen kunnen doen.',
      'layperson.tickets': 'Het beantwoordt de zorg of ze een nieuw kaartje nodig hebben.',
      'layperson.signal': 'Seinnummers zeggen reizigers niets.',
      'layperson.singleTrack': 'Bedrijfsregels helpen reizigers niet.',
      'layperson.construction': 'Speculeren over schuld helpt reizigers niet en kan onjuist zijn.',
      'layperson.staff': 'Interne bezetting is niet de zorg van reizigers.',
      'expert.tickets': 'Regels voor vervoerbewijzen hebben geen invloed op het treinverkeer.',
      'expert.signal': 'De collega heeft de exacte plek en storing nodig.',
      'expert.singleTrack': 'Dit is de bedrijfsregel die hij moet toepassen.',
      'expert.repair': 'Hij plant de dienstregeling rond het verwachte einde.',
      'expert.staff': 'De bezetting verandert niets aan hoe het baanvak wordt bereden.',
      'executive.delay': 'De directie heeft de omvang van de verstoring nodig.',
      'executive.tickets': 'Geldigheid van kaartjes is een standaardregel, geen directiezaak.',
      'executive.repair': 'Ze moeten weten hoe lang de gevolgen duren.',
      'executive.construction': 'Mogelijke schade door derden is belangrijk voor aansprakelijkheid en kosten.'
    },
    messages: {
      'layperson.fit': 'Treinen op deze lijn hebben ongeveer 40 minuten vertraging. Vervangende bussen vertrekken elke 20 minuten van het stationsplein en uw kaartje is daarin geldig.',
      'layperson.tooMuch': 'Sein 14 bij het splitsingspunt staat na een kabelstoring permanent op rood; treinen rijden over één spoor met loopsnelheid op schriftelijke opdracht.',
      'layperson.missing': 'Even geduld alstublieft, er is een technische storing.',
      'expert.fit': 'Sein 14 bij het splitsingspunt staat na een kabelstoring vast op rood. Enkelsporig rijden met loopsnelheid op schriftelijke opdracht; reparatie duurt naar verwachting nog ongeveer vier uur.',
      'expert.condescending': 'Een sein is een soort verkeerslicht voor treinen. Er is er een kapot, dus moeten de treinen langzaam rijden.',
      'expert.missing': 'Er is een probleem op de lijn en treinen zijn te laat. Er rijden bussen.',
      'executive.fit': 'Een kabelstoring verstoort de lijn nog ongeveer vier uur; treinen rijden zo’n 40 minuten te laat. Waarschijnlijk heeft bouwwerk van een ander bedrijf de kabel beschadigd, dus we onderzoeken de aansprakelijkheid.',
      'executive.tooMuch': 'Sein 14 staat permanent op rood; enkelsporig rijden met loopsnelheid op schriftelijke opdracht; bussen elke 20 minuten van het plein; kaartjes geldig in de bussen.',
      'executive.missing': 'Klein seinprobleem, het team is ermee bezig.'
    }
  },
  kettleLid: {
    title: 'Deksel van de waterkoker',
    situation: 'Je bedrijf heeft ontdekt dat het deksel van één model waterkoker los kan gaan. Leg het uit.',
    facts: {
      batches: 'Alleen waterkokers met batchnummers 2301 tot en met 2315 zijn getroffen (gedrukt onder de voet).',
      risk: 'Het deksel kan opengaan tijdens het schenken, waardoor heet water kan spatten.',
      stop: 'Gebruik een getroffen waterkoker niet meer tot hij is vervangen.',
      hinge: 'Een plastic scharnierpen is 0,2 mm te dun gemaakt.',
      free: 'De vervanging is gratis, inclusief verzending.',
      cost: 'De omruiling kost het bedrijf ongeveer 120.000 euro.',
      supplier: 'De pennen kwamen van een nieuwe leverancier wiens monsters de keuring hadden doorstaan.',
      injuries: 'Er zijn tot nu toe geen verwondingen bekend.'
    },
    reasons: {
      'customer.batches': 'Klanten moeten kunnen nagaan of hun waterkoker getroffen is.',
      'customer.risk': 'Ze moeten begrijpen waarom het belangrijk is.',
      'customer.stop': 'Dit is de handeling die hen veilig houdt.',
      'customer.hinge': 'Millimeterdetails helpen klanten niet.',
      'customer.free': 'Weten dat het niets kost, neemt een reden om te wachten weg.',
      'customer.cost': 'De kosten van het bedrijf zijn niet de zorg van de klant.',
      'customer.supplier': 'Details over de leverancier klinken als de schuld afschuiven.',
      'executive.risk': 'De directie moet eerst het veiligheidsrisico begrijpen.',
      'executive.hinge': 'De exacte maat is iets voor ingenieurs.',
      'executive.cost': 'De financiële impact hoort bij hun beslissing.',
      'executive.injuries': 'Of er iemand gewond is, verandert de urgentie en de reactie.',
      'expert.stop': 'Instructies voor klanten helpen niet bij het analyseren van het defect.',
      'expert.hinge': 'De ingenieur heeft het exacte defect nodig.',
      'expert.free': 'Verzendvoorwaarden doen er voor de technische analyse niet toe.',
      'expert.cost': 'De kosten van de terugroepactie zijn niet nodig om het onderdeel te verbeteren.',
      'expert.supplier': 'Het laat zien waar de kwaliteitscontrole moet veranderen.'
    },
    messages: {
      'customer.fit': 'Controleer het batchnummer onder uw waterkoker. Ligt het tussen 2301 en 2315, gebruik hem dan niet meer: het deksel kan opengaan tijdens het schenken. We vervangen hem gratis, inclusief verzending.',
      'customer.tooMuch': 'Een scharnierpen van een nieuwe leverancier was 0,2 mm te dun; de omruiling kost ons ongeveer 120.000 euro.',
      'customer.condescending': 'Sommige waterkokers hebben misschien een klein probleempje. U hoeft de details niet te begrijpen; stuur hem terug als u wilt.',
      'executive.fit': 'Veiligheidsprobleem: bij batches 2301 tot en met 2315 kan het deksel opengaan tijdens het schenken van heet water. Tot nu toe geen verwondingen bekend. De omruiling kost ongeveer 120.000 euro.',
      'executive.tooMuch': 'De diameter van de scharnierpen ligt 0,2 mm onder de tolerantie; de monsters van de nieuwe leverancier waren binnen de specificatie, dus we vermoeden slijtage van het gereedschap.',
      'executive.missing': 'We vervangen uit voorzorg een aantal waterkokers.',
      'expert.fit': 'De scharnierpennen van de nieuwe leverancier zijn 0,2 mm te dun, waardoor het deksel tijdens het schenken kan opengaan. Getroffen batches: 2301 tot en met 2315. Hun monsters waren goedgekeurd, dus onze ingangscontrole moet veranderen.',
      'expert.missing': 'Sommige deksels zitten los; klanten krijgen gratis vervanging.',
      'expert.condescending': 'Een scharnier is het onderdeel waarmee het deksel draait. Als het te dun is, houdt het niet goed.'
    }
  },
  renovation: {
    title: 'Vertraagde verbouwing',
    situation: 'Je leidt het bouwbedrijf dat de keuken en badkamer van een twee-onder-een-kapwoning verbouwt. Het werk loopt vertraging op. Leg het uit.',
    facts: {
      delay: 'De verbouwing is een week later klaar: op 21 juni in plaats van 14 juni.',
      tiles: 'De leverancier leverde badkamertegels van 30 × 60 cm in plaats van 60 × 60 cm; ze moeten opnieuw besteld worden.',
      order: 'Tot de nieuwe tegels er zijn, werkt de ploeg eerst aan de keuken.',
      water: 'De gedeelde waterleiding wordt dinsdag van 8 tot 12 uur afgesloten.',
      noise: 'Volgende week wordt er nog drie dagen luid geboord, tussen 8 en 17 uur.',
      cost: 'De vertraging kost de eigenaren niets; de leverancier betaalt de nieuwe tegels.',
      supplierHistory: 'Deze tegelleverancier had dit jaar al meerdere keren leveringsproblemen.',
      skip: 'Maandag staat de container op straat voor de oprit van de buren.'
    },
    reasons: {
      'customer.delay': 'De eigenaren plannen rond de nieuwe opleverdatum.',
      'customer.tiles': 'Het precieze tegelformaat is een zaak van de ploeg; de eigenaren hebben de datum en de kosten nodig.',
      'customer.water': 'Ze moeten weten wanneer ze geen water hebben.',
      'customer.cost': 'Hun eerste zorg is of de vertraging hun geld kost.',
      'projectManager.delay': 'De ploegleider plant het resterende werk naar de nieuwe datum toe.',
      'projectManager.tiles': 'De ploeg moet precies weten wat er mis is met de levering.',
      'projectManager.order': 'Dit doet de ploeg morgenochtend.',
      'projectManager.water': 'De ploeg sluit het water af en moet iedereen waarschuwen.',
      'projectManager.cost': 'Wie betaalt, regelen kantoor en leverancier; het verandert niets aan het werk.',
      'projectManager.skip': 'De ploegleider moet regelen waar de container komt.',
      'neighbour.tiles': 'Tegeldetails gaan de buren niets aan.',
      'neighbour.order': 'De werkvolgorde van de ploeg raakt de buren niet.',
      'neighbour.water': 'De buren delen de leiding en hebben de precieze tijden nodig.',
      'neighbour.noise': 'De tijden van lawaai raken de buren het meest.',
      'neighbour.cost': 'De kosten van de eigenaren zijn privé.',
      'neighbour.skip': 'De container blokkeert hun oprit, dus moeten ze het vooraf weten.',
      supplierHistory: 'Klagen over de leverancier klinkt als een excuus en helpt niemand.'
    },
    messages: {
      'customer.fit': 'Uw verbouwing is op 21 juni klaar in plaats van 14 juni, omdat de badkamertegels in het verkeerde formaat zijn geleverd. Dat kost u niets. Let op: dinsdag is het water van 8 tot 12 uur afgesloten.',
      'customer.tooMuch': 'De leverancier stuurde 30 × 60 in plaats van 60 × 60, dus het legplan klopt niet meer; de ploeg doet nu eerst de keuken en de container komt maandag op straat.',
      'customer.condescending': 'Er is een klein probleempje met de tegels, daar hoeft u zich geen zorgen over te maken. Laat dat maar aan de vakmensen over.',
      'projectManager.fit': 'De badkamertegels kwamen als 30 × 60 in plaats van 60 × 60, dus eerst de keuken tot de nabestelling er is. Nieuwe oplevering: 21 juni. Dinsdag water af van 8 tot 12 uur, en maandag komt de container op straat.',
      'projectManager.missing': 'Er is vertraging bij de badkamer. Ga maar gewoon door.',
      'projectManager.condescending': 'Tegels hebben een maat, en als de maat verkeerd is, passen ze niet. Dus leg ze alsjeblieft niet.',
      'neighbour.fit': 'Over de verbouwing hiernaast: dinsdag is de gedeelde waterleiding van 8 tot 12 uur afgesloten, en volgende week wordt er nog drie dagen luid geboord, tussen 8 en 17 uur. Maandag staat de container voor uw oprit. Excuses voor het ongemak.',
      'neighbour.tooMuch': 'De badkamertegels kwamen in het verkeerde formaat, dus de ploeg schakelt over naar de keuken, en de eigenaren betalen niets extra omdat de leverancier het vergoedt.',
      'neighbour.missing': 'We zijn hiernaast een beetje aan het verbouwen. Bedankt voor uw geduld.'
    }
  },
  schoolTrip: {
    title: 'Wijziging schoolreisje',
    situation: 'Je bent klassenleraar. Het busbedrijf heeft afgezegd, dus het uitje naar de dierentuin moet verschuiven. Leg het uit.',
    facts: {
      newDate: 'Het dierentuinuitje verschuift van donderdag naar volgende week dinsdag.',
      bus: 'Het busbedrijf heeft afgezegd omdat twee chauffeurs ziek zijn.',
      lunch: 'Kinderen nemen zoals gepland een lunchpakket en drinken mee.',
      form: 'Ouders moeten vóór vrijdag een nieuw toestemmingsformulier ondertekenen.',
      price: 'De prijs blijft 12 euro per kind.',
      cover: 'Dinsdag moet iemand mijn lessen aan klas 7b van 10 tot 12 uur overnemen.',
      rain: 'Bij hevige regen bezoekt de klas in plaats daarvan het aquariumhuis.',
      complaint: 'Sommige ouders klaagden dat donderdag toch al een slechte dag was.'
    },
    reasons: {
      'child.newDate': 'Kinderen willen eerst weten wanneer het uitje is.',
      'child.bus': 'Zieke buschauffeurs zijn niets waar kinderen over hoeven na te denken.',
      'child.lunch': 'Dit moeten ze zelf meenemen.',
      'child.form': 'Het formulier is voor de ouders, niet voor de kinderen.',
      'child.price': 'Geld regelen de ouders.',
      'child.cover': 'Afspraken tussen leraren gaan de kinderen niet aan.',
      'child.rain': 'Het vertelt hun wat ze kunnen verwachten, en dat willen kinderen graag weten.',
      'parent.newDate': 'Ouders hebben de nieuwe datum nodig om hun week te plannen.',
      'parent.lunch': 'Zij maken het lunchpakket klaar.',
      'parent.form': 'Dit moeten ze doen, met een deadline.',
      'parent.price': 'Ze willen weten of het duurder wordt.',
      'parent.cover': 'Vervangende lessen zijn een interne schoolzaak.',
      'parent.rain': 'Zo kunnen ze hun kind op het weer voorbereiden.',
      'colleague.newDate': 'De collega moet weten om welke dag het gaat.',
      'colleague.lunch': 'Lunchpakketten zijn voor de klas, niet voor de collega.',
      'colleague.price': 'De prijs van het uitje raakt de collega niet.',
      'colleague.cover': 'Dit is wat je eigenlijk aan hen vraagt.',
      'colleague.rain': 'Het slechtweerplan verandert niets aan de lessen van de collega.',
      complaint: 'Klachten doorgeven zorgt voor onrust en verandert niets.'
    },
    messages: {
      'child.fit': 'Ons dierentuinuitje is nu volgende week dinsdag! Neem een lunchpakket en drinken mee, zoals afgesproken. Als het hard regent, gaan we naar het aquariumhuis.',
      'child.tooMuch': 'Het busbedrijf heeft afgezegd omdat twee chauffeurs ziek zijn, jullie ouders moeten vóór vrijdag een nieuw formulier tekenen, en de prijs blijft 12 euro.',
      'child.missing': 'Er verandert iets aan het uitje. Jullie horen later meer.',
      'parent.fit': 'Het dierentuinuitje verschuift van donderdag naar volgende week dinsdag, omdat het busbedrijf heeft afgezegd. Wilt u vóór vrijdag het nieuwe toestemmingsformulier ondertekenen? De prijs blijft 12 euro; uw kind heeft nog steeds een lunchpakket en drinken nodig.',
      'parent.tooMuch': 'Bij het busbedrijf zijn twee chauffeurs ziek, ik heb dinsdag van 10 tot 12 uur vervanging nodig voor klas 7b, en sommige ouders vonden donderdag toch al een slechte dag.',
      'parent.condescending': 'Maakt u zich geen zorgen over de details, wij leraren hebben alles onder controle. Teken gewoon wat uw kind mee naar huis neemt.',
      'colleague.fit': 'Ons dierentuinuitje is nu volgende week dinsdag. Kun jij die dag mijn lessen aan klas 7b van 10 tot 12 uur overnemen?',
      'colleague.tooMuch': 'De kinderen nemen een lunchpakket mee, de prijs blijft 12 euro, het toestemmingsformulier moet vrijdag binnen zijn, en bij regen gaan we naar het aquariumhuis.',
      'colleague.missing': 'Het uitje verschuift trouwens.'
    }
  },
  practiceMonday: {
    title: 'Huisartsenpraktijk: afspraken op maandag',
    situation: 'Je werkt aan de balie van een huisartsenpraktijk. Een arts is maandag onverwacht afwezig, dus afspraken moeten verschuiven. Leg het uit. (Het gaat alleen om afspraken, niet om gezondheid.)',
    facts: {
      moved: 'Alle maandagafspraken bij dokter Lind verschuiven naar woensdag, op hetzelfde tijdstip.',
      away: 'Dokter Lind is onverwacht afwezig om privéredenen.',
      urgent: 'Dringende zaken op maandag worden opgevangen door de tweede arts van de praktijk.',
      calls: '42 patiënten moeten vóór vrijdag gebeld worden.',
      reply: 'Wie woensdag niet kan, belt de praktijk voor een ander tijdstip.',
      hours: 'Het omboeken kost deze week ongeveer zes extra personeelsuren, die de praktijkmanager moet goedkeuren.',
      vip: 'Een van de maandagpatiënten is een bekende lokale politicus.',
      texts: 'Het nieuwe afsprakensysteem kan automatisch sms-herinneringen sturen.'
    },
    reasons: {
      'patient.moved': 'De patiënt heeft eerst de nieuwe dag en tijd nodig.',
      'patient.urgent': 'Hij moet weten waar hij terechtkan als iets niet kan wachten.',
      'patient.calls': 'Hoeveel mensen het betreft, is interne werkdruk.',
      'patient.reply': 'Het vertelt wat hij kan doen als woensdag niet uitkomt.',
      'patient.hours': 'Personeelsuren zijn een zaak van de praktijk.',
      'patient.texts': 'Interne hulpmiddelen hoeft de patiënt niet te horen.',
      'executive.moved': 'De praktijkmanager moet weten wat er in de planning verandert.',
      'executive.calls': 'Het laat de omvang van het werk zien.',
      'executive.reply': 'Instructies voor patiënten zijn baliewerk, geen managementvraag.',
      'executive.hours': 'Dit is de beslissing die de praktijkmanager moet nemen.',
      'colleague.moved': 'De collega moet patiënten de nieuwe tijd doorgeven.',
      'colleague.urgent': 'Patiënten gaan ernaar vragen, dus de collega heeft het antwoord nodig.',
      'colleague.calls': 'Dit is de taak die je overdraagt.',
      'colleague.hours': 'Extra uren keurt de manager goed; de collega heeft de taak nodig.',
      'colleague.texts': 'Het scheelt haar veel telefoontjes.',
      vip: 'Wie de patiënten zijn, is vertrouwelijk en hoort in geen van deze berichten thuis.'
    },
    messages: {
      'patient.fit': 'Uw afspraak bij dokter Lind op maandag verschuift naar woensdag, op hetzelfde tijdstip. Komt woensdag u niet uit, bel ons dan voor een ander tijdstip. Dringende zaken op maandag worden opgevangen door onze tweede arts.',
      'patient.tooMuch': 'We moeten vóór vrijdag 42 patiënten bellen, wat ongeveer zes extra personeelsuren kost, en het nieuwe systeem kan sms-herinneringen sturen.',
      'patient.condescending': 'Artsen hebben het nu eenmaal druk. Kom gewoon woensdag en maak u geen zorgen over het waarom.',
      'executive.fit': 'Wil je deze week ongeveer zes extra personeelsuren goedkeuren? Dokter Lind is maandag afwezig, dus 42 afspraken verschuiven naar woensdag en die patiënten moeten vóór vrijdag gebeld worden.',
      'executive.tooMuch': 'Wie woensdag niet kan, moet ons bellen, dringende zaken gaan naar de tweede arts, en sms-herinneringen kun je aanzetten in het instellingenmenu.',
      'executive.missing': 'Maandag is een beetje rommelig, we lossen het op.',
      'colleague.fit': 'Kun je me helpen om vóór vrijdag de 42 patiënten te bellen die maandag bij dokter Lind staan? Hun afspraken verschuiven naar woensdag, op hetzelfde tijdstip; dringende zaken op maandag gaan naar de tweede arts. Het nieuwe systeem kan ook sms-herinneringen sturen.',
      'colleague.missing': 'De maandagafspraken veranderen, even ter info.',
      'colleague.condescending': 'Patiënten bellen is makkelijk: hoorn opnemen, nummer kiezen, praten. Doe dat alsjeblieft voor de maandaglijst.'
    }
  },
  libraryHours: {
    title: 'Openingstijden van de bibliotheek',
    situation: 'Je leidt de stadsbibliotheek. Door bezuinigingen veranderen de openingstijden. Leg het uit.',
    facts: {
      hours: 'Vanaf 1 september is de bibliotheek dinsdag tot en met zaterdag open van 10 tot 18 uur en op maandag gesloten.',
      cards: 'Bibliotheekpassen en online lenen veranderen niet.',
      budget: 'De gemeente heeft het budget van de bibliotheek met 15% verlaagd.',
      returns: 'Boeken kunnen nog steeds altijd via de inleverbus worden teruggebracht.',
      shifts: 'De diensten veranderen: geen maandagdiensten meer, langere zaterdagdiensten.',
      savings: 'De nieuwe tijden besparen ongeveer 40.000 euro per jaar, en niemand verliest zijn baan.',
      petition: 'Een lezer is een petitie gestart tegen de sluiting op maandag.',
      heating: 'De sluiting op maandag bespaart ook op verwarming, omdat het oude gebouw slecht geïsoleerd is.'
    },
    reasons: {
      'customer.hours': 'Lezers moeten eerst weten wanneer ze kunnen komen.',
      'customer.cards': 'Het beantwoordt de zorg of hun pas en online lenen nog werken.',
      'customer.returns': 'Het vertelt wat ze op een gesloten dag toch kunnen doen.',
      'customer.shifts': 'Dienstroosters zijn intern.',
      'customer.savings': 'Begrotingscijfers helpen lezers niet hun bezoek te plannen.',
      'customer.petition': 'De petitie noemen kiest partij en helpt lezers niet plannen.',
      'customer.heating': 'De isolatie van het gebouw is een intern detail.',
      'colleague.hours': 'Collega’s beantwoorden de vragen van lezers over de nieuwe tijden.',
      'colleague.cards': 'Collega’s kennen hun eigen systemen; deze zin is voor lezers.',
      'colleague.shifts': 'Dit verandert hun eigen werkweek.',
      'colleague.savings': 'Horen dat niemand zijn baan verliest, is voor hen heel belangrijk.',
      'colleague.heating': 'Verwarmingskosten veranderen niets aan hun werk.',
      'executive.hours': 'De gemeenteraad moet precies weten wat het publiek gaat zien.',
      'executive.budget': 'De raad heeft de bezuiniging zelf besloten; het herhalen kost alleen tijd.',
      'executive.returns': 'Details over de inleverbus zijn dagelijkse bedrijfsvoering.',
      'executive.savings': 'Besparingen en banen zijn precies waar de raad naar vroeg.',
      'executive.petition': 'Reacties van het publiek kunnen de raad bereiken, dus moet die het eerst van jou horen.'
    },
    messages: {
      'customer.fit': 'Vanaf 1 september is de bibliotheek dinsdag tot en met zaterdag open van 10 tot 18 uur en op maandag gesloten. U kunt boeken nog steeds altijd via de inleverbus terugbrengen, en uw pas en online lenen werken zoals altijd.',
      'customer.tooMuch': 'De gemeente heeft ons budget met 15% verlaagd, dus besparen we ongeveer 40.000 euro per jaar door de diensten aan te passen en het oude gebouw op maandag minder te verwarmen.',
      'customer.condescending': 'We weten dat verandering voor sommige lezers moeilijk is. Onthoud gewoon: op maandag geen bibliotheek. Zo simpel is het.',
      'colleague.fit': 'Vanaf 1 september veranderen onze diensten: geen maandagdiensten meer, langere zaterdagdiensten. We zijn open van dinsdag tot en met zaterdag van 10 tot 18 uur, en niemand verliest zijn baan.',
      'colleague.missing': 'In het najaar verandert er een en ander. Later meer.',
      'colleague.tooMuch': 'Lezers kunnen de inleverbus blijven gebruiken, passen en online lenen veranderen niet, en de maandagsluiting bespaart ook op verwarming in ons slecht geïsoleerde gebouw.',
      'executive.fit': 'De nieuwe openingstijden besparen ongeveer 40.000 euro per jaar zonder banenverlies: vanaf 1 september sluiten we op maandag en zijn we dinsdag tot en met zaterdag open van 10 tot 18 uur. Let op: een lezer is een petitie gestart tegen de maandagsluiting.',
      'executive.tooMuch': 'Inleveren blijft mogelijk via de inleverbus, passen en online lenen veranderen niet, en de zaterdagdiensten worden langer terwijl de maandagdiensten vervallen.',
      'executive.missing': 'We hebben de openingstijden wat aangepast.'
    }
  }
};
