/**
 * The shipped puzzle list — original, generated by `scripts/generate-puzzles.ts` (seeded random
 * placement + exhaustive breadth-first search; nothing is taken from a commercial puzzle set).
 * Do not edit by hand: regenerate instead.
 *
 * `layout`: 36 cells, row by row, top to bottom: `.` free, `x` star block, `a`… other blocks.
 * `optimum`: fewest moves (one block slid any distance) to free the star block. The test suite
 * re-derives every optimum with an independent solver (test/oracle.ts).
 */
export interface PuzzleSource {
  readonly layout: string;
  readonly optimum: number;
}

export const PUZZLES: Readonly<Record<'easy' | 'medium' | 'hard', readonly PuzzleSource[]>> = {
  /** Optimum 4–10 moves. */
  easy: [
    { layout: '.a..bbcaddefcgxxef.ghhii.jjjkk..llmm', optimum: 4 },
    { layout: '.aa.b.c.ddbecxxf.e.ggfhijj.khi.llk.i', optimum: 4 },
    { layout: '.aaabbcdeeefcdgxxfhigj..hikj.lhik..l', optimum: 4 },
    { layout: 'a...bbac.dddec.xxfegghhfi.jjkkillmm.', optimum: 4 },
    { layout: 'a.bbccadeffg.dexxg.hijj.khilmnk..lmn', optimum: 4 },
    { layout: 'aabc..debcffdebxxg.ehiig..hjjg..kkll', optimum: 4 },
    { layout: 'abc..dabcefdxx.efghi..jghikkj..lllmm', optimum: 4 },
    { layout: '.aaa.bc.dddbc.xx.e..fggeh.fiiih.jjkk', optimum: 5 },
    { layout: '.aab.cdeebfcdgxxfhdgii.hjjkkkh..llmm', optimum: 5 },
    { layout: '.aabb.ccddefgxx.efghijjkghil.k.mml.k', optimum: 5 },
    { layout: '.aabb.cdeeffcd.xxg..hhhgijkllmijknnm', optimum: 5 },
    { layout: 'ab..ccabdddexxf..e..fggg.hhiijkk...j', optimum: 5 },
    { layout: '...abbcc.ade.xx.deffgghhiiij...kkjll', optimum: 6 },
    { layout: '.aabbbcc.ddexxf..eggfhhijjkk.i.llmmm', optimum: 6 },
    { layout: 'a..bccaddbefaxx.efghi.jjghikk..llmm.', optimum: 6 },
    { layout: 'aa..bbccde..xxde.fgg.hhf....ijkkllij', optimum: 6 },
    { layout: 'abccddabeee..bxx.fghh.ifgjjkilmmmk.l', optimum: 6 },
    { layout: 'a.bbcca.dd..xxef.gh.ef.ghii...jjj.kk', optimum: 7 },
    { layout: 'aa..bb...cccdxxefgd..efgh.ii.jh.kkkj', optimum: 7 },
    { layout: 'aab.cc..bdddxxb.......eefggh..fiihjj', optimum: 7 },
    { layout: 'aabcc.d.beeedxx.fghijjfghikk.lh.mm.l', optimum: 7 },
    { layout: '...abbcddae.cfxxegcfhiigjfhk..jllk..', optimum: 8 },
    { layout: 'aa...bcddeebc..xxbcffggghhi.jj..i.kk', optimum: 8 },
    { layout: 'aabbbc..deecxxd....fgghhifj.kki.j.ll', optimum: 8 },
    { layout: 'aabcc.ddb.efxx..ef.g.hhf.giijj..kk..', optimum: 8 },
    { layout: 'a..bbba.ccddxx..efg...efghiiij.h.kkj', optimum: 9 },
    { layout: 'ab.cccabddeeaxx..fggh..f..hijk...ijk', optimum: 9 },
    { layout: '.aa...bbcccdxxe..dffe.gghhijjjkki.ll', optimum: 10 },
    { layout: 'aabccd..beedfg.xxdfg.hh.ijjjkki.llmm', optimum: 10 },
    { layout: 'abccc.abdeefxxdghf...gh.i..gj.i.kkj.', optimum: 10 }
  ],
  /** Optimum 11–20 moves. */
  medium: [
    { layout: '....abc...abcxx.ad..effd.gehhd.giijj', optimum: 11 },
    { layout: '..abccd.abe.d.xxefghhiifgjj..k.....k', optimum: 11 },
    { layout: '.aaa.bccdeeb..dxxbf..g..fhhgii.jj...', optimum: 11 },
    { layout: '.aaabb.cccdefxx.defgg..efhiijj.hkkll', optimum: 11 },
    { layout: '.aaabc....bcxx..bcde.ff.degghh..iijj', optimum: 11 },
    { layout: '.abccc.abdddxx.e...fge.h.fgiihjjj...', optimum: 11 },
    { layout: 'aab.ccddb.e..fxxeghfiiighf.jj..kkll.', optimum: 11 },
    { layout: '..a..b..a.cbdexxcfdeghhfi.gjkkillj..', optimum: 12 },
    { layout: '..abb.cca.dexx.fdeghhf.eg.ijjj..i.kk', optimum: 12 },
    { layout: '..abbb..acddxx.ce.fggce.fh.iij.hkk.j', optimum: 12 },
    { layout: '.abbcc.a.deexxfdgh..fdgh.ii..j...kkj', optimum: 12 },
    { layout: '.abcccdabeefdxx.gfh.iig.h..jk....jk.', optimum: 12 },
    { layout: 'a...bca.debcxxdefg.hiifg.h.jkklllj..', optimum: 12 },
    { layout: 'abbccda.ee.dfxx..df.ghhhiig.....g.jj', optimum: 12 },
    { layout: 'abbcddaeecf.xxg.fhiigjjhkkll..mm.nn.', optimum: 12 },
    { layout: 'abccddab.effxx.egh.iiigh..jjklmmnnkl', optimum: 12 },
    { layout: 'aa.bb..cc.dexxfgde..fghhijkkllij.mmm', optimum: 13 },
    { layout: 'abbcc.add.e.xxfge.h.fgiihjj..kll.mmk', optimum: 13 },
    { layout: '..abbb..acdd.xxc.e.ffghei..ghjikkk.j', optimum: 14 },
    { layout: '.abb...a.cddxx.c.efffg.e..hgii..h.jj', optimum: 14 },
    { layout: '.abb...acdddxxcef.gghef.i.he.jikkk.j', optimum: 14 },
    { layout: 'a..bb.a..cddaxxce.fghheifgjkkilljmm.', optimum: 14 },
    { layout: 'a.bbb.a..cddxxec..ffec..ghhiijg.kkkj', optimum: 14 },
    { layout: 'a.bbb.a..cddxxecfg..ehfgijehklijmmkl', optimum: 14 },
    { layout: 'aabbbcdd.efcxx.ef.gghh.ij.kkkij.llmm', optimum: 15 },
    { layout: 'aa.b....cbddxxc..e.fffge.hiigj.h...j', optimum: 16 },
    { layout: 'aaabbc.ddd.cxxe.f.ggehf.ijjh..i.....', optimum: 17 },
    { layout: 'abbc..a..cddxxe.f...e.fghhhiig.jjkkk', optimum: 17 },
    { layout: 'abbcd.a.ecd.xxefghiiifgh.jj.gk.lll.k', optimum: 18 },
    { layout: '.aaa.bccdddb..xxef..ghef..ghii..gjjj', optimum: 19 }
  ],
  /** Optimum 21+ moves. */
  hard: [
    { layout: '.aaa...bbcddxxec.fg.e..fghhiif....jj', optimum: 21 },
    { layout: '.aaa.bccdddbexxfghe.ifgh..ijjj...kkk', optimum: 21 },
    { layout: '.abb.c.adeecxxdfg...hfgij.hklijmmkl.', optimum: 21 },
    { layout: '.abbcc.addd.xxef..g.efhhg.iij.kk..j.', optimum: 21 },
    { layout: 'aab...c.bdddcxxef.gg.ef.hh.eijkkllij', optimum: 21 },
    { layout: 'aabc..d.bceedxx.fghhi.fg..ijjkllmm.k', optimum: 21 },
    { layout: 'abbb..a.cdeexxcd...f.dgg.fhhij.kk.ij', optimum: 21 },
    { layout: 'abbcc.a.deffxxdegh.i..gh.ijjg..ikkk.', optimum: 21 },
    { layout: 'abccddabee..xxfg..hifgjjhikklmnn..lm', optimum: 21 },
    { layout: 'a.bccda.b.edafxxeg.fhhigjj.kiglllk..', optimum: 22 },
    { layout: 'aab...c.bddecxxfgehhifgj..ikkjllmmmj', optimum: 22 },
    { layout: 'abccdeabfgdexxfg.hiijkkh..jlm..nnlm.', optimum: 22 },
    { layout: '.aabbcddeefcxx.gf.hhhgijklllijk..mm.', optimum: 23 },
    { layout: 'a..bccad.b.efdxxgefhh.g.f.i.g.jjikk.', optimum: 23 },
    { layout: 'aa...bcccd.bxxed.fgge..fh.iijjh.....', optimum: 23 },
    { layout: 'aa..b.cc..b.dxx.b.d.efffggeh...iihjj', optimum: 23 },
    { layout: 'aaab.c..db.cxxd.ecff..e.ghhiiigjjkkk', optimum: 23 },
    { layout: 'aab..c..bddc..xxef.gggef.h.ijj.h.i..', optimum: 23 },
    { layout: 'aabc..debcffdexxghii..gh.jj.kl.mmmkl', optimum: 23 },
    { layout: 'abbcd.a..cd.xxe..fgge..fhhhiif....jj', optimum: 23 },
    { layout: '..abb.c.a.d.cxx.deffggdehijjjehikk..', optimum: 24 },
    { layout: 'abbc..addcefxxg.efhhg..f..ijjjkki...', optimum: 24 },
    { layout: '..abbbcca.d.e.xxd.e...ffgghhhijjkk.i', optimum: 25 },
    { layout: 'aaabbc..dddcxxef..g.efhhg.iij.....j.', optimum: 25 },
    { layout: 'aabc..d.bceedxxfg.hhifgj..ikkj.llmmm', optimum: 25 },
    { layout: 'aabc..debcffdexxghiij.gh..jkklmmnn.l', optimum: 25 },
    { layout: 'abb.c.addecfxxge.fhhg..f.ijjkk.illmm', optimum: 25 },
    { layout: 'abbcc.a.deffxxdegh.ijjgh.ikkkh.ll...', optimum: 25 },
    { layout: 'a.bbbca.defcxxdefg...h.g...hiijjj...', optimum: 27 },
    { layout: '........abc.xxabc.ddeb.fgheiifghjjjf', optimum: 28 }
  ]
};
