/**
 * GENERATED by scripts/generate-puzzles.ts — do not edit by hand.
 * Original positions from the built-in engine's self-play, verified by the exhaustive mate
 * solver and deep search (and re-verified in test/puzzles.test.ts).
 */
import type { BestMovePuzzle, MatePuzzle } from './ai';

export const MATE_PUZZLES: readonly MatePuzzle[] = [
  { fen: 'r1bk2r1/1p1p1ppp/3p2N1/1BB5/1P6/8/PP3PPP/R3R1K1 w - - 4 20', n: 1, line: ['c5b6'] },
  { fen: '3r2kr/QR3pp1/4p3/2p4p/2n5/7P/P1P5/1K1R4 b - - 0 29', n: 1, line: ['d8d1'] },
  { fen: 'rq6/p3RQ2/1p3p1k/1B4p1/8/5N2/PPP2PPP/2K4R w - - 1 20', n: 1, line: ['f7h7'] },
  { fen: '6k1/4np2/8/p7/4q3/8/6r1/5K2 b - - 7 51', n: 1, line: ['e4e2'] },
  { fen: '8/1R6/5Q2/3k4/8/3P1P2/6P1/5K2 w - - 3 51', n: 1, line: ['b7b5'] },
  { fen: '8/5R2/7p/1B6/P2p4/8/1PP1R1PP/1K1k4 w - - 0 34', n: 1, line: ['f7f1'] },
  { fen: 'r1b2rk1/2pp1p2/pp3q2/6pQ/1N3P2/2PBB3/PP4PP/R3K2R w KQ - 0 19', n: 1, line: ['h5h7'] },
  { fen: '3r2kr/QR3pp1/4p3/2p4p/2n5/7P/P1Pq4/1K5R b - - 3 28', n: 2, line: ['d2d1', 'h1d1', 'd8d1'] },
  { fen: '6k1/4np2/6r1/p7/4q3/8/5K2/8 b - - 5 50', n: 2, line: ['g6g2', 'f2f1', 'e4e2'] },
  { fen: '8/1R6/6Q1/2k5/8/3P1P2/6P1/5K2 w - - 1 50', n: 2, line: ['g6f6', 'c5d5', 'b7b5'] },
  { fen: '8/5R2/7p/1B1p4/P7/8/1PP2RPP/1K1k4 w - - 1 33', n: 2, line: ['f2e2', 'd5d4', 'f7f1'] },
  { fen: 'r1b2rk1/2pp1pq1/pp6/6pQ/1N3PN1/2PBB3/PP4PP/R3K2R w KQ - 3 18', n: 2, line: ['g4f6', 'g7f6', 'h5h7'] },
  { fen: '6k1/2p3p1/2P4p/5p1P/p7/1pb5/2r5/7K b - - 3 44', n: 2, line: ['b3b2', 'h1g1', 'b2b1q'] },
  { fen: '3k4/1P5R/3B4/2P5/2K5/1r6/8/8 w - - 3 59', n: 2, line: ['c4b3', 'd8e8', 'b7b8q'] },
  { fen: 'rq3r2/p2Rb1k1/1p3p2/1B4pQ/8/5N2/PPP2PPP/2K4R w - - 1 18', n: 3, line: ['d7e7', 'f8f7', 'h5f7', 'g7h8', 'f7g7'] },
  { fen: '6k1/4np2/r7/p7/6K1/8/8/1q6 b - - 1 48', n: 3, line: ['b1f1', 'g4g5', 'a6g6', 'g5h5', 'f1h1'] },
  { fen: '8/1R6/6p1/2k5/3p2Q1/8/2P2PP1/5K2 w - - 1 47', n: 3, line: ['g4d7', 'd4d3', 'c2d3', 'g6g5', 'b7b5'] },
  { fen: '8/5R2/7p/1B1p4/P7/5R2/1PPk1rPP/1K6 w - - 11 32', n: 3, line: ['f3f2', 'd2d1', 'f2e2', 'd5d4', 'f7f1'] },
  { fen: 'r1b2r1k/2pp1pq1/pp5N/6pQ/1N3P2/2PBB3/PP4PP/R3K2R w KQ - 1 17', n: 3, line: ['h6g4', 'g7h6', 'h5h6', 'h8g8', 'g4f6'] }
];

export const BEST_MOVE_PUZZLES: readonly BestMovePuzzle[] = [
  { fen: 'r1b1k2r/1pppnppp/8/p3N3/1Q2N3/2P5/PP3PPP/R1B1KB1R b KQkq - 0 11', move: 'a5b4' },
  { fen: '3r1k1r/Qp3pp1/4p3/2p3qp/2B5/5n1P/P1P1KP1P/1R5R b - - 2 19', move: 'f3d2' },
  { fen: 'r5k1/4Rp2/7b/p2n3K/1p6/8/8/8 b - - 0 43', move: 'd5e7' },
  { fen: 'r1b2rk1/pp1p1pp1/5n1p/n2P2N1/1P1Bp3/P1q5/2P1BPP1/R2Q1RK1 b - - 1 15', move: 'c3c7' },
  { fen: '2rqkb1r/2Bn1pp1/ppQ4p/3p4/8/5N2/PPP2PPP/1K1R1B1R w k - 0 14', move: 'd1e1' },
  { fen: 'r3kb1r/ppp1pppp/5n2/4q3/1PP5/P3BP1P/2Q2PP1/R3KB1R b KQkq - 0 11', move: 'e5a1' },
  { fen: 'r1bqkb1r/2pp1p2/pp5p/3NN1pQ/8/3BB3/PPP2PPP/R3K2R b KQkq - 1 11', move: 'f8b4' },
  { fen: 'r1b1k2r/ppp1bpp1/2n4p/3qp3/3P2n1/4PP2/PPPNK2P/R1BQ1B1R w kq - 0 10', move: 'c2c4' },
  { fen: 'r1b1kb1r/ppp1ppPp/2n5/8/8/5N2/PPPB1PPP/R3KB1R b KQkq - 0 8', move: 'f8g7' }
];
